### ISSUE TITLE
[1.7.0] Celestia stops responding when typing object name

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#1014]
**Describe the bug**
When typing any text into the search field, Celestia stops responding for about a minute before registering what has been typed.

**To Reproduce**
1. Press Enter
2. Type any text...like `mars` or `abc` or anything
3. See error

**Expected behavior**
Celestia immediately registers the typed text, as it did in the past.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Frontend: Qt & Win
 - Version: 1.7.0 (latest build as of today)

**Comment by 375gnu** [comment]
@SevenSpheres what about older builds? Now it sounds like a bug introduced by #996

**Comment by SevenSpheres** [comment]
The bug doesn't occur in 1.7.0-dev-485, so it seems it was caused by that PR
