### ISSUE TITLE
Sometimes stars are not visible when they have an apparent magnitude of between 7 and 3

### ISSUE THREAD

**Issue by Trolligi112477-ww** [CelestiaProject/Celestia#1017]
Sometimes, when I am playing celestia, stars aren't visible at all when their apparent magnitude is between 7 and 3. This is really annoying. This seems to only happen with stars in the extras section, though.

This has been happening for at least the last 13 stable builds of Celestia 1.7.0. To replicate this bug, get an addon which adds many stars. Some of them should be invisible between magnitude 7 and 3, but only at certain angles for some reason.

![wr87](https://user-images.githubusercontent.com/66268885/119269327-09bea900-bbef-11eb-92d1-bc5141fb228c.png)
![wr87visible](https://user-images.githubusercontent.com/66268885/119269331-104d2080-bbef-11eb-84b5-d23ecd0fb830.png)

And no, I didn't disable stars on one of the pictures.
Laptop
 - OS: Windows
 - Frontend: Qt
 - Version: 1.7.0

**Comment by 375gnu** [comment]
@Trolligi112477-ww 1) what addon? 2) provide cel:// URLs for testing

**Comment by Trolligi112477-ww** [comment]
1) This is the galactic Wolf-Rayet stars addon that I am still working on. I also have many other addons.
2) approximately cel://Follow/WR%2089/2021-06-18T20:57:20.57190Z?x=AAAAAADk0j4aVi3S/////w&y=AAAAAABquhJxrN/P/////w&z=AAAAAABwdjm5xnbD&ow=0.834038&ox=-0.0397813&oy=0.158199&oz=-0.527039&select=WR%2089&fov=27.7903&ts=1&ltd=0&p=0&rf=138205079&nrf=255&lm=2177&tsrc=0&ver=3

**Comment by SevenSpheres** [comment]
The most recent version of your WRs addon doesn't have WR 89.

**Comment by SevenSpheres** [comment]
Now that the [updated WR catalog](https://celestia.space/forum/viewtopic.php?p=154448#p154448) has been released; I'm unable to reproduce this bug with the above URL on the latest 1.7 build.

**Comment by Trolligi112477-ww** [comment]
cel://Follow/3%20Gem/2021-12-01T16:59:05.44493Z?x=AADYSsuvmYtX/////////w&y=AAC4uoHeUCkl/////////w&z=AAAwaqchFXXV/v///////w&ow=0.1597&ox=-0.833771&oy=-0.41457&oz=0.327803&select=3%20Gem&fov=27.7903&ts=1e+06&ltd=0&p=1&rf=138270615&nrf=255&lm=2183&tsrc=0&ver=3

Does this one work? It doesn't require any mods

**Comment by SevenSpheres** [comment]
Also unable to reproduce with the latest build.

**Comment by Trolligi112477-ww** [comment]
That's annoying

**Comment by Trolligi112477-ww** [comment]
This seems to have been fixed in the newest version of Celestia.
