### ISSUE TITLE
cotire is unsupported since December 2019

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1020]
Ran into this while investigating build breaks using Visual Studio Code on Linux (that defaults to using ninja for its cmake builds), which turned out to be related to the use of cotire. According to the README at https://github.com/sakra/cotire/

> The functionality provided by cotire has been superseded by features added to CMake 3.16. Support for pre-compiling and unity builds is now built into CMake. Thus, there will not be any further updates or support for this project.

It would be worth considering removing cotire from the build process.

**Comment by 375gnu** [comment]
I actually do this in my WIP branch which uses ffmpeg to save captured video.
