### ISSUE TITLE
UniformRotation analog in Cel/Celx

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#104]
We was asking for
```
UniformRotation
{
Period 27.33
}
```
analog, avaliable via scripts.
So, let's find chances to implement it and find if it would be read-only property, as currently Celestia set all content parameters at start, when loading it from ssc files.
Should it be implement in 1.7 release?

**Comment by 375gnu** [comment]
Celx method `celestia:from_ssc()` provides more powerful tool. And it's not so trivial to implement the required method, actually it's almost complete rebuilding of object in-memory representation.

**Comment by 375gnu** [comment]
99%
