### ISSUE TITLE
Enable/disable asteroids, comets and spacecrafts via scripts.

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#105]
We were asked for implementing enabling/disabling (show/hide) via CEL and CELX following object types:
* asteroids
* comets
* spacecrafts
So, as I heard this should be easy, should it also be part of 1.7?

**Comment by 375gnu** [comment]
I've already created core interface for this, only win32 and gtk backends are left. I hope you won't object if I reassign this issue to me?

**Comment by 375gnu** [comment]
Fixed by #116
