### ISSUE TITLE
Deprecation warnings with fmt 8.0.1

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1137]
Using fmt 8.0.1, a large number of deprecation warnings are being generated from calls to overloads of `fprintf` that write to an `std::ostream` (as opposed to a C `FILE`). This is the version of fmt currently supplied by vcpkg, so this can be seen in the Windows build logs. Not sure on the best way to fix this, as switching to the fmt syntax looks like it would break translations.

**Comment by 375gnu** [comment]
Mixing C and C++ output is not recommended, so for the nearest future we can replace `fmt::fprintf(stream, ...)` with `stream << fmt::sprintf(...)` for messages which sh'ld be translated and with `fmt::print(stream, ...)` for other messages.

In long run we sh'ld migrate to `fmt::print` & `fmt::format` and later (i suppose in 4-5 years) to `std::print` & `std::format`.

**Comment by 375gnu** [comment]
fixed by #1138
