### ISSUE TITLE
Fix colors of the G-type stars (eg. Sun)

### ISSUE THREAD

**Issue by VarunS2002** [CelestiaProject/Celestia#1147]
**The Problem**
Even though the Sun is classified as a yellow dwarf (G-type main-sequence). G-type stars actually range in color from white, for more luminous types like the Sun, to only very slightly yellow for the less massive and luminous G-type main-sequence stars. This affects other G-type stars in Celestia too. Notable examples: Alpha Centauri A, 51 Pegasi, Tau Ceti.

**Expected behavior**
All colors to be adjusted based on the temperature, especially for G-type stars. Sun might look like Sirius A.

**Screenshots**
Sun:

![image](https://user-images.githubusercontent.com/30069380/139540841-1b25ca7f-e598-48ea-a58c-d245d2ed266a.png)

Sirius A:

![image](https://user-images.githubusercontent.com/30069380/139540831-95126ae9-35c2-4d2f-8ed0-f710828a29ba.png)

**Desktop**
 - OS: Windows 10
 - Frontend: What is used by default? Native Win I presume
 - Version: 1.6.2.2 release

**Comment by SevenSpheres** [comment]
Celestia has supported blackbody star colors for a *very* long time. In Celestia 1.6.2, blackbody colors can be enabled by typing `%`. In Celestia 1.7.0, blackbody colors are enabled by default.
