### ISSUE TITLE
Upper limit on token lengths?

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1151]
Currently working on a few changes that involve the tokenizer used to parse the various catalog files, one thing I've noticed is it currently allows unlimited token lengths, which would eventually exhaust memory. In order to tighten things up, I am planning to add an upper limit: if the token length is exceeded, the token will be reported as an error and parsing will bail out.

As an initial suggestion, I'm considering putting the limit to 1024 characters (which basically correspond to UTF-8 code units), perhaps with a lower limit (64) for tokens that aren't quote-delimited strings.

Any use cases you can see for supporting longer tokens?

**Comment by 375gnu** [comment]
I agree with your proposal. I don't see any usage scenarios for longer tokens.
