### ISSUE TITLE
Problem with cmodfix

### ISSUE THREAD

**Issue by munix9** [CelestiaProject/Celestia#1163]
**Describe the bug**
Conversion to binary format with cmodfix gives an error.

**To Reproduce**

Conversion to ASCII ~~works~~ seems to work
`$ cmodfix -a /usr/share/celestia/extras-standard/iss/models/iss.cmod a_iss.cmod`

Conversion back to binary format gives the following output
`$ cmodfix -b a_iss.cmod b_iss.cmod`
`Error in model file: Material definition expected (line 4)`

`$ head a_iss.cmod`
```
#celmodel__ascii

material
diffuse 0.839216 0.839216 0.839216
specular 1 1 1
specpower 3.73213
texture0 "issmod.avif"
end_material

material
```
**Expected behavior**
cmodfix -b should not produce an error, as in the last versions
(but maybe the file extras-standard/iss/models/iss.cmod needs to be adjusted too?).

**Screenshots**
nop

**Desktop (please complete the following information):**
 - OS: GNU/Linux openSUSE Tumbleweed 20211111
 - Frontend: Qt
 - Version: 1.7.0~git20211115+b3efa631d-494.1.x86_64

**Additional context**
Version from OBS:
https://build.opensuse.org/package/binaries/home:munix9:unstable/celestia/openSUSE_Tumbleweed

**Comment by 375gnu** [comment]
Sounds like a bug in parser. See #706 as well

**Comment by munix9** [comment]
That would be possible.
However, it worked until recently because I use it when converting the images to avif/dds.

**Comment by ajtribick** [comment]
Typo when I was refactoring the loading - the part that loads the materials was checking for the wrong token.

**Comment by munix9** [comment]
Thanks, works.
