### ISSUE TITLE
GOTO Rotation speed too fast for Dome Planetarium use

### ISSUE THREAD

**Issue by alcomposer** [CelestiaProject/Celestia#1174]
**Is your feature request related to a problem? Please describe.**
Using Celestia in a dome planetarium theatre, GOTO rotation speed is too fast, and induces motion sickness for audience

**Describe the solution you'd like**
Add a setting for `GOTO Rotation Speed` & `GOTO Translation Speed` in either settings or .cfg 

The reason to have a separate speed is that translation can look very good, and exciting in the dome- without any motion sickness. It is mainly rotation of camera that causes motion sickness.

**Comment by munix9** [comment]
A request on this topic:
Would it be possible to include a customized `celestia.cfg`, which could be named e.g. `celestia-fisheye.cfg`, which already contains as default the values suitable for a representation of fisheye/dome?

It would then be easier to use `celestia --conf celestia-fisheye.cfg` to start a corresponding instance that is already well adapted to the requirements of the presentation.

**Comment by 375gnu** [comment]
good idea!

**Comment by alcomposer** [comment]
Would it be possible then to have which <foobar>.cfg is used in Celestia preferences? (Possibly multiple configs for different things).

That way a user can simply select a config for what they need to do.

**Comment by 375gnu** [comment]
Currently you can do the following:

1. Create a file `hook.lua` with the following content:
```
GOTO_TIME   = 20.0
ITER_START  = 0.1
ITER_FINISH = 0.9
ACCEL_TIME = 0.5

function gotoobject(self)
    selection = celestia:getselection()
    observer  = celestia:getobserver()
    if selection and observer then
        observer:gotoobject(selection, GOTO_TIME, ITER_START, ITER_FINISH, ACCEL_TIME)
        return true
    end
    return false
end

keys = {
    g = gotoobject,
}

hook = {
    charentered = function(self, ch)
        fun = keys[ch]
        if fun then
            return fun(self)
        end
        return false
    end;
}

celestia:setluahook(hook)
```
Adjust values of `GOTO_TIME`, `ITER_START`, `ITER_FINISH` and `ACCEL_TIME` to your needs.

2. Edit your `celestia.cfg` (I suggest editing `.celestia.cfg` in your home directory). Add the following line to it
```
LuaHook "hook.lua"
```
If you put the file not to your celestia directory then use the full path to it.

Please note that `ACCEL_TIME` is supported only since today.

**Comment by 375gnu** [comment]
As a solution was proposed let's close this.
