### ISSUE TITLE
Merge QtEclipseFinder into celestia/eclipsefinder.cpp

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#119]
Qt backend uses an own implementation of EclipseFinder, it should be merged back into celestia/eclipsefinder.cpp

**Comment by pirogronian** [comment]
Please explain. 
* what is the  qt backend?
* why qt implementation of something should be merged into celestia core?

**Comment by 375gnu** [comment]
- qt interface
- because in that case we have 2 implementations of the same thing. the 1st one used in gtk & windows backend, and the 2nd in qt. if qt implementation is better, then we should replace the 1st with it (i'm talking about generic bits only, only qt-specific code should remain in qt backend)
