### ISSUE TITLE
[1.7.0] Objects with Class "component" are invisible

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#1195]
**Describe the bug**
If any object is defined with `Class "component"`, it isn't shown. Initially reported by **DaveBowman2001** on the Discord server.

**To Reproduce**
This code destroys the Earth:
```
Modify "Earth" "Sol"
{
	Class "component"
}
```

**Expected behavior**
Earth should still be visible with the above code.

**Screenshots**
[Image of an ISS addon with several components not appearing](https://cdn.discordapp.com/attachments/691413425494032474/916174517846568990/Screenshot_20211203-114915.png)

**Desktop (please complete the following information):**
 - OS: Windows, Android
 - Frontend: Qt, native Win, Android
 - Version: 1.7.0

**Comment by ajtribick** [comment]
Looks like `Renderer::isBodyVisible` ([render.cpp](https://github.com/CelestiaProject/Celestia/blob/a670d8e3be16968e4845ec4325bfc38bd8fbef85/src/celengine/render.cpp#L4000)) needs to use similar logic to how it handles `Body::SurfaceFeature`, extended to support the possibility of having components of components.

It also looks like the existing logic for SurfaceFeature would also go wrong if the SurfaceFeature is defined on a star, as `getPrimary()` would return `nullptr`.
