### ISSUE TITLE
Sprite models are too bright and make Celestia extremely slow

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#1244]
**Describe the bug**
Going near Sagittarius A* from [Vision's addon](https://celestia.space/forum/viewtopic.php?p=155519#p155519) on Celestia 1.7.0 makes Celestia extremely slow, both on desktop and mobile. The sprite effects also appear brighter than they do on 1.6.2, which might be related to #646, although the sprite models used don't have textures defined in the ssc file, and `Emissive true` is set.

**To Reproduce**
1. Download [the addon](https://celestia.space/forum/viewtopic.php?p=155519#p155519)
2. Select and go to `Sgr A*`
3. Try to rotate or zoom or something, and see how slow it is

**Expected behavior**
The addon works as it does on 1.6.2, without massively slowing down Celestia.

**Desktop (please complete the following information):**
 - OS: Windows, Android, macOS(?)
 - Frontend: Qt, Android, native Mac(?)
 - Version: 1.7.0, 1.6.2(?)

**Additional context**
...I just checked the native Windows frontend, and this issue actually does *not* affect that frontend. Minmus on Discord reported having this same issue on 1.6.2, so I think it also affects the macOS frontend, regardless of version.

**Comment by SevenSpheres** [comment]
@ajtribick says:
> not noticing any slowdown on the Qt frontend on Linux

Maybe I should make a table listing the behavior on different setups:

| OS | Frontend | Version | Result |
| ------------- | ------------- | ------------- | ------------- |
| Windows | Win32 | 1.6.2 | Works ✔️ |
| Windows | Win32 | 1.7.0 | Works ✔️ |
| Windows | Qt | 1.7.0 | Slow ❌ |
| Android | Android | 1.7.0 | Slow ❌ |
| macOS | native Mac | 1.6.2 | Slow ❌ |
| Linux | Qt | 1.7.0 | Works ✔️ |

**Comment by SevenSpheres** [comment]
This is happening with dsc sprite models too.

The Bubble Nebula (from [Trolligi's new addon](https://celestia.space/forum/viewtopic.php?f=23&t=21739)) on Win32:
![bubbleneb](https://user-images.githubusercontent.com/56284207/147420675-870e082d-2a89-4478-818e-5a08048c1484.png)

and on Qt - it's also significantly slower:
![bubblenebqt](https://user-images.githubusercontent.com/56284207/147420679-117527cb-ca4c-413d-8f5f-27717df77b4c.png)

**Comment by Trolligi112477-ww** [comment]
This happens to my win 1.7.0 qt install as well. When I'm outside the milky way and it comes into view, the game slows down a lot.

**Comment by SevenSpheres** [comment]
That sounds like it's caused by nebulae; the Sagittarius A* models shouldn't be loaded when it comes into view if you're *outside the Milky Way*. It may or may not be related to this issue; Celestia has always slowed down when loading lots of nebulae at once.

**Comment by DaveBowman2001** [comment]
Tested every sprite-model nebula addon posted on [Addon submissions for mobile](https://github.com/levinli303/celestia.mobi/issues/2) so far, and they are very laggy upon close distances, but occurs only on sprite-heavy models (e.g [Abell 7](https://github.com/levinli303/celestia.mobi/issues/2#issuecomment-1003128714), [IC 3568](https://github.com/levinli303/celestia.mobi/issues/2#issuecomment-1003121219), [MyCn 18](https://github.com/levinli303/celestia.mobi/issues/2#issuecomment-1003124045), etc.). The only sprite model that doesn't lag on Mobile (Android) is the [GK Persei (Firework Nebula)](https://github.com/levinli303/celestia.mobi/issues/2#issuecomment-1003131265) addon

**Comment by SevenSpheres** [comment]
Don't know what changed, but I'm now seeing this on the native Windows frontend as well, even on cartrite's latest build from two months ago.

**Comment by SevenSpheres** [comment]
Reducing screen resolution seems to mitigate this issue. It might be related to that and not frontends, with the introduction of the issue on the native Windows frontend being caused by #1324.

**Comment by levinli303** [comment]
@SevenSpheres yeah it seems so. i've submitted a fix
