### ISSUE TITLE
Stuff that you can add

### ISSUE THREAD

**Issue by Ezebytez** [CelestiaProject/Celestia#1252]
Can you add a button for enhanced star color and can you make a setting for temperature (like Kelvin, Fahrenheit and Celsius)?  can you add a journey log (like the stars or planets that you've been to) so that if we want to go back then we can just go into the journey log and go back to it. Please add all of this it would make the game great!

**Comment by SevenSpheres** [comment]
Not sure why you closed this issue...

> Can you add a button for enhanced star color

Shift+5

> and can you make a setting for temperature (like Kelvin, Fahrenheit and Celsius)?

Good idea, odd that this wasn't added in #1121.

**Comment by levinli303** [comment]
about showing Kelvin/Celsius/Fahrenheit, there are three options so it cannot just map to the metric/imperial options we offer. And it also seems people in the UK don't use Fahrenheit, so we will need to have a separate settings for that.

**Comment by Ezebytez** [comment]
Great!
