### ISSUE TITLE
Build failures on checking out the content submodule

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1260]
There are several recent build failures which are caused by errors checking out the content repository, this may be due to the repository size. It might also make sense to reduce bandwidth by not checking it out on pull requests (which would mean running the individual `git submodule` commands rather than using the `submodules` parameter on `checkout@v2`), possibly also not for builds other than tagged releases?

**Comment by munix9** [comment]
I thought it was a good idea from the beginning to put the content area in its own repository.
On the other hand, the inclusion of the content area as a submodule is not very helpful.
It might be an advantage to make the builds easier, at least the ones that offer the whole package (bin+data).
But I would rather recommend to provide scripts for checking out the content-repo, e.g. prepare.sh, prepare.bat (same for android/apple) or similar stuff.
These can then be called before the build, would then have to be documented accordingly.

Or does the integration as a submodule have a special reason?

**Comment by 375gnu** [comment]
Adding `content` as a submodule was a temporary fix for localization. Now they are independent and we can remove this submodule.
