### ISSUE TITLE
Laggy asteriods

### ISSUE THREAD

**Issue by Ezebytez** [CelestiaProject/Celestia#1263]
Uploading Screen_Recording_20211227-093050_Celestia.mp4…
Why does my game lag when i get close to an asteroid? And it happens on some not all. Fix?

**Comment by Ezebytez** [comment]
Oops the recording didn't work! Here try again 

https://user-images.githubusercontent.com/96560141/147486083-90391aa9-e50e-44ca-af16-4d3b5ac8c28e.mp4

**Comment by SevenSpheres** [comment]
Can you link the addon/ssc file you use so we can test?

**Comment by Ezebytez** [comment]
Its not an ssc file that asteroid came with the game.

**Comment by SevenSpheres** [comment]
No, that asteroid is not included by default. It must be from an addon.

**Comment by SevenSpheres** [comment]
I'm not seeing any lag at 2014 FE72, on Windows or Android.

**Comment by Ezebytez** [comment]
Maybe its just my phone

**Comment by SevenSpheres** [comment]
I see there's another addon, just for extreme TNOs, that also defines this objects. I'll test with that one.

**Comment by 375gnu** [comment]
closing as there no more information provided by the reporter
