### ISSUE TITLE
Generic, user defined categories

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#128]
As estabilished on forum, we need some kind of user defined category system. I propose something similar to tags: multiple categories per object, for more flexibility. Categories database would be generated in fly, during data files loading. I can start it.
Edit: I can also implement dynamic instalation category names localisation.

**Comment by 375gnu** [comment]
Celestia parser supports arrays, so in ssc file we can have 
`usertags [foo, bar]`

**Comment by pirogronian** [comment]
@375gnu 
UserCategory, as well as other my stuff, have static members. Is this good idea, as you are rather removing static objects from Celestia?

**Comment by 375gnu** [comment]
Generally only "trivial" types may be static, see https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables for explanation. Maps, sets, vectors are not trivial, so it better to refactor the code.

**Comment by pirogronian** [comment]
As categories are arleady in master since some time, it seems to be safe to close this issue.
