### ISSUE TITLE
[1.7.0] Greek letter planet names unselectable

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#1297]
**Describe the bug**
Exoplanets with Greek letters in their names are unselectable by those names. This doesn't happen in 1.6.2.

**To Reproduce**
1. Press Enter, type "Ups And A", press Enter - it will be selected
2. Press Enter, type "Ups And Ad", press enter - it should be selected, but won't be

**Expected behavior**
Ups And Ad is selectable by that name when in the Ups And system.

**Desktop (please complete the following information):**
 - OS: Windows, Linux?
 - Frontend: Qt, Win
 - Version: 1.7.0

**Comment by 375gnu** [comment]
29d76471f2790d0d628fc1436f159d002d90bb9b - this commit is to blame
