### ISSUE TITLE
Floating point compilation options

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1308]
A couple of potential issues with the use of `-ffast-math` on non-Windows compilers:

- This enables `-ffinite-math-only` - this prevents detection of infinities/NaN, e.g. in inputs because the compiler is allowed to assume they won't happen, so a call to `std::isnan` or `std::isinf` can be optimized to `false`. I think we should compile with `-fno-finite-math-only` to avoid issues.
- The floating point charconv implementation relies on `errno` (disabled by `-ffast-math`) to detect range errors coming back from `strtof`/`strtod`/`strtold` - this code needs to be compiled with `-fmath-errno`. If it doesn't cause linker issues, we probably don't need to turn this option on in general.

**Comment by 375gnu** [comment]
I can confirm that with these options enabled together with `-ffast-math` Celestia seems to work fine. (And my guess that the problem was with `NaN` is correct).
