### ISSUE TITLE
Make leap seconds configurable

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1309]
**Is your feature request related to a problem? Please describe.**
Leap seconds are currently hardcoded in astro.cpp. This means that the program would need to be recompiled (and new releases produced) if the [IERS](https://www.iers.org/) decides to add another one.

**Describe the solution you'd like**
Move the leap seconds table to celestia.cfg and load it on startup.

**Describe alternatives you've considered**
I suppose we could have a separate configuration file for the leap seconds, but this doesn't seem like a particularly useful option.

**Additional context**
N/A

**Comment by 375gnu** [comment]
Please see #342 and #343 for the same.
