### ISSUE TITLE
Spacecraft & minor moon visibility settings "flipped" on native Windows frontend

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#1332]
**Describe the bug**
On Celestia 1.7.0-win, ~~modeled objects are invisible, regardless of object type (moon, spacecraft, etc)~~ spacecraft and minor moons are invisible if their visibility is turned ON in the "View Options" dialog. They are only visible if visibility is turned OFF. ~~Possibly related to #1330.~~ Neither this issue nor #1330 is present on 1.7.0-qt on Windows.

EDIT: WTF, this issue *is* present on cartrite's build as well. I'm sure it wasn't before.

**To Reproduce**
1. Go to any spacecraft or minor moon, e.g. Hubble, with spacecraft/minor moon visibility turned on
2. See error

**Expected behavior**
~~Modeled objects should be visible.~~ Spacecraft and minor moons should be visible when their visibility option is on in the "View Options" dialog, and not when it's off, instead of the other way around.

**Screenshots**
![invisihubble](https://user-images.githubusercontent.com/56284207/150658429-37d1dd3b-8ef9-48e0-8be6-35002ec06fdd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Frontend: native Win
 - Version: 1.7.0

**Comment by SevenSpheres** [comment]
Update: If I turn visibility of spacecraft and minor moons OFF in the "View Options" dialog, I can see them. So the issue is just that the visibility settings for these object types got flipped somehow.

**Comment by 375gnu** [comment]
I can't reproduce.

**Comment by ajtribick** [comment]
I can reproduce this, will attempt a fix.
