### ISSUE TITLE
Different sensitivity along the axes on elongated screens

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#1344]
**Describe the bug**
The sensitivity of object rotation / FOV movement depends on which axis to move the cursor/finger. It seems now the sensitivity along the axis is proportional to the size of the screen along the axis.

**Expected behavior**
I expect cursor/finger movement and field of view movement to be equal.

**Screenshots**
https://user-images.githubusercontent.com/44873271/151985175-796dc0fa-65bf-4d3b-96be-514440141081.mp4

**Desktop:**
 - OS: at least Windows and Android
 - Frontend: at least Qt, native Win, UWP
 - Version: at least 1.6, 1.7

**Comment by 375gnu** [comment]
Sounds like a different DPI in X and Y direction.

**Comment by levinli303** [comment]
FYI this is fixed when you pass ENABLE_RAY_BASED_DRAGGING=ON to cmake in configuration for building. Default is still OFF.
