### ISSUE TITLE
Build fails with cmake v3.23.0

### ISSUE THREAD

**Issue by knatsakis** [CelestiaProject/Celestia#1357]
**Describe the bug**
Build fails with cmake v3.23.0

**To Reproduce**
1. Clone the celestia git repo
2. Run `cmake -Wno-dev -DLEGACY_OPENGL_LIBS=OFF -DENABLE_CELX=ON -DENABLE_SPICE=ON -DENABLE_NLS=ON -DENABLE_GLUT=OFF -DENABLE_GTK=OFF -DENABLE_QT=ON -DENABLE_SDL=OFF -DENABLE_WIN=OFF -DENABLE_FFMPEG=ON -DENABLE_LIBAVIF=ON -DENABLE_TOOLS=ON -DNATIVE_OSX_APP=OFF -DFAST_MATH=OFF -DENABLE_TESTS=OFF -DENABLE_GLES=OFF -DUSE_GTKGLEXT=OFF -DUSE_QT6=OFF -DUSE_GTK3=OFF`
3. cmake fails with:
```
CMake Error at src/celestia/CMakeLists.txt:84 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "celestia".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * src/celestia/CMakeLists.txt:80 (target_link_libraries)



-- GLUT frontend is disabled.
-- Either not Unix or Gtk frontend is disabled.
-- SDL frontend is disabled.
-- Either not Windows or Windows frontend is disabled.
-- Looking for sqrt in m
-- Looking for sqrt in m - found
-- Configuring incomplete, errors occurred!
```

**Expected behavior**
cmake runs without errors

**Desktop (please complete the following information):**
 - OS: debian/testing with cmake v3.23.0
 - Frontend: Qt
 - Version: commit b4cf176ac3495a0435d123473a154dca5526086d

**Additional context**
I believe this is caused by https://cmake.org/cmake/help/latest/policy/CMP0023.html

**Comment by 375gnu** [comment]
@knatsakis please confirm that #1358 fixes the issue. My cmake despite been 3.23 doesn't fail on `master`.

**Comment by knatsakis** [comment]
Yes! It works for me.

Thank you!
