### ISSUE TITLE
Moon orbits overlap each other with planet visibility on, but don't when planet visibility is off

### ISSUE THREAD

**Issue by TheLostProbe** [CelestiaProject/Celestia#1372]
**Description of the bug**
When the visibility of planets is turned on, the orbits of minor moons, and possibly major moons (I haven't checked), overlap each other. But when the visibility of planets is turned off, most of the orbits stop overlapping, but some continue to overlap. It is noticeable on the minor moon systems of the outer planets in our Solar System, but I found that it is much more visible with the minor moons around Olovis, a planet I am making for CelWP, presumably because of the differences in the orbit colours. You can get it here: https://drive.google.com/drive/folders/1zfp9cKUIUVvEljyad_pJJ8dO7Vn5us5m?usp=sharing
You don't really have to download it, in theory you could just change the orbit colours of some of Jupiter or Saturn's minor moons and theoretically you should see the bug, but I just haven't tested that theory and so, for the sake of simplicity, I gave you the link to it

**To Reproduce**
1. Go to the star "Ereros"
2. Go to "Olovis"
3. Zoom out until you can see the entire moon system, and rotate the camera as to give you a top-down view of the moon system
4. Turn planet visibility off
5. You should see some points on the screen "flicker"
6. Switch back and forth between the on and off visibility setting and you should be able to see that the orbits overlap and un-overlap when the visibility is on and off, respectively

If you decided not to download Olovis, you can just do these same steps but instead of the star and planet being Ereros and Olovis, the star and planet is Sol and Jupiter/Saturn/Uranus/Neptune

**Expected behavior**
The orbits shouldn't overlap. Say you have two orbits, one lower than the other, and Celestia renders them overlapping each other. What should happen is Celestia should render the highest orbit "in front" of the lower orbit

**Screenshots**
[Planet visibility on](https://cdn.discordapp.com/attachments/691413425494032474/987648801047203880/unknown.png)
[Planet visibility off](https://cdn.discordapp.com/attachments/691413425494032474/987648860799246407/unknown.png)

**Specifications**
 - OS: Windows 10 Home 21h2 19044.1706
 - Frontend: Native Win
 - Version: 1.7.0

**Comment by 375gnu** [comment]
@TheLostProbe could you confirm that #1394 makes number of overlapping orbits less than without this fix?

**Comment by TheLostProbe** [comment]
@375gnu just from eyeballing it, it seems that there was a small change in the visibility of this bug. it appears to be less noticeable. weirdly, if you look at the orbits from a certain distance, the flickering bug isnt present. however, once you zoom in enough, it becomes visible again.

also, it is only noticeable with the outer solar system's moons when using certain addons, not in the default config. iirc i have one of those "new moons of jupiter" addons installed, and so the different orbit colours make the bug visible with some of those moons. i think this entire bug is caused by the different orbit colours

**Comment by TheLostProbe** [comment]
update: im an idiot lmao. didnt notice that #1394 hadnt been merged into the master branch yet, and went ahead and downloaded from the master branch, not the merge-depth-spans branch. since #1394 has now been merged, i downloaded it _again_. i can now confidently say that there was a massive change in the visibility of this bug

with planet visibility on
![image](https://user-images.githubusercontent.com/67564416/183772729-50540d1a-bb57-4793-9d1d-2fb07b9103ae.png)

with planet visibility off
![image](https://user-images.githubusercontent.com/67564416/183772769-c03b304c-bb9c-4a3f-abc1-5e908b8faf65.png)

**Comment by 375gnu** [comment]
thanks for confirming
