### ISSUE TITLE
Transparent stars [1.7.0]

### ISSUE THREAD

**Issue by TheLostProbe** [CelestiaProject/Celestia#1397]
when comet tails pass behind a star, the star appears semi-transparent and the comet tail is able to be seen through the star. it is most visible with comets that pass extremely close to the star. i suspect that #1394 may be the cause
this addon is required: [Celestia_Comets.zip](https://github.com/CelestiaProject/Celestia/files/9347402/Celestia_Comets.zip)

**To Reproduce**
1. go to any comet that passes very close to the Sun (such as P/2003 R5 (SOHO))
2. speed up the time until the selected comet reaches periapsis
3. rotate camera until the comet is behind the Sun
4. see error

**Expected behavior**
the comets are behind the star, and so they should be rendered as such. the comets should not be visible through the star

**Screenshots**
![image](https://user-images.githubusercontent.com/67564416/184781075-910718c9-2256-4000-a1e3-21494f929a15.png)

**Desktop**
 - OS: Windows 10 Home 21H2 build 19044.1889 64-bit
 - Frontend: native win
 - Version: 1.7.0 (latest build from **Actions** tab)

**Comment by 375gnu** [comment]
@TheLostProbe please provide a cel:// URL to reproduce the issue.

**Comment by TheLostProbe** [comment]
cel://Follow/Sol/2026-12-22T00:55:37.38029Z?x=ACyXQnsBrDA&y=AEi4r5q7v8z//////////w&z=ANCL22xmnIM&ow=0.10503691&ox=-0.18614677&oy=0.1576447&oz=-0.96408755&select=Sol&fov=30.375294&ts=1&ltd=0&p=0&rf=138205059&nrf=247&lm=2048&tsrc=0&ver=3

**Comment by 375gnu** [comment]
@TheLostProbe https://github.com/CelestiaProject/Celestia/actions/runs/2869541951 should fix the issue, could you validate that it doesn't introduce other regressions?

**Comment by TheLostProbe** [comment]
@375gnu
looks like it worked! and i dont see any issues created by this fix
![image](https://user-images.githubusercontent.com/67564416/184986875-f59a91f8-bb15-425d-986b-571431914044.png)
