### ISSUE TITLE
Depth issue in rendering

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#1403]
**Describe the bug**

Hydra should be behind Charon in the screenshot but it is not, see the white dot on Charon.

**To Reproduce**
cel://Follow/Sol:Pluto:Charon/2022-08-19T23:19:34.77550Z?x=/je0V1xfJg&y=zyqNHKlc6////////////w&z=ggvfXIpn5P///////////w&ow=0.48163635&ox=-0.37898168&oy=-0.789877&oz=0.02221862&select=Sol:Pluto:Charon&fov=30.375292&ts=1&ltd=0&p=0&rf=138205075&nrf=247&lm=2048&tsrc=0&ver=3

**Screenshots**

![E09D1031-1992-43EA-819F-5AA22E1C01F9](https://user-images.githubusercontent.com/17924287/187439601-d56033c9-a31b-4ad7-8e43-a35b7d992cb9.jpeg)

**Comment by 375gnu** [comment]
I hope #1404 fixes it
