### ISSUE TITLE
Orbits have gaps when lines are triangulated

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#1414]
**Describe the bug**
First I found this bug with #1402 and I realized that I forgot to add NextPos for the last 2 vertices. But it persisted then I checked `master` and found it there.

**To Reproduce**
1. Update `Renderer::shouldDrawLineAsTriangles()` to always return `true` or use a device with max line thickness equal to `1px`.
2. Enable planet orbits
3. Disable fading orbits
4. Scroll to see all planets of the Solar system.
5. See error

**Expected behavior**
No gaps.

**Screenshots**
![image](https://user-images.githubusercontent.com/1612688/188286134-f861acb2-4acf-4374-a1f4-2186a4cf7a1b.png)

**Desktop (please complete the following information):**
 - OS: any
 - Frontend: any
 - Version: 1.7.0

**Additional context**
The same orbits with lines drawn as lines doesn't have gaps.

**Comment by levinli303** [comment]
it seems `vec2 transform = normalize(nextPos.xy - thisPos.xy);` resulted in nan, as thisPos and nextPos are the same.

**Comment by levinli303** [comment]
one way to mitigate this issue might be passing in previous point as well, if we see nextPos == thisPos, calculate with prevPos == thisPos.
