### ISSUE TITLE
[1.7.0] celx math functions broken

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#1421]
**Describe the bug**
The attached script used to work on older 1.7.0 builds. Now it returns an error on line 60, "attempt to call a nil value (field 'mod')". Since most of the code is taken from the Lua Tools, the Lua Tools coordinates function is likely also broken.
[getcoords.zip](https://github.com/CelestiaProject/Celestia/files/9549305/getcoords.zip)

**To Reproduce**
1. maybe go to a random location in space first
2. run script
3. see error

**Expected behavior**
The script displays coordinates (RA, Dec, Distance) of the user's current position in space.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Frontend: any
 - Version: 1.7.0

**Comment by 375gnu** [comment]
The latest CI builds for Windows use Lua 5.4 which dropped `math.mod` support. Actually the last Lua version with officailly supported `math.mod` is 5.0. Version 5.1 kept it for backward compatibility but in later versions it doesn't present.

You should replace it either with `math.fmod` of `%` operator. Note they behave differently with negative values.
