### ISSUE TITLE
Stars with custom models render behind orbits, ssc objects, and other stars

### ISSUE THREAD

**Issue by nussun-celestia** [CelestiaProject/Celestia#1422]
**Describe the bug**
Stars with a custom defined cmod model render behind certain other objects, like orbits, ssc objects, and other stars. Some parts of them also render behind other parts of themselves.

**To Reproduce**
1. Download [triangulum_galaxy.stc.zip](https://celestia.space/forum/download/file.php?id=12291&filename=triangulum_galaxy.stc.zip)
2. Download [celwp_vy22.zip](https://github.com/CelestiaProject/Celestia/files/9560026/celwp_vy22.zip)
3. Go to 'CelWP VY22'
4. See bug

**Expected behavior**
The star should render correctly over everything.

**Screenshots**
![image](https://user-images.githubusercontent.com/69641920/189983307-d4a115ac-1ed6-4dab-9f78-151ceca81264.png)

**Desktop:**
 - OS: Windows 10
 - Frontend: Win
 - Version: 1.7.0

**Comment by 375gnu** [comment]
@nussun-celestia please provide minimal working test case

**Comment by nussun-celestia** [comment]
I put some download links, the addon is pretty minimal.

**Comment by nussun-celestia** [comment]
Did you install both addons?

**Comment by 375gnu** [comment]
ok, it's because celwp* is loaded before triang*

**Comment by nussun-celestia** [comment]
Please remove the label if there is no additional information needed.

**Comment by 375gnu** [comment]
@nussun-celestia the root cause is your texture with alpha channel. Objects with such textures are retread as translucent. Convert you texture to jpeg.

**Comment by nussun-celestia** [comment]
Yes, it technically fixes it, but it introduces another bug, where a small part of the model doesn't glow like the rest of it.
![image](https://user-images.githubusercontent.com/69641920/190487797-d20526af-d7c2-455a-a8b3-b2c1231b8518.png)

**Comment by 375gnu** [comment]
> Also make you model fit its radius or you'll some other issues.

**Comment by nussun-celestia** [comment]
Best solution I found for now was to reduce the radius using SemiAxes, but this should have a proper fix.
