### ISSUE TITLE
Please use "nb" for norwegian locales

### ISSUE THREAD

**Issue by StefanBruens** [CelestiaProject/Celestia#1424]
"no" has been deprecated for almost two decades, and current glibc no longer supports "no".

https://www.gnu.org/software/gettext/manual/gettext.html#The-LANGUAGE-variable
> Special advice for Norwegian users: The language code for Norwegian bokmål changed from ‘no’ to ‘nb’ recently (in 2003).

**Comment by StefanBruens** [comment]
Also applies to CelestiaContent

**Comment by levinli303** [comment]
I see that Stellarium is also using nb.po instead of no.po, so I think we can go ahead and the make the change.

**Comment by 375gnu** [comment]
@StefanBruens in version 1.6.2 we have two Norwegian translation: nb and no. Could you tell what language variant is no using, nynorsk or bokmal?

**Comment by StefanBruens** [comment]
Both seem to be bokmal (usage of "en/et").

**Comment by levinli303** [comment]
CelestiaContent repo should also be updated
