### ISSUE TITLE
Invisible black holes

### ISSUE THREAD

**Issue by TheLostProbe** [CelestiaProject/Celestia#1430]
title sums it up well. every black hole is completely invisible no matter what options are selected

**To Reproduce**
1. [download a black hole addon](https://celestia.mobi/resources/category?category=DEAF9C38-7E4B-7DFB-CA72-B496B1652550)
2. go to the black hole
3. zoom into black hole and (optional) rotate camera around as to make it coplanar with the accretion disk
4. see error

**Expected behavior**
the black hole should be rendered as a solid object

**Screenshots**
![image](https://user-images.githubusercontent.com/67564416/191971226-ac051bf6-755b-4318-95dd-df3cbb993a77.png)
![image](https://user-images.githubusercontent.com/67564416/191973196-42b2e04e-07c9-4beb-b040-cc8468aeb7bc.png)

**Desktop**
 - OS: Windows 10 Home 21H2 build 19044.2006 64-bit
 - Frontend: native win
 - Version: 1.7.0

**Comment by 375gnu** [comment]
@TheLostProbe could you confirm that #1433 fixes this issue?

**Comment by TheLostProbe** [comment]
its fixed
![image](https://user-images.githubusercontent.com/67564416/192075867-5d623f7c-8302-4cc0-b7be-16d6ce6fc962.png)
