### ISSUE TITLE
Aurorae visible through planet

### ISSUE THREAD

**Issue by TheLostProbe** [CelestiaProject/Celestia#1431]
aurorae on planets are visible through the planet, eg. the northern aurorae on a planet are visible from the southern side of the planet

1. download cubicApocalypses salib-3 system from [here](https://celestia.space/forum/viewtopic.php?p=151418#p151418)
2. go to the planet "Bluelight" around the black hole "Red Vortex" or "Salib-3 A"
3. you should see the error immediately upon arriving at the planet

**Expected behavior**
aurorae should be depth sorted properly and should not be visible through the planet

**Screenshots**
![image](https://user-images.githubusercontent.com/67564416/191992517-c349056c-a82c-47bc-b8cc-50b59971561a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H2 build 19044.2006 64-bit
 - Frontend: native win
 - Version: 1.7.0

**Comment by SevenSpheres** [comment]
[This](https://celestia.space/forum/viewtopic.php?p=159192#p159192) is probably the same issue.

**Comment by 375gnu** [comment]
@TheLostProbe @SevenSpheres could you confirm that #1433 fixes this issue?

**Comment by TheLostProbe** [comment]
yep, it is fixed
![image](https://user-images.githubusercontent.com/67564416/192076028-29cd5c30-d0f6-42af-bb8c-ce20cc457840.png)
