### ISSUE TITLE
1.6.2.2 x86_64 ignores some addons

### ISSUE THREAD

**Issue by delboy85341** [CelestiaProject/Celestia#1439]
**Describe the bug**
I've found a problem with celestia-1.6.2.2.x86_64.AppImage.   I installed two addons using the -e option to specify an additional extras directory.  I installed two addons, and they work.  I installed two other addons but Celestia ignores them.

These are the four addons I instlled.
These two work.
http://www.celestiamotherlode.net/addon/addon_240.html
http://www.celestiamotherlode.net/addon/addon_1014.html

These two are ignored.  They do nothing.  They work on the windows version.  Both are modifications of Pluto and Charon using data from New Horizons.
http://www.celestiamotherlode.net/addon/addon_1656.html
http://www.celestiamotherlode.net/addon/addon_1660.html

To Reproduce create a celestia directory in your home directory. In the celestia directory, put an extras directory and put the addons in it.

Open a terminal in the Celestia directory (/home/USER/celestia then launch Celestia.
./celestia-1.6.2.2.x86_64.AppImage -e ~/celestia/extras/

Once it launches, look at the sun and you'll see solar flares.  Go to Mars and you'll see a more detailed image of Mars than the default.

Then go to Pluto and you'll see the default images of Pluto and Charon.

I should see the images of Pluto and Charon that came with the addons, not the default images that were there before I installed either of the Pluto addons.  They do work on the Windows version.

This machine has Kubuntu 22.04 installed.

**Comment by JohnVV** [comment]
to me this sounds like a appimage issue, i was the one that checked the celestiamotherload addons to make sure that worked on linux .

most linux distros have Celestia in the software repos , have you tried installing that one ?

**Comment by delboy85341** [comment]
> to me this sounds like a appimage issue, i was the one that checked the celestiamotherload addons to make sure that worked on linux .
> 
> most linux distros have Celestia in the software repos , have you tried installing that one ?

It's not in the repos for ubuntu 22.04.  I haven't seen Celestia in the repost for ubuntu since about 16 or 18.  When I used to run Ubuntu 20.04, I found a repo that I could add so I could install Celestia.  So far I haven't been able to find one for Ubuntu 22.04.  I tried compiling from source, but something went wrong and I don't know enough about compiling from source to figure out how to fix it.    If anyone knows a repo that will allow me to install Celestia on 22.04, please let me know.  John, thanks for your reply.

**Comment by delboy85341** [comment]
I did a little more looking around and found this page.  I followed the instructions and Celestia is now installed and working properly.  Thanks.

https://software.opensuse.org/download.html?project=home:munix9:unstable&package=celestia
