### ISSUE TITLE
Crashes with meshoptimizer

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#1445]
I enabled meshoptimizer in the latest beta on mobile builds and am seeing some crashes, but no idea what model is causing the crash:

Android:
https://appcenter.ms/orgs/CelestiaProject/apps/Celestia-1/crashes/errors/3077834076u/overview

```
libc.so
0x3dabbe20 + 572960
libc.so
0x3dabbdf0 + 572912
libc.so
0x3dabc1ec + 573932
libcelestia.so
meshopt_optimizeVertexCacheTable(unsigned int*, unsigned int const*, unsigned long, unsigned long, meshopt::VertexScoreTable const*) vcacheoptimizer.cpp:173
libcelestia.so
cmod::Mesh::optimize() mesh.cpp:471
libcelestia.so
cmod::Model::sortMeshes(cmod::Model::MeshComparator const&) model.cpp:357
libcelestia.so
GeometryInfo::load(std::__ndk1::__fs::filesystem::path const&) meshmanager.cpp:481
libcelestia.so
ResourceManager<GeometryInfo>::find(int) resmanager.h:103
libcelestia.so
Renderer::addRenderListEntries(RenderListEntry&, Body&, bool) render.cpp:3736
libcelestia.so
Renderer::buildRenderLists(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, celmath::Frustum const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, FrameTree const*, Observer const&, double) render.cpp:3915
libcelestia.so
Renderer::buildNearSystemsLists(Universe const&, Observer const&, celmath::Frustum const&, double) render.cpp:5673
libcelestia.so
Renderer::draw(Observer const&, Universe const&, float, Selection const&) render.cpp:1526
libcelestia.so
CelestiaCore::draw(View*) celestiacore.cpp:2239
libcelestia.so
CelestiaCore::draw() celestiacore.cpp:2149
```

iOS:
https://appcenter.ms/orgs/CelestiaProject/apps/Celestia/crashes/errors/2380106194u/overview

The symbolicated android crash log has line info inside the library is pointing to https://github.com/zeux/meshoptimizer/blob/1cfd09893292e5842ba44e93709779ea28639675/src/vcacheoptimizer.cpp#L173

**Comment by munix9** [comment]
FYI: The packages for openSUSE on OBS are built with `meshoptimizer 0.18`, including the AppImage.  
So far no problems, but only tested with the default data and without extensions.  
I'm also trying to adapt the Debian/Ubuntu packages to build with meshoptimizer, so there might be a wider test base of users.  
Would that help isolate the problem (if it's not just a specific issue on mobile platforms)?

**Comment by 375gnu** [comment]
I once observed the issue on my system, but I don't remember what data were used, I have some test data.

**Comment by levinli303** [comment]
looking only at the code it should be model having index count that is not multiply of 3, maybe we should check it before calling into meshoptimizer?

**Comment by munix9** [comment]
Debian/Ubuntu packages on OBS are now built with meshoptimizer 0.18.  
meshoptimizer 0.18 is also available as Debian/Ubuntu package on OBS in the same repository as celestia.

**Comment by normanr** [comment]
I assume meshoptimizer only understands `TriList` primitive group types (otherwise why would it assert that the index_count is a multiple of 3), but it's (incorrectly) called for all group types. One workaround is to make sure that there is more than one group in the mesh (which disables the optimizer, assume they're not merged by `mergePrimitiveGroups`):

https://github.com/CelestiaProject/Celestia/blob/b57a94a5742f059ade43f680105db01a39b10c23/src/celmodel/mesh.cpp#L359-L366
