### ISSUE TITLE
Config file should not be system wide

### ISSUE THREAD

**Issue by mattiaverga** [CelestiaProject/Celestia#1459]
The default config file should be provided under `/etc` and should be overridden by a custom config in the user home directory (under the appropriate XDG directory), so that it can be easily customized by different users.
Or, better, just create the default config under user home when the program is first run.

**Comment by 375gnu** [comment]
Regarding `/etc` - we support 5 different OS, some of them supports different installation ways (OS packages, `make install`, macOS bundles, etc) which require different config file location (`/etc`, `/usr/local/etc`, `$PREFIX/etc`, file in the data dir). So keeping the default config file in the data dir is a least common denominator for all systems. We leave to package maintainers to move it to `/etc` if their system demands this.

We override the default config, see https://github.com/CelestiaProject/Celestia/blob/master/src/celestia/celestiacore.cpp#L3754

As we provide default config it doesn't make sense to write it by the Celestia itself.
