### ISSUE TITLE
Your Website Source Code Has Been Used Without Permission Or Intention.

### ISSUE THREAD

**Issue by snvike** [CelestiaProject/Celestia#1491]
In my country, a person want to share the source code of your website
“celestia.space”, but he didn’t give the information of the code.
That is, he didn’t say that the code is from your website.I think this violated your rights, so I told him to add the info. But he refused to do that. I don’t know if this really violated your rights.If it really does, please let him correct his behavior.Thanks!

I tried to send emails but they were returned. Hope you can protect your rights.

**Comment by TheLostProbe** [comment]
what do you mean he used our website's source code? please send a link to said site
also, this issue would be better off in the [www repository](https://github.com/CelestiaProject/www)

**Comment by snvike** [comment]
Sorry, I know it now. And this is the page :  https://www.qwbk.net/2654.html
they spread it without telling people who download it where it is from

**Comment by TheLostProbe** [comment]
this is not a violation of anything. our website is actually a heavily edited website template from Pixelarity called Landed (see [this link](https://pixelarity.com/landed)). he has simply used the same template that we used, which should not be uncommon considering the template has around 500000 downloads last time i checked

**Comment by snvike** [comment]
thanks for your reply
