### ISSUE TITLE
CMake Error in Visual Studio 2017

### ISSUE THREAD

**Issue by lodp** [CelestiaProject/Celestia#15]
Hi getting the following CMake error - anyone tell me what I'm missing please?

1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Stephen\AppData\Local\CMakeBuild\01ec6fa0-891c-e932-b1f6-102a4aedd859\build\install"  -DCMAKE_CONFIGURATION_TYPES="Release" "C:\Users\Stephen\Source\Repos\Celestia\thirdparty\Eigen\Eigen"
1> Working directory: C:\Users\Stephen\AppData\Local\CMakeBuild\01ec6fa0-891c-e932-b1f6-102a4aedd859\build\x86-Release
1> -- The C compiler identification is MSVC 19.10.25019.0
1> -- The CXX compiler identification is MSVC 19.10.25019.0
1> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
1> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
1> -- Detecting C compiler ABI info
1> -- Detecting C compiler ABI info - done
1> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
1> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
1> -- Detecting CXX compiler ABI info
1> -- Detecting CXX compiler ABI info - done
1> -- Detecting CXX compile features
1> -- Detecting CXX compile features - done
1> CMake Error at C:\Users\Stephen\Source\Repos\Celestia\thirdparty\Eigen\Eigen\CMakeLists.txt:1 (include):
1>   include could not find load file:
1> 
1>     RegexUtils
1> 
1> 
1> CMake Error at C:\Users\Stephen\Source\Repos\Celestia\thirdparty\Eigen\Eigen\CMakeLists.txt:2 (test_escape_string_as_regex):
1>   Unknown CMake command "test_escape_string_as_regex".
1> 
1> 

``1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Stephen\AppData\Local\CMakeBuild\01ec6fa0-891c-e932-b1f6-102a4aedd859\build\install"  -DCMAKE_CONFIGURATION_TYPES="Release" "C:\Users\Stephen\Source\Repos\Celestia\thirdparty\Eigen\Eigen"
1> Working directory: C:\Users\Stephen\AppData\Local\CMakeBuild\01ec6fa0-891c-e932-b1f6-102a4aedd859\build\x86-Release
1> -- The C compiler identification is MSVC 19.10.25019.0
1> -- The CXX compiler identification is MSVC 19.10.25019.0
1> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
1> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
1> -- Detecting C compiler ABI info
1> -- Detecting C compiler ABI info - done
1> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe
1> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x86/cl.exe -- works
1> -- Detecting CXX compiler ABI info
1> -- Detecting CXX compiler ABI info - done
1> -- Detecting CXX compile features
1> -- Detecting CXX compile features - done
1> CMake Error at C:\Users\Stephen\Source\Repos\Celestia\thirdparty\Eigen\Eigen\CMakeLists.txt:1 (include):
1>   include could not find load file:
1> 
1>     RegexUtils
1> 
1> 
1> CMake Error at C:\Users\Stephen\Source\Repos\Celestia\thirdparty\Eigen\Eigen\CMakeLists.txt:2 (test_escape_string_as_regex):
1>   Unknown CMake command "test_escape_string_as_regex".
1> 
1>

**Comment by CelestiaProject** [comment]
https://celestiaproject.net/forum/viewtopic.php?f=15&t=17702
