### ISSUE TITLE
Bad eclipse shadows

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#1509]
Master:
![bad](https://user-images.githubusercontent.com/1612688/212496286-ebc13f34-e7e5-44e9-80b0-38022468afff.png)

ec232b7f seems to be good:
![good](https://user-images.githubusercontent.com/1612688/212496276-1f4ddb28-b916-4e25-8e84-8191a22fa73f.png)

**Comment by TheLostProbe** [comment]
i've seen this occur with rings as well as ring shadows. it seems to vary in intensity with different planets, and on some it doesn't occur at all
![image](https://user-images.githubusercontent.com/67564416/212521493-d3a80689-0d18-4e3e-a5db-b2ffe1593df9.png)
![image](https://user-images.githubusercontent.com/67564416/212521537-df0b5c23-d7ac-4ea0-872b-fd78a89af140.png)
![image](https://user-images.githubusercontent.com/67564416/212521561-f7c3dac6-4e29-40a0-954d-3c5df03ae591.png)
doesn't look like it occurs with moon shadows
![image](https://user-images.githubusercontent.com/67564416/212521586-e87368fa-4b64-4a65-9ca3-08c46c7be6e8.png)
maybe it's just aliasing really hard
