### ISSUE TITLE
Very bad galaxy rendering performance

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#1510]
Need to find a way to reduce glBufferData calls

**Comment by 375gnu** [comment]
We can increase VBO size

**Comment by 375gnu** [comment]
cb379e4d0470e43489d73a9607940f9040c93fb1 is the root cause

**Comment by 375gnu** [comment]
The main problem is https://github.com/CelestiaProject/Celestia/blob/master/src/celengine/galaxy.cpp#L143. Here we allocate every buffer (vbo & vio) twice. Replacement of `glBufferData` on lines 145 and 146 with `glBufferSubData` will give ~10fps, but this is still lower then original code. With additional smaller buffers it's possible to have a few fps more, but still I don't have stable 60fps.

**Comment by 375gnu** [comment]
@levinli303 if you want to release a new mobile version you can simply revert cb379e4d0470e43489d73a9607940f9040c93fb1 temporary

**Comment by 375gnu** [comment]
Next issue is that Celestia draws invisible galaxies. We should find a way to fix this.
