### ISSUE TITLE
Celestia icon replaced with Wayland icon

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#1525]
There was actually another bug on Wayland that was harmless enough to be shelved

**Describe the bug**
Celestia icon failure leads to replacement with the Wayland's logo icon. Both taskbar and window cases. The main window displays the wrong icon from the start, while the process is more complicated for the taskbar:
1. Celestia icon with a loading status
2. Celestia icon with a loading status + (splash?) window with the Wayland icon
3. Celestia icon with a loading status + 3 windows with the Wayland icon
4. Celestia icon with a loading status + (main) window with the Wayland icon
5. (main) window with the Wayland icon

KDE tends to delay the rendering of the loading icon, so perhaps the icon should actually disappear instantly

**Expected behavior**
(main) window with the Celestia icon

**Screenshots**
https://user-images.githubusercontent.com/44873271/215320211-654ef136-4533-4d80-ab85-54cd207111dd.mp4

**Desktop:**
 - OS: openSUSE Tumbleweed + KDE with Wayland session
 - Frontend: Qt 5
 - Version: 1.7.0, all the versions since last year

**Comment by ajtribick** [comment]
https://nicolasfella.de/posts/fixing-wayland-taskbar-icons/ seems relevant here?

**Comment by Askaniy** [comment]
> Make sure your application actually has such a .desktop file installed to /usr/share/applications/

> Now all we need to do is make sure that the window correctly reports the name of the .desktop file to the compositor.

.desktop file is ok, and I'm sure Celestia connected to it, you can see the icon after launch. I think multiple windows break it. Can't check if `QGuiApplication::setDesktopFileName("celestia")` able to fix it

**Comment by ajtribick** [comment]
I think it should be `QGuiApplication::setDesktopFileName("celestia-qt.desktop")` but I am not yet able to reproduce the issue locally

**Comment by Askaniy** [comment]
It was fixed 👍
