### ISSUE TITLE
Update copyright year in readme

### ISSUE THREAD

**Issue by darigovresearch** [CelestiaProject/Celestia#1539]
**Describe the bug**
Copyright year in readme is out of date

**To Reproduce**
1. Go to readme

**Expected behavior**
Year should be `2001-2023`

**Screenshots**
![image](https://user-images.githubusercontent.com/30328618/216782517-4f4ad99b-4c77-4b7a-a5b3-459427722aca.png)

**Desktop (please complete the following information):**
 - OS: NA
 - Frontend: NA
 -  Version: NA

**Additional context**
NA

**Comment by darigovresearch** [comment]
Pull request https://github.com/CelestiaProject/Celestia/pull/1540 would resolve this issue

**Comment by 375gnu** [comment]
thanks for reporting and fixing

**Comment by darigovresearch** [comment]
@375gnu you're very welcome & thanks for merging!
