### ISSUE TITLE
Strange Saturn rings render with 1024x512 px PNG

### ISSUE THREAD

**Issue by Lepestronik** [CelestiaProject/Celestia#1546]
**Describe the bug**
Strange Saturn rings render if you use 1024x512 px PNG texture (used in Celestia Origin) instead of 1024x1 px PNG one (used in 1.7.0).

**To Reproduce**
1. Unpack [Saturn_rings_bug.zip](https://github.com/CelestiaProject/Celestia/files/10611686/Saturn_rings_bug.zip) to Celestia folder.
2. Run Celestia and go to Saturn.
3. See the rings like they are a bicycle wheel.

**Expected behavior**
True rings render like it was before with 1.6.1, 1.6.2 and 1.6.2.2.

The picture made with 1.6.2.2.
![Saturn_1 6 2 2](https://user-images.githubusercontent.com/89343875/216835326-51bc072d-ff02-405f-881f-1453e1d35943.png)

**Screenshots**
![Linux Saturn](https://user-images.githubusercontent.com/89343875/216835421-bb9949fa-9ac1-44de-a5f6-814ae1d7b479.png)

**Desktop:**
 - OS: Linux Mint 20.3 Cinnamon, Windows 8.1, Windows 11.
 - Frontend: Qt, native Win.
 - Version: 1.7.0.

**Comment by 375gnu** [comment]
You should update your ring textures to be 1px width.

**Comment by Lepestronik** [comment]
Why can't we leave it as it was? This at least violates backward compatibility for data.

**Comment by 375gnu** [comment]
No. Old code was using GL_QUAD which is not supported by newer GL versions and graphic hardware. I don't know how GL libraries emulate QUADS to make 2D textures work.

**Comment by Askaniy** [comment]
Okay, so be it, but leaving artifacts is still not a good idea. It would be smart to check rings textures for the height, and throw an error if it's not supported.
