### ISSUE TITLE
New exoplanet properties

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#155]
* Mass
* Density
* ESI (Earth Similarity Index), see http://phl.upr.edu/projects/earth-similarity-index-esi
* ?

**Comment by pirogronian** [comment]
I've already thought about universal, user defined properties, by analogy to currently developed categories. It could be used as long as doesn't affect rendering and other in-Celestia behaviour.

**Comment by 375gnu** [comment]
For those options are rather useful to be displayed by the core, at least in a verbose mode.

**Comment by pirogronian** [comment]
Yeah, this is complication. So we can implement it inside the core or go deeper and make internal object info box also programmable.

**Comment by LukeCEL** [comment]
Adding parameters like "Mass", "Density", etc. would make the information section below the object name more detailed. However, I don't know if that's necessary; neither of them would have any effect on how the appearance or orbit of the planets.

**Comment by Askaniy** [comment]
The support of "Mass" parameter in ssc will allow displaying the calculated density and programmatically calculating the orbital period of the object’s satellite. Not so much, but the lack of mass support, being one of the main parameters of the object, is often perceived negatively by many when comparing Celestia with other similar programs.

**Comment by LukeCEL** [comment]
Good point. If Celestia is compared negatively to other programs, then it's probably a good thing to add.

**Comment by 375gnu** [comment]
ESI can be easily calculated, so I will not include it.

**Comment by 375gnu** [comment]
Mass and density is implemented in #183. ESI can be calculated.
