### ISSUE TITLE
Landing locations on ellipsoidal bodies

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#1557]
**Problem:**
For bodies using constructions `SemiAxes` and `Oblateness`, the positions of locations are approximated by a sphere, and they are floating in space (see the screenshots below).

**Way to solve:**
Let's notice, that
- Celestia uses planetocentric (projection from center) coordinate system for texturing models and for their locations
- Celestia uses planetographic (projection by normal) for texturing ellipsoids, and _spherical approximation_ for their locations

So, request is to implement recalculation of input planetographic longitude (λ), latitude (φ) and height (h) into x, y, z coordinates using ellipsoid proprieties (semiaxes a_x, a_y, b). I found the formulas in [DOI 10.1007/s00190-011-0514-7](https://link.springer.com/article/10.1007/s00190-011-0514-7):
![formulas1](https://user-images.githubusercontent.com/44873271/218064798-f7f913e9-5f17-4342-9b94-1c5e84d70b1d.png)
![formulas2](https://user-images.githubusercontent.com/44873271/218061889-2fa0a718-ec6b-4952-890f-6edb197d95f8.png)

![Screenshot_20230131_120154](https://user-images.githubusercontent.com/44873271/218057458-042f6ce3-5959-4ce6-b8aa-760c0b05d30b.png)
![Screenshot_20230130_210805](https://user-images.githubusercontent.com/44873271/218057632-e9f22bee-9870-4059-99a9-72f4a1957d4c.png)
(Duplicate here from the Discord server)

**Comment by 375gnu** [comment]
@Askaniy could you provide test addons?

**Comment by Askaniy** [comment]
These locations of Ceres already in the content, I think they are good for testing

**Comment by 375gnu** [comment]
The formulae should be adjust a bit to match Celestia coordinate system but the result is good:
![image](https://github.com/CelestiaProject/Celestia/assets/1612688/d4fddfe2-9096-4b5f-9ff9-265a0fe6cd13)

**Comment by 375gnu** [comment]
But with an object placed on a planet surface image is broken due to #542:

![image](https://github.com/CelestiaProject/Celestia/assets/1612688/f22afc0d-1639-4fea-8ef6-c2e342cc9656)

So I gonna fix this for locations only for now.

**Comment by SevenSpheres** [comment]
At least with the [build from the pull request](https://github.com/CelestiaProject/Celestia/actions/runs/5677998213), locations on Ceres are fixed with its actual oblateness, but I just found that if I modify an object to increase its oblateness to 0.5, locations are still floating in space:
![flatmars](https://github.com/CelestiaProject/Celestia/assets/56284207/5ebfa2b9-a82f-4e26-b8ca-0b97c86ec3bf)
