### ISSUE TITLE
Build the Qt front-end on the gnulinux-arm64 configuration

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1567]
I noticed that the gnulinux-arm64 workflow builds the legacy GTK front-end and not the Qt front end. Would it be possible to enable Qt5 builds on this target? (I'm not entirely sure which particular distribution is being used for that runner though)

**Comment by 375gnu** [comment]
It uses Oracle Linux 8

**Comment by 375gnu** [comment]
fixed buy #1568
