### ISSUE TITLE
URL parser should treat TintedIllumination as a new render flag

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1579]
The URL parser code treats `TintedIllumination` as the last render flag supported by 1.6.x, however this setting is not in the 1.6 codebase: the last 1.6.x setting is actually `ShowEcliptic`. The consequence is that any cel URL generated in 1.6.x will switch the `TintedIllumination` flag off in 1.7.x. Probably `TintedIllumination` should be handled in the `nrf` query parameter, and presumably we need to avoid breaking any URLs that have already been generated by people using the 1.7.x prereleases.

**Comment by 375gnu** [comment]
I don't think there are many new urls so we can safely break them.
