### ISSUE TITLE
User input data translation

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#159]
As Celestia have now ability to import new data, provided by user, there is a queston about translating such a data (for example - celestial object names, user defined category names etc). Current approach is usage of gettext, as for every other translatable string. But users providing new string are unable (without messing with system files) to provide translation for it. I see to solutions (not secessarily exclusive):
1. Allow users to bind own text domains and use dgettext when translating particular string.
2. Allow users to provide translations directly.
In both cases there would be a new class, incorporating string and translation method: domain name or array with translations.

**Comment by 375gnu** [comment]
I thought about the 1st method.

**Comment by pirogronian** [comment]
So, here is my proposition (being realized here #164 ).
To allow non-privileged users to bing their own translations, we have to know, where these translations are located. Gettext allows binding many directories with translations, but every such a directory have to be linked with unique domain. So, we have to allow users to define custom domains. 
We cannot assume that every string user want to translate is provided by the same user. So, users have to be allowed to alter trasnaltion process inside Celestia core. I want to enable this by pairing every user-translatable string with domain name.
Pair { text-domain name } is named Translatable. Extracting i18-d string is achieved dynamically, which solve problem with changing program language during runtime, but increase CPU usage.
Translation struct is an extension of Translatable with cached translated string. It saves CPU time, but need to call update() when language is changed.
Where Trasnatable or Translation could be used? As a names of celestial objects, which are provided externally: Bodies, Stars, DSOs and Locations. Access to it would be provided analogically to current way - by getName/setName etc.
From user point of view, this would be most obvious with Lua. Catalog file interface integration: SSC, STC, DSC and binary is hereby put for discussion.

**Comment by 375gnu** [comment]
How Celestia will load your custom text domain? `dgettext` loads domains only from "standard" directories.

Why do you want to add a new additional class? All objects have `name` and `i18nName` fields, so they just need is a domain id, which **can** be a string, but I suggest to create a translation manager (it can be just a `std::vector` with .mo paths, so the domain id is an index). Please keep the code as simple as possible, don't overengineer, that's not Java.

SSC and friends are 1st class citizens, so if your change doesn't support them it's useless.

**Comment by pirogronian** [comment]
What is "standard directory"? Do ypu mean there is a better function than dgettext? Or something better than gettext package?

I just prefere to have single mechanism than multiple similar in many places. Moreover, some objects can have many names. Translatable names should be also with user categories.

I will support ssc and friends as soon as we agreed about core solution.

**Comment by 375gnu** [comment]
On 12/10/18, pirogronian <notifications@github.com> wrote:
> What is "standard directory"? Do ypu mean there is a better function than
> dgettext? Or something better than gettext package?

"Standard directory" is usually `$prefix/share/locale`. To use mo
files outside it you need `bindtextdomain`.

> I just prefere to have single mechanism than multiple similar in many
> places. Moreover, some objects can have many names. Translatable names
> should be also with user categories.

I assume it will look like
```
void updateTranslations()
{
for (auto& o : allObjects) o.name.update();
}
```

where `update` calls `bindtextdomain` and `dgettext`

alternative way looks like

```
void updateTranslations()
{
for (auto& o : allObjects) {
  bindtextdomain();
  n = dgettext();
  o.setName(n);
}
}
```

The same, but generally simplier.

**Comment by 375gnu** [comment]
For context dependent translations we have `dcgettext`. There is no need to cache its returned value as a context is applied for a few strings (in 99% for one string) only. For other case caching is a must.

**Comment by pirogronian** [comment]
According to [man page](https://linux.die.net/man/3/dcgettext), category passed to `dcgettext` refers to LC_{type} type constant. So, provided context very limited. I thought about user-defined context (by binding own text domain).

**Comment by 375gnu** [comment]
Actually I was thinking about https://www.gnu.org/software/gettext/manual/html_node/Contexts.html

**Comment by pirogronian** [comment]
So, we will use `pgettext`. Ok.
But I'm afraid about memory. Ready translation is allocated by gettext and we have to remember only pointer to const char. But except that we have 3 strings: main text, domain text and, sometimes, context text. Three `string class` objects. I wonder if in most cases coresponding strings are already allocated as in-code literals.

**Comment by 375gnu** [comment]
On 12/10/18, pirogronian <notifications@github.com> wrote:
> But I'm afraid about memory. Ready translation is allocated by gettext and
> we have to remember only pointer to const char. But except that we have 3
> strings: main text, domain text and, sometimes, context text. Three `string
> class` objects. I wonder if in most cases coresponding strings are already
> allocated as in-code literals.

For domain name you don't need more then one string stored inside
translation manager. As I said it can be implemented as a wrapper for
std::vector, so objects will store just a index in this vector.
Context is hardcoded into the application code.

**Comment by pirogronian** [comment]
Context and domain may be also provided by ssc-and-family files, and by lua scripts. So, we need at least two managers (or just two containers).
However, there could be passing same string (but different instances) both to translatable and manager, without any trouble except memory wasting.

**Comment by pirogronian** [comment]
Hard to find, athough I assumed it's better to provide possibility (with little cost), than provide patches, when need emerges.

**Comment by pirogronian** [comment]
`dpgettext` is missing on my system. I learned from Internet I have to run `gettextize` in project directory. But running `gettextize -n` in root Celestia catalog give:
`gettextize: *** Missing configure.in or configure.ac, please cd to your package first.
gettextize: *** Stop.`

**Comment by 375gnu** [comment]
> dpgettext is missing on my system. I learned from Internet I have to run gettextize in project directory. But running gettextize -n in root Celestia catalog give:

You can add it manually, it's just a few files in /usr/share/gettext.

> Hard to find, athough I assumed it's better to provide possibility (with little cost), than provide patches, when need emerges.

Nope. It will not emerge. You misunderstand translation contexts. They are used to distinguish such cases like one original word is used for different things (Homonym). Or when original word has the same form in different cases but translated word has different forms, for example `Earth` is `Ziemia` in Polish, but `Follow Earth` becomes `Śledź Ziemię`, without gettext contexts you'll have wrong `Śledź Ziemia` instead.

What's the purpose of your proposed context in ssc-files? I don't see it. It will be just a dead unused code. Don't forget about main Unix principle - KISS.

**Comment by pirogronian** [comment]
@375gnu Please judge if my implementation of static objects is valid.

**Comment by 375gnu** [comment]
It seems that you did it correctly.

BUT you just don't hear me. Your approach is terribly overengineered  without any good reason.

**Comment by pirogronian** [comment]
I still don't understand. Which approach will be better?

**Comment by 375gnu** [comment]
All you need is to add a new private member for all objects, let's call it `int i18nDomainId{ 0 };` (+ getter & setter) and a new class `TranslationManager` as simple as `class TranslationManager { std::vector domains; }` with 2 public methods `addDomain()` & `getDomain(int domainId)`.

In `setName` you check if i18nDomainId == 0 the use `gettext` else `bindtextdomain` if required + `dgettext`.

That's all.

We'll have just a few new domains so `O(n)` is not a problem for `TranslationManager::addDomain()`. And even if we have 100 domains it won't be a big problem as vector is checked on startup only.

**Comment by pirogronian** [comment]
What about changing language at runtime?
What about objects with multiple names?
How to know at name set the domain id?
My approach is simplufication by unification. "overengeenering" isn't a big issue to me, especially compared to Celestia scattered code.

**Comment by 375gnu** [comment]
1. How your approach helps this issue? In any case you'll need to run updateTranslation (see above).
1. What objects? And why with simple approach you unable to handle them? _("Name 1"), _("Name 2"), _("Name 3"). What the problem?
1. int getDomainId() { return domainId; } :)
1. How long will you involved in Celestia? Why do you think that future maintainers will be happy with your code? Your code should be as simple as possible. Overengineering is real issue, abstractions, fabrics, common virtual classes for everything, and as a result your program takes 20 minutes for startup.

It seems that your are IT student and want to implement everything you're taught  at classes, but to architect your program properly you need years of experience. You don't have them, me neither.

**Comment by pirogronian** [comment]
1. In your method I don't see, how updateTranslation would be implemented. You provided only domains container, while to update all strings we need them in database.
2. Stars and DSOs. More specifically, they have names in appropriate databases, internally in `std::map` and `multimap` containers. Should I just provide second container with translated names?
3. I meant what is criterion domainId choose. Why not directly by passing string?
4. I think that virtual classes don't increse startup time so much, but never mind... I'm involving since may, when I introduced CelestiaCoreApplication. I always appreciated your comments, but now I think you're overreacting :) We never will be sure if next developer will be happy with our code, but I'm sure I won't be happy with current overepeating and over overdifferential code. I'm sure that making it more unified and compact can only help.

**Comment by 375gnu** [comment]
1. I haven't checked yet how to iterate over all objects because I don't assess runtime language switch a high priority feature. 99.9999% applications don't have this feature and nobody complain. I know that Gimp & Inkscape support it but I never used it. `LANG` env var is sufficient. And like any other low priority feature it should be unintrusive.
1. We already have such databases - gettext mo files. Gettext supports simple translations, context based translation, translation for plural form. No need to reimplement them. You rarely need to show additional names, so direct call to *gettext is sufficient for this case.
1. Because in this case you'll have multiple copies of the same string. `addDomain(d){ if (domains not include(d)) { domains.push_back(d); return domain.size() - 1;}}`
1. If you want more compact and unified code you can start with code duplications found by Sonar. Your virtual classes will not help because besides the most trivial cases like `getRadius()` all objects will have other "common" methods reimplemented (== slower invocation). So current approach with `Selection` is absolutely fine, with it we have `if (sel.body() == nullptr) ... else if (sel.star() == nullptr) ...` with virtual classes we'll have `if (dynamic_cast<Body>(o) != nullptr) ... else if (dynamic_cast(Star) != nullptr) ...` in so many places that I don't understand what profit we might have from the change.

I'm not "overreacting". There are lot of places where Celestia code is terrible (just to mention that methods containing hundreds of LoC), but at least it's quite easy to understand it, all you need is `grep` + `less`. And compare it with OpenSpace. It's great in features but it has too high entry level for anybody who came outside of that world where overengineering is in favor. I wanted to "steal" their star field drawing code, but I just was unable to understand it.

**Comment by pirogronian** [comment]
1. Ok. I just needed it clearly stated :)
2. Ok let it be. At least for now.
3. Ok, I just wanted to have stated clearly, that programmer need to know domain id when setting name. It is known from `addDomain` method, but could be problematic when name setting is done in defferent scope than domain adding. I that case I would bind domain id with name string, but it is what you dont want, right?
4. Actually I'm not criticize `selection`. Even if I would replace it, then certainly not in that way.

To me,my  refactoring propositions are because many parts of code are unclear. Many loc, I agree. Sometimes I see even templates and virtials that seems to be "overabstract", so it's not only one direction I want to go.

**Comment by pirogronian** [comment]
As input translation, at least for categories, is already implemented, there seems to be safe to close this issue.
