### ISSUE TITLE
Error loading 3DS model (Uranographia)

### ISSUE THREAD

**Issue by Lepestronik** [CelestiaProject/Celestia#1613]
**Describe the bug**
The "Uranographia" addon does not work due to a 3DS model loading error.

**To Reproduce**
1. Unpack [Uranographia.zip](https://github.com/CelestiaProject/Celestia/files/10868867/Uranographia.zip) to _extras_ directory.
2. Run Celestia.
3. Press Shift+` and see mentioned errors in the log (there will be no pictures in the sky).

**Expected behavior**
![image](https://user-images.githubusercontent.com/89343875/222368496-e510b3dd-059f-4db9-b48e-593ca25d3415.png)
Screenshot was made with 1.6.2.2

**Screenshots**
![image](https://user-images.githubusercontent.com/89343875/222364187-993d5c47-0b26-4564-b4cc-04495ec56287.png)
Text:
```
Loading model: extras/Uranographia/models/uranographia.3ds
Chunk size 0 too small to include header
Error loading model "extras/Uranographia/models/uranographia.3ds"
```

**Desktop:**
 - OS: Linux.
 - Frontend: Qt, GTK.
 - Version: 1.7.0.

**Comment by Lepestronik** [comment]
"3DS to CMOD converter for Windows" creates a working CMOD model. Can this be considered to eliminate **_the root_** of the problem?

![image](https://user-images.githubusercontent.com/89343875/222502342-3a30d343-0b31-4375-9b42-512acdd53433.png)

**Comment by 375gnu** [comment]
our current 3dstocmod fails with the same error

**Comment by 375gnu** [comment]
i suppose this is a really buggy model. it has one chunk with size 0.

**Comment by ajtribick** [comment]
File is malformed. The top-level chunk specifies a length of 67437 bytes, while the total length of the file is 67400 bytes.
