### ISSUE TITLE
Add the more accurate D58 blackbody colors for star glow color.

### ISSUE THREAD

**Issue by JiliTheSpaceboy** [CelestiaProject/Celestia#1637]
Currently we have two blackbody colors: Classic and D65. The D65 blackbody color was implemented as a more realistic color scheme. However, [D65 is designed for use on Earth's surface](https://en.wikipedia.org/wiki/Illuminant_D65), and [is unsuited for depicting star colors in space](http://vendian.org/mncharity/dir3/starcolor/), as shown by the color of the Sun being pale orange although it is white in real life (see Askaniy's TCT, which defines white as flat spectrum).

I propose we add D58 as a blackbody color scheme, **and make it the default star color**. This can either use [the color table provided by 7Sph here](https://github.com/CelestiaProject/Celestia/issues/892#issuecomment-1006076147), or alternatively [implement D57 from here](https://github.com/CelestiaProject/Celestia/pull/1585#issue-1590643939).

**Comment by ajtribick** [comment]
Ok to close this with the new star color settings from #1819 ?

**Comment by JiliTheSpaceboy** [comment]
> Ok to close this with the new star color settings from #1819 ?

I'm not sure if the D58 equivalent (Solar Whitepoint) has been set to default (or is planned to) but I guess that's a minor issue, so I'm cool with closing this.
