### ISSUE TITLE
Spoiled text information

### ISSUE THREAD

**Issue by Lepestronik** [CelestiaProject/Celestia#1647]
**Describe the bug**
https://github.com/CelestiaProject/Celestia/commit/67cbcc3a5cfbb63d572d5254540f3040b82014af spoils the text information displayed in the screen corners with some symbols.

**Screenshots**
![image](https://user-images.githubusercontent.com/89343875/226101296-94f19231-821d-4c8d-8e76-335f87f6d0ef.png)
![image](https://user-images.githubusercontent.com/89343875/226101310-9a1c3ba3-cd5a-4561-844d-64b74a4fdd38.png)

**Desktop:**
 - OS: Linux.
 - Frontend: Qt.
 - Version: 1.7.0.

**Comment by levinli303** [comment]
the character to blame is '\0'
