### ISSUE TITLE
Assertion failure in rendering sun

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#1655]
https://github.com/CelestiaProject/Celestia/blob/979b76b9f2da9fc2fdab4aef3036e0edb20cc686/src/celengine/lodspheremesh.cpp#L451

<img width="623" alt="Screenshot 2023-03-24 at 11 43 59" src="https://user-images.githubusercontent.com/17924287/227419271-93629b3a-5ac4-43b3-83cf-c52ceff57eeb.png">

**Comment by 375gnu** [comment]
```
    int expectedIndices = nRings * (nSlices + 2) * 2 - std::max(nRings, 2);
```
it should be just `2` instead of `std::max(nRings, 2)`
