### ISSUE TITLE
openSUSE Tumbleweed gains optional x86-64-v3 optimization

### ISSUE THREAD

**Issue by munix9** [CelestiaProject/Celestia#1661]
I have configured the optional `x86-64-v3` optimization for openSUSE Tumbleweed on OBS for testing.

It only optimizes `libcelestia` and offers it once as usual as `libcelestia1_7-1.7.0~git*.x86_64.rpm` and once (now new) as `libcelestia1_7-x86-64-v3-1.7.0~git*.x86_64.rpm`.

I'm not sure if this will significantly increase performance on devices with a suitable CPU (if at all), but I think it's worth a try.

If you want to test it, you can find the packages here:
https://build.opensuse.org/package/show/home:munix9:test/celestia
https://build.opensuse.org/package/binaries/home:munix9:test/celestia/openSUSE_Tumbleweed
https://download.opensuse.org/repositories/home:/munix9:/test/openSUSE_Tumbleweed/x86_64/

If it makes sense, the changes will move to the well-known (official) unstable-repo soon.

Additional Info:
https://news.opensuse.org/2023/03/02/tw-gains-optional-optimizations/
https://www.phoronix.com/news/openSUSE-TW-x86-64-v3-RPM
https://www.theregister.com/2023/03/09/opensuse_finds_x86_64_solution/
https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels

**Comment by 375gnu** [comment]
In my tests `-O3` gave higher boost then `-march` so I don't expect noticeable performance change.

**Comment by munix9** [comment]
Sure, I have also found the link below and read other sources - but testing does not hurt and sometimes you are positively surprised.

Maybe the chain of optimizations of other system-libs will result in advantages that do not show up so strongly when optimizing a single application - let's see, I have to test it more extensively.

https://sunnyflunk.github.io/2023/01/15/x86-64-v3-Mixed-Bag-of-Performance.html
