### ISSUE TITLE
Our site has been moved to celestiaproject.space

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#1672]
Years ago Alexell registered celestia.space domain at russian registrar reg.ru. Due to russian invasion to the Ukraine bank transfers to russia are blocked, so I'm unable to renew the domain. I also unable to transfer to any other registrar because only a few days ago I found that despite the fact that the domain is transferred to my account it still owned by Alexell. I was able to update ownership but reg.ru disallows transfers to other registrar during 60 days after ownership change.

So my plan is to try buying it tomorrow at another registrar.

You can add the following line to the /etc/hosts file (on windows it's located somewhere inside c:\windows\...) to keep site working from your machine:
```
5.39.216.162 celestia.space
```

Please follow the github issue for more information: https://github.com/CelestiaProject/Celestia/issues/1672

**Comment by 375gnu** [comment]
reg.ru keeps domain till 24.05.2023. so i can purchase it only on 25th of may

**Comment by vico93** [comment]
Just FYI, on Windows the full path of hosts file is `C:\Windows\System32\drivers\etc\hosts`

**Comment by inetuka** [comment]
If any help is needed do not hesitate to contact me.
Best regards from Hamburg

**Comment by TheLostProbe** [comment]
in case it helps anyone, here is a full tutorial on how to enable the hosts file workaround on windows

1. open file explorer and click on the "view" tab at the top of the window, and enable "file name extensions" (not necessary if you already have this option enabled)
2. navigate to the following directory: `C:\Windows\System32\drivers\etc`
3. copy the file named "hosts" to your desktop and open it in notepad
4. add the following line to the very bottom of the page: `5.39.216.162 celestia.space`
5. save the edits and exit notepad
6. the file should now be called "hosts.txt", rename the file to just "hosts" without the ".txt"extension and click the "yes" button on the resulting pop-up
7. drag the new version of the "hosts" file from your desktop back into the "etc" folder, and replace the old version of the "hosts" file
8. open a web browser and see if you can access the website: https://celestia.space

**Comment by Joachim-Otahal** [comment]
Thank you! I just hit the right time to get that program :D

**Comment by Texturer99** [comment]
Would you be so kind to post the new Celestia 1.6.3 exe file on http://celestiamotherlode.net/ too? That is the only one remaining (up and running) open Celestia3D site as I know.

**Comment by SevenSpheres** [comment]
The Motherlode is no longer maintained and no longer accepts new uploads.

**Comment by ajtribick** [comment]
Hi, any updates on this?

**Comment by 375gnu** [comment]
I expect in about a week we can restore the domain name.

**Comment by 375gnu** [comment]
Bad news. The domain was acquired by cyber squatters. So I'm going to register a new domain.

**Comment by 375gnu** [comment]
The new domain is celestiaproject.space

**Comment by ajtribick** [comment]
Might be worth contacting the registrar listed on the ICANN lookup, not sure how likely it is that they'll do anything though.

**Comment by 375gnu** [comment]
I suspect that domain squatters and their registrar are the same people. I tried to create an account on https://costrar.com/ but without any success.

**Comment by inetuka** [comment]
The registrar of .space TLD is Radix, a subsidiary of Directi Group, a UAE located company. https://radix.website/
If you file a dispute directly to them, maybe they agree on Costrar failing to adhere to the standards by allowing domain grabbing/hijacking.

Best regards, Udo

**Comment by mattiaverga** [comment]
BTW, the README and README.md files in the main project dir still link to the old domain
