### ISSUE TITLE
Bayer designations for globular clusters

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#169]
Star names allow Bayer designations: e.g. "ALF Cen" becomes displayed as "α Cen". However, we should also have this feature for globular clusters, specifically for two globular clusters (xi Tucanae and omega Centauri) with Bayer designations.

**Comment by pirogronian** [comment]
Fixed in #213 .

**Comment by 375gnu** [comment]
Not fixed yet
