### ISSUE TITLE
Celestia 1.6.3's compilation instructions are insufficient

### ISSUE THREAD

**Issue by TCH68k** [CelestiaProject/Celestia#1715]
They say, start with `./configure <options>`; well, there is no `configure` in the directory. There is a `configure.ac`, but `autoconf` cannot process it, complaining about missing macros. Instead it needs to be processed with `autoreconf --install`. Then the rest of the instructions can be executed. Please update the docs.

**Comment by Hellseher** [comment]
It works for me https://github.com/CelestiaProject/Celestia/blob/1.6.3/INSTALL#LL13C1-L17C14
```
	libtoolize
	autoreconf -f
	./configure --with-INTERFACE                   [*]
	make
	make install
```

But I've got issue to link to Lua in Guix right now.

**Comment by 375gnu** [comment]
@TCH68k `autoreconf` is mentioned in INSTALL file as @Hellseher posted.
