### ISSUE TITLE
Celestial objects unification

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#173]
To me, every (or nearly) celestial object should be able to have:
1. Trajectory (maybe except location)
2. Parent
3. Children
4. Position in catalog
I also suggest to create unified catalog class, which would have:
1. Name (of catalog), maybe description
2. Catalog numbers
3. Catalog names(?)
Because I don't know much about catalogs, let me know if I misunderstanded something.

**Comment by 375gnu** [comment]
1-3 They do.
4 Catalog is useless for planets & moons as they belong to their star. Dunno if it required for asteroids and comets.
5-7 Currently Celestia has only one catalog (HIP), other catalogs are either crosslinked to it (e.g. SAO) or map their numbers to HIP numbers (Tycho). Not all catalogs use simple linear numbering (e.g. Tycho has a-b-c numbering). So if you want to fix the problem, you should have a very good understanding of it, simply adding a virtual parent for all C++ classes will not solve it magically.

**Comment by 375gnu** [comment]
Because they are DSO. What parent can a galaxy have?

**Comment by pirogronian** [comment]
Other galaxy. Or center of mass in a group. For example, Centaur Galaxy near Milky Way or both Magellan Clouds. Moreover, DSOs include also globular clusters and nebulae, that certainly can have parent with galaxy center and trajectory around it.

**Comment by 375gnu** [comment]
So, summarizing, you propose to add some dead code, because now we don't have any code to support clusters/nebulae/etc trajectories/universe expansion and so on.

**Comment by pirogronian** [comment]
As overall code size will be reduced, objections about dead code sounds a bit abstract...

**Comment by pirogronian** [comment]
I think so. Now we have 3  base classess for objects, every with own databade, data parser and name handling. It causes existence of three different (although very similar) browse widgets. I propose one universal clasd for (nearly) evetything , with all common code. It can also include code for all special cases or let it for subclassing. If user want galaxy encircling around immovable planet - let it be. I just dont want waste my effort just to prevent user radiculus ideas...

**Comment by 375gnu** [comment]
Just do `fgrep -R StarDetails`.

Star & DSO browsers can be merged, but merging Solar system browser  doesn't worth efforts.

**Comment by 375gnu** [comment]
What common data? Radius?

**Comment by pirogronian** [comment]
Radius also. But first of all: parent, children, trajectory, visibility, category (already is) and (maybe) names list/catalog entries.

**Comment by 375gnu** [comment]
Don't you see that this means that your proposal is useless?

**Comment by pirogronian** [comment]
No, I don't see. Why?

**Comment by 375gnu** [comment]
1. because the code is already written
1. because there is no nontrivial methods common (except trajectory)
1. and there is no codepaths where star or planet or dso can be used. stars has own path, planets have their own, and so dsos.

First you should implement a new feature which can be implemented better if all object has common ancestor and only then implement your proposal. Not just because you was told that common virtual classes are "the only  right thing"

**Comment by pirogronian** [comment]
1. So I want to eliminate code, rathwr, than write new.
2. Still worth an effort.
3. What is "codepath"? Do you mean rendering method?

> you should implement a new feature which can be implemented better if all object has common ancestor

That's how I planned to try it.
Where I argued that common virtual class is the only right thing?

**Comment by 375gnu** [comment]
"code path" = "code", but related to some particular feature.

DSOs have a lot of shared, they are not implemented in this way just because in textbooks it's said so.
