### ISSUE TITLE
[gtk] Locale initialization looks incorrect

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1746]
The code to initialize the locale in the GTK frontend sets `LC_NUMERIC` *before* `LC_ALL`, unlike all other front-ends which do it the other way round. As far as I can see this will result in the setting of `LC_ALL` overriding the `LC_NUMERIC` setting.

I am not sure if this actually causes any issues, but presumably this should either be reversed or the call setting `LC_NUMERIC` should be removed.

https://github.com/CelestiaProject/Celestia/blob/00cb5913b66d617cc6bbcb37bb0440f58254573b/src/celestia/gtk/main.cpp#L315-L317

**Comment by 375gnu** [comment]
Correct, this a bug. According to https://www.gnu.org/software/libc/manual/html_node/Locale-Categories.html

> LC_ALL
> 
>     This is not a category; it is only a macro that you can use with setlocale to set a single locale for all purposes. Setting this environment variable **overwrites** all selections by the other LC_* variables or LANG.
>
