### ISSUE TITLE
SonarScanner failing?

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1761]
Run for #1760 fails with the following error:

```
ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
```

**Comment by 375gnu** [comment]
That's because now sonar token is stored as a github secret which is available only for actions run from the main fork, as you run that pr from your own fork it's not available.

**Comment by ajtribick** [comment]
I think it's worth checking out the workarounds as described in https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/30
