### ISSUE TITLE
Site looks taken over - possible cyber squatting 

### ISSUE THREAD

**Issue by mbiesiad** [CelestiaProject/Celestia#1777]
**Describe the bug**
Project here on the GitHub description (About) and provided Link is "Real-time 3D visualization of space.
**celestia.space**"

The site is wrong, please change to proper one.
At this moment from celestia.space there is a redirection to http://ww38.celestia.space/ (yup, also without HTTPS Forcing there)

**To Reproduce**
1. Go to https://github.com/CelestiaProject/Celestia
2. Take a look at the right side - provided project' link (improper; above)

**Expected behavior**
Update provided site to proper one.

**Screenshots**
![image](https://github.com/CelestiaProject/Celestia/assets/18367606/fad82d25-a56a-4442-8090-934e3a0c8908)

**Desktop (please complete the following information):**
NA

**Additional context**
Referring to the https://github.com/CelestiaProject/Celestia/issues/1672 #1672 message from 3 weeks ago is "Bad news. The domain was acquired by cyber squatters. So I'm going to register a new domain."
That is dangerous, please update About section with proper website link.

Best wishes,

**Comment by SevenSpheres** [comment]
Link updated

**Comment by mbiesiad** [comment]
@SevenSpheres Thanks a lot! 🎉
