### ISSUE TITLE
Compiler messages

### ISSUE THREAD

**Issue by wm-0007** [CelestiaProject/Celestia#1780]
**Describe the bug**
Compiled celestia-master and had lots of compiler messages. How do I resolve the issues that result in the messages?

**To Reproduce**
Steps for compiling Celestia-master on Debian 11

1)  get source code - clone github code repository
    cd ~/Development
    rm -r ./Celestia
    git clone https://github.com/CelestiaProject/Celestia
    cd Celestia
    git submodule update --init

2) get required libraries 
    sudo apt-get install libepoxy-dev libjpeg-dev libpng-dev libgl1-mesa-dev libeigen3-dev libfmt-dev libfreetype6-dev libglu1-mesa-dev qtbase5-dev qtbase5-dev-tools libqt5opengl5-dev libgtk2.0-dev libavif-dev

3)  compile Celestia source files
    cd ~/Development/Celestia
    mkdir build
    cd build
    cmake .. -DCMAKE_INSTALL_PREFIX=/home/william/Celestia-Test
    make -j

4) abort compilation due to messages

**cmake results**
CMake Deprecation Warning at CMakeLists.txt:28 (cmake_policy):
  The OLD behavior for policy CMP0071 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Found Intl: /usr/include  
-- NAIF SPICE is disabled. Not looking for cspice library.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found Libepoxy: /usr/include  
-- Found Eigen3 3.3.9
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "62") 
-- Could NOT find LuaJIT (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.1.5") 
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.10.4") 
-- meshoptimizer library is missing
-- Looking for wordexp
-- Looking for wordexp - found
-- Looking for include file byteswap.h
-- Looking for include file byteswap.h - found
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - found
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Success
CMake Warning at CMakeLists.txt:438 (message):
  C++ charconv lacks floating point support!

  Will use own implementation.

-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Either not Unix or Gtk frontend is disabled.
-- Qt6 frontend is disabled.
-- SDL frontend is disabled.
-- Either not Windows or Windows frontend is disabled.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/william/Development/Celestia/build

** make -j sample messages **
<<<<<< snip >>>>>>
[ 48%] Building CXX object src/celrender/CMakeFiles/celrender.dir/gl/buffer.cpp.o
[ 48%] Built target translations_1
In file included from /home/william/Development/Celestia/src/celutil/timer.cpp:11:
/home/william/Development/Celestia/src/celutil/timer.h: In constructor ‘Timer::Timer()’:
/home/william/Development/Celestia/src/celutil/timer.h:19:5: warning: ‘Timer::start’ should be initialized in the member initialization list [-Weffc++]
   19 |     Timer() { reset(); };
      |     ^~~~~
[ 48%] Building CXX object src/celengine/CMakeFiles/celengine.dir/axisarrow.cpp.o

<<<<<< snip >>>>>>
[ 71%] Building CXX object src/celengine/CMakeFiles/celengine.dir/render.cpp.o
In file included from /home/william/Development/Celestia/src/celengine/glsupport.h:4,
                 from /home/william/Development/Celestia/src/celrender/gl/buffer.h:14,
                 from /home/william/Development/Celestia/src/celrender/gl/vertexobject.cpp:12:
/home/william/Development/Celestia/src/celutil/array_view.h: In member function ‘constexpr celestia::util::array_view<T>& celestia::util::array_view<void>::operator=(const celestia::util::array_view<T>&)’:
/home/william/Development/Celestia/src/celutil/array_view.h:261:16: warning: ‘operator=’ should return a reference to ‘*this’ [-Weffc++]
  261 |         return *this;
      |                ^~~~~
/home/william/Development/Celestia/src/celutil/array_view.h: In member function ‘constexpr celestia::util::array_view<T>& celestia::util::array_view<void>::operator=(celestia::util::array_view<T>&&)’:
/home/william/Development/Celestia/src/celutil/array_view.h:269:16: warning: ‘operator=’ should return a reference to ‘*this’ [-Weffc++]
  269 |         return *this;
      |                ^~~~~
/home/william/Development/Celestia/src/celutil/array_view.h: In member function ‘constexpr celestia::util::array_view<T>& celestia::util::array_view<const void>::operator=(const celestia::util::array_view<T>&)’:
/home/william/Development/Celestia/src/celutil/array_view.h:383:16: warning: ‘operator=’ should return a reference to ‘*this’ [-Weffc++]
  383 |         return *this;
      |                ^~~~~
/home/william/Development/Celestia/src/celutil/array_view.h: In member function ‘constexpr celestia::util::array_view<T>& celestia::util::array_view<const void>::operator=(celestia::util::array_view<T>&&)’:
/home/william/Development/Celestia/src/celutil/array_view.h:391:16: warning: ‘operator=’ should return a reference to ‘*this’ [-Weffc++]
  391 |         return *this;
      |                ^~~~~
[ 71%] Building CXX object src/celengine/CMakeFiles/celengine.dir/renderglsl.cpp.o

<<<<<< snip >>>>>>

There are more...

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Frontend: Gnome 3.38.5
 - Version: Wayland

**Comment by ajtribick** [comment]
Some of the messages are actual issues, some of them are less of a priority. The ones about warning: `‘operator=’ should return a reference to ‘*this’` should be fixed now.
