### ISSUE TITLE
celx_internal.h:209: error: 'lua_isinteger' was not declared in this scope

### ISSUE THREAD

**Issue by qsc555** [CelestiaProject/Celestia#180]
Qt 5.12.0 use by mingw730_64 , this error caused by lua51.lib does not have the ‘lua_isinteger’ method，can somebody make a lua53.lib ? I'm still learning about this project.

**Comment by pirogronian** [comment]
It's my fault. I didn't realized `lua_isinteger` is avaliable since Lua 5.3. Please wai a moment, I'll send fix.

**Comment by 375gnu** [comment]
Fixed in #181
