### ISSUE TITLE
build error on Debian_11 and Ubuntu_20.04

### ISSUE THREAD

**Issue by munix9** [CelestiaProject/Celestia#1822]
build error on Debian_11 and Ubuntu_20.04, probably caused by https://github.com/CelestiaProject/Celestia/commit/58d956ebac68f14a1b22a295d3f2d43144636413 :
https://build.opensuse.org/package/live_build_log/home:munix9:unstable/celestia/Debian_11/x86_64
https://build.opensuse.org/package/live_build_log/home:munix9:unstable/celestia/Ubuntu_20.04/x86_64

Last successful build was https://github.com/CelestiaProject/Celestia/commit/b735a84bd178aaa6d2a29df5484f2b5f571fe69f :
https://build.opensuse.org/package/binaries/home:munix9:unstable/celestia/Debian_11
https://build.opensuse.org/package/binaries/home:munix9:unstable/celestia/Ubuntu_20.04

**Comment by ajtribick** [comment]
Odd, the Ubuntu 20.04 build ran fine on the CI. I see that the check for pthread failed, do you have libpthread-stubs0-dev installed?

**Comment by munix9** [comment]
according to the logs, yes:

https://build.opensuse.org/public/build/home:munix9:unstable/Debian_11/x86_64/celestia/_log
[   27s] [20/619] installing libpthread-stubs0-dev-0.4-1

https://build.opensuse.org/public/build/home:munix9:unstable/Ubuntu_20.04/x86_64/celestia/_log
[   17s] [21/618] installing libpthread-stubs0-dev-0.4-1

**Comment by munix9** [comment]
found this:
```
[  153s] CMake Error at cmake/FixIntl.cmake:11 (set_target_properties):
[  153s]   INTERFACE_LIBRARY targets may only have whitelisted properties.  The
[  153s]   property "IMPORTED_LINK_INTERFACE_LANGUAGES" is not allowed.
[  153s] Call Stack (most recent call first):
[  153s]   CMakeLists.txt:188 (MakeIntlTarget)
```
