### ISSUE TITLE
Incorrect light years ↔ parsecs conversion

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1825]
The conversion between light years and parsecs is defined here:

https://github.com/CelestiaProject/Celestia/blob/9b8dcfc696dcf8e046d8075c94dde635f14267f2/src/celengine/astro.h#L23-L24

This value should be 3.26156 (to 5 decimal places). This should be fixed, but not sure if that would have implications for existing add-ons.

**Comment by JiliTheSpaceboy** [comment]
Given that this is a matter of accuracy of the simulation, I think the value of parsec should be changed to the correct value regardless of whether it breaks existing addons or not.
