### ISSUE TITLE
Proposal: drop Windows Qt5 builds from CI

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1834]
I propose we drop the Qt5 builds on Windows CI in favour of building just the Qt6 and Windows front ends. I am not proposing that we prevent Windows Qt5 builds from the source code, just that we don't run it in CI.

* Building both Qt5 and Qt6 leads to longer build times, particularly on Windows where the CI will compile from source when the build system or vcpkg get updated.
* Qt5 lacks the CMake utilities that trigger winqtdeploy on the install target, making it less convenient to set up installers

On Linux it makes sense to keep Qt5 around since the major desktop environments are still on Qt5.
I don't know enough about what things look like on Mac to say whether or not it makes sense to have both Qt5 and Qt6 there.

**Comment by 375gnu** [comment]
why not? let's go.
