### ISSUE TITLE
Use gperf to generate lookup tables

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1842]
It may be worth using [GNU gperf](https://www.gnu.org/software/gperf/) to generate the lookup tables used in places like the legacy script command parser, or the custom orbits/rotations. I've done some local experimentation with the table in cmdparser.cpp and it looks like this shouldn't be too difficult to integrate into the code.

Advantages: avoids need to allocate heap memory for the lookups and spend time at runtime building the data structures.
Disadvantages: more complexity in the build process (autogenerated code), requires another build dependency.

The gperf tool is available via vcpkg so Windows isn't a problem. Not sure about Mac.

**Comment by 375gnu** [comment]
That's sound interesting. Homebrew has gperf as does macports.
