### ISSUE TITLE
Cmodview fails on load with segmentation fault

### ISSUE THREAD

**Issue by dave-kaye** [CelestiaProject/Celestia#1864]
Cmodview is failing upon load and crashing. The symptoms of the failure are reproducible. First operating system is openSUSE Leap 15.2 Linux and Qt-5. Second operating system is Windows 10 with Qt-6.  Both performed identically. 

To illustrate, I am using models found in the Celestia Content github repository and extras-standard directory. The models are: galileo, hubble and iss.

If cmodview is loaded and any of the above models are opened via the cmodview program menu, the models will load and cmodview runs successfully.  However, if the model is opened via the file manager with an association of the *.cmod file type to cmodview, the program may crash upon startup.

The problem started with modifications uploaded on Aug 9, 2023. The program works through Celestia git version 3945309. It begins failing with Celestia git version 8a191ed - Migrate to QOpenGLWidget.

The crash will only occur if the model has textures associated with it. If there are no textures, the model will open and cmodview will operate successfully.  Examples below are based upon an older version of cmodview prior to 8/9/23 called "cmodview" and a newer version of cmodview called "cmodview-qt5". To illustrate the issues, the cmodview program was started via the command line on models moved to the home directory to show the error messages. It also will fail using the file manager association described above, but no error messages are available.

MODEL WITH NO TEXTURES

```
localhost:/usr/bin/celestia-tools> ./cmodview /home/dk/hubble/models/hubble.cmod

localhost:/usr/bin/celestia-tools> ./cmodview-qt5 /home/dk/hubble/models/hubble.cmod
```

* Both programs ran successfully and no errors were recorded.

MODEL WITH TEXTURES

```
localhost:/usr/bin/celestia-tools> ./cmodview /home/dk/galileo/models/galileo.cmod
Load galileo_tex_02.*, texId = 0
Load galileo_tex_01.*, texId = 0
Load foil_gold_ramp.*, texId = 0
Load foil_n.png, texId = 1

localhost:/usr/bin/celestia-tools> ./cmodview-qt5 /home/dk/galileo/models/galileo.cmod
Failed to load "galileo_tex_02.*"
Failed to load "galileo_tex_01.*"
Failed to load "foil_gold_ramp.*"
Segmentation fault (core dumped)

```
* Older version loaded and ran successfully. Newer version crashed upon startup.

MODEL WITH TEXTURES

```
localhost:/usr/bin/celestia-tools> ./cmodview /home/dk/iss/models/iss.cmod    
Load issbso.jpg, texId = 1
Load issku2.jpg, texId = 2
Load isscov2.jpg, texId = 3
Load nasda.jpg, texId = 4
Load issku.jpg, texId = 5
Load issdot.jpg, texId = 6
Load iss_un.jpg, texId = 7
Load issku.dds, texId = 0
Load issbs.jpg, texId = 8
Load graple.jpg, texId = 9
Load issb2.jpg, texId = 10
Load issleo.jpg, texId = 11
Load isspanel.jpg, texId = 12
Load d_ring.jpg, texId = 13
Load issrad.jpg, texId = 14
Load issmod.jpg, texId = 15
Load iss_dcs.jpg, texId = 16
Load issins.jpg, texId = 17
Load issdish.dds, texId = 0
Load issb4.jpg, texId = 18
Load issdish.jpg, texId = 19
Load issusaf.jpg, texId = 20
Load issmb.jpg, texId = 21
Load d_ring.dds, texId = 0
Load isscup.jpg, texId = 22
Load issb3.jpg, texId = 23
Load issp2.dds, texId = 0
Load issbso2.jpg, texId = 24
Load issb3.dds, texId = 0
Load isszmod.jpg, texId = 25
Load issusa.jpg, texId = 26
Load issp2.jpg, texId = 27
Load issb.jpg, texId = 28
Load questcov.jpg, texId = 29
Load isshand.jpg, texId = 30
Load metalcon.jpg, texId = 31
Load issred.jpg, texId = 32
Load issku1.jpg, texId = 33
Load isscover.dds, texId = 0
Load issesa.jpg, texId = 34
Load iss_dc.jpg, texId = 35
Load issItalian.jpg, texId = 36
Load isssolar.jpg, texId = 37
Load isscover.jpg, texId = 38

localhost:/usr/bin/celestia-tools> ./cmodview-qt5 /home/dk/iss/models/iss.cmod        
Segmentation fault (core dumped)

```
* Older version loaded and ran successfully. Newer version crashed attempting to startup.

The problem appears to be consistant with any model I select. I utilize the cmodview program via the file manager association to look at segments of spacecraft when assembling a spacecraft model from components. Therefore, this error is happening during Celestia model deployment. It also is utilized to monitor/modify capitalization of model parts since Linux is case sensitive.

**Comment by ajtribick** [comment]
It works if you open cmodview-qt5 and load the model file from the menu. Will take a look at why supplying the file on the command line fails.
