### ISSUE TITLE
Lobus location type support

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#1880]
We need to be sure that src/celengine/location.cpp contains all the [IAU location types](https://planetarynames.wr.usgs.gov/DescriptorTerms). Maybe, reorder them according to the source?
At least support of new feature type "Lobus"  is needed.

_upd_: ajtribick on Discord said that
> looks like we ran out of space in 64-bit integers for all the location flags

**Comment by ajtribick** [comment]
Looks like we have everything in the list apart from Lobus. We do have the location type "Lenticula" which isn't listed on the linked page, anyone know what this one is? It has been backported into the 1.6.x releases so probably not so easy to just replace this with Lobus though.

**Comment by SevenSpheres** [comment]
This is documented at https://en.wikibooks.org/wiki/Celestia/SSC_File#Type_%22string%22

> "LE" = Lenticula = small dark spots on Europa

Though the source cites the same USGS page, which no longer lists Lenticula, so maybe it should be replaced with Lobus.

**Comment by ajtribick** [comment]
Thanks - according to the Wayback Machine it looks like it was removed sometime between March and May 2019. Archived versions of the Europa nomenclature zip don't seem to contain any entries for this, so maybe it never got used in actual feature names?

**Comment by Askaniy** [comment]
Having such an extra location type sounds like great luck
