### ISSUE TITLE
Untranslatable lightning preferences

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#1887]
![image](https://github.com/CelestiaProject/Celestia/assets/44873271/fdd5a500-0ae7-465f-a834-a4f7bee38207)
![image](https://github.com/CelestiaProject/Celestia/assets/44873271/433fb2b2-4188-46ad-95bb-4992cd70fec1)

**Comment by Askaniy** [comment]
New stellar whitepoints too:
![image](https://github.com/CelestiaProject/Celestia/assets/44873271/052b3b1b-90dd-43ef-80be-eccec98baaa8)

**Comment by ajtribick** [comment]
I think this is what the Makefile in the po directory is supposed to do, at least for me I needed to run it a couple of times to get it to update all the files.

**Comment by ajtribick** [comment]
Can we close this?

**Comment by Askaniy** [comment]
I hope yes. For some reason, the latest available version in munix9's repo is bed2d96, so I can't check
