### ISSUE TITLE
No menus work in fullscreen

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#191]
After migration to QOpenGLWidget no menus work in fullscreen. Windows only.

**Comment by pirogronian** [comment]
Internet rumors [reports](https://forum.qt.io/topic/76129/qopenglwidget-fullscreen-problem/6) it can be related to ANGLE backend with Qt on Windows. Here is a [Qt Wiki article](https://wiki.qt.io/Qt_5_on_Windows_ANGLE_and_OpenGL) about dealing with ANGLE.

**Comment by 375gnu** [comment]
Seems that you are correct, after exporting QT_OPENGL to desktop I was
not only able to run Celestia under wine, but menus were working as
well.

**Comment by 375gnu** [comment]
Unfortunately, nope. This issue has been reported countless times to qt's bugzilla and no proper solution yet. QOpenGLWidget also is slower and enforces double buffering by default while QGLWindow is a raw GL window. Another issue reported in https://celestia.space/forum/viewtopic.php?p=141773#p141773. So I'll revert this change.

**Comment by 375gnu** [comment]
The official w/a doesn't work. Celestia just crashed when I added it.

I hope Qt 5 will keep the old class. Also we can try https://doc.qt.io/qt-5/qopenglwindow.html instead.
