### ISSUE TITLE
RFE: show fps

### ISSUE THREAD

**Issue by mattiaverga** [CelestiaProject/Celestia#1920]
Can you add a "current FPS" information so that, when fps is set to auto, I can evaluate the hardware performance based on different settings / compiler option?
(background story is: I'd like to evaluate in Fedora the performance impact on ARM based platforms of building Celestia with OpenGL vs OpenGL ES - if I ever manage to get QT in Fedora built with OpenGL ES support)

**Comment by 375gnu** [comment]
Press ` . But we use double buffering by default, so fps will be cupped by refresh rate

**Comment by mattiaverga** [comment]
:+1: Nice, I was looking for a menu item and didn't know about the keyboard shortcut.
