### ISSUE TITLE
Binance Account 

### ISSUE THREAD

**Issue by KJ1403** [CelestiaProject/Celestia#1939]
https://www.binance.info/en/activity/referral-entry/CPA/together?ref=CPA_003UT3YQZ9![share_2023-10-16_00_11_14_158.jpeg_2023-10-16_00_11_14.jpg](https://github.com/CelestiaProject/Celestia/assets/147840786/bea47993-c3c9-4401-bd46-1796a80b8b9c)

**Comment by 375gnu** [comment]
lol, now spammers are on github
