### ISSUE TITLE
Switch the Windows front-end to Unicode APIs

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#1966]
Currently the Windows front-end is using ANSI APIs, this limits the ability to support certain languages (e.g. Georgian, recently added).

If we still want to keep the Windows front-end around, we should update it to use the wide-character APIs instead.

**Comment by 375gnu** [comment]
From https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page:

Win32 APIs often support both -A and -W variants.

-A variants recognize the ANSI code page configured on the system and support char*, while -W variants operate in UTF-16 and support WCHAR.

Until recently, Windows has emphasized "Unicode" -W variants over -A APIs. However, recent releases have used the ANSI code page and -A APIs as a means to introduce UTF-8 support to apps. If the ANSI code page is configured for UTF-8, then -A APIs typically operate in UTF-8. This model has the benefit of supporting existing code built with -A APIs without any code changes.

**Comment by 375gnu** [comment]
-W API will also cause problems with gettext.

**Comment by ajtribick** [comment]
Using the UTF-8 codepage would be the simplest option, although I believe this requires a minimum of Windows 10 version 1903.

**Comment by ajtribick** [comment]
I have some work in progress on converting the win32 UI. It turns out that gettext isn't too much of an issue since we're already having to convert from UTF8 to current codepage.
