### ISSUE TITLE
Celestia 1.6.4 for macOS

### ISSUE THREAD

**Issue by krehel** [CelestiaProject/Celestia#1967]
Hello!  Homebrew maintainer here 👋 

I see Celestia 1.6.4 was released without a macOS build.  Are there plans to make one available?

Thank you!

**Comment by 375gnu** [comment]
Hi @krehel , yes there are such plans, but our macOS maintainer is busy. Once he finds time he uploads the build.

**Comment by levinli303** [comment]
available now in https://github.com/CelestiaProject/Celestia/releases/tag/1.6.4
