### ISSUE TITLE
Gaps in ring

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#1975]
**Describe the bug**
See screenshot

**To Reproduce**
1. Download this [add-on](https://celestia.mobi/resources/item?item=C276F25A-DFE6-7F33-10D1-135C7DA4AB72)
2. Go to URL: cel://Follow/Sol:Pioneer%2011/1979-09-01T16:37:11.00780Z?x=uRn60gM&y=bjF0tQ&z=GAMGhgI&ow=0.8676776&ox=0.16016424&oy=-0.4495414&oz=0.13926755&select=Sol:Saturn&fov=28.218485&ts=100&ltd=0&p=1&rf=70571923&nrf=191&lm=2114&tsrc=0&ver=3
3. See error

**Expected behavior**
Rings have no gap

**Screenshots**
<img width="1136" alt="Screenshot 2023-11-07 at 09 32 14" src="https://github.com/CelestiaProject/Celestia/assets/17924287/e1b3141b-b6e7-4176-9c63-ff8ffd90b749">

**Comment by 375gnu** [comment]
When spacecraft display is off there are no issues.

**Comment by 375gnu** [comment]
When spacecraft ON near plain distance is 0.00448116, when they are OFF it's 70.1225.
