### ISSUE TITLE
Density calculations for non-spherical objects

### ISSUE THREAD

**Issue by JiliTheSpaceboy** [CelestiaProject/Celestia#1983]
**Is your feature request related to a problem? Please describe.**
While updating the mass values for Solar System objects, I noticed that the density value does not show up for any object defined as non-spherical: objects with flattening, or those that use SemiAxes parameter. The problem is in [body.cpp](https://github.com/CelestiaProject/Celestia/blob/986adb11bd7406e9ef3df1c796318a3e7fd6efec/src/celengine/body.cpp#L267), where for some reason any object that is not sphere is automatically assigned a density of 0. Unless the implementation of this density causes big issues elsewhere, I think this should be fixed.

The volume of an ellipsoid can be find by V = 4/3 * π * a * b * c, where a, b, and c are semi axes of the ellipsoid. The following is my (a person with no experience in C++) attempt at modifying the function. As I do not have ability to compile Celestia source code, I'd like to see if this work properly in the program, and if it can be improved (for example, simply merging spherical case into ellipsoidal case, if the latter functions fine?).

```
float Body::getDensity() const
{
    if (density > 0)
        return density;

    if (radius == 0)
        return 0;
    
    if (isEllipsoid())
        double volume = 4.0 / 3.0 * celestia::numbers::pi * semiAxes.x() * semiAxes.y() * semiAxes.z();
        return (float) mass * astro::EarthMass / 1e9 / volume;

    // assume that we have a spherical body
    // @mass unit is mass of Earth
    // @astro::EarthMass unit is kg
    // @radius unit km
    // so we divide density by 1e9 to have kg/m^3
    double volume = 4.0 / 3.0 * celestia::numbers::pi * ::pow(radius, 3);
    return (float) mass * astro::EarthMass / 1e9 / volume;
}

**Comment by ajtribick** [comment]
Yes, makes sense to add this calculation. Probably won't be able to do anything reasonable for objects with meshes for the time being, so would skip the density calculation for those.

**Comment by JiliTheSpaceboy** [comment]
> Yes, makes sense to add this calculation. Probably won't be able to do anything reasonable for objects with meshes for the time being, so would skip the density calculation for those.

Some objects with meshes, like Ceres and Mimas, are close enough to ellipsoidal shape that their calculations wouldn't be significantly off, though maybe we can instead simply add manual density input for these cases?

**Comment by 375gnu** [comment]
We have `Density` parameter.
