### ISSUE TITLE
Body::getSystem(): celestia-gtk killed by SIGSEGV

### ISSUE THREAD

**Issue by mattiaverga** [CelestiaProject/Celestia#2041]
Reported by a Fedora user and confirmed myself (fully reproducible).
Using the Eclipse finder and trying to set datetime to the reported eclipse crashes the program with GTK frontend (both double clicking on the eclipse line, as the user did, or selecting the eclipse and clicking on the interface button below).
No crash occurs with QT6 interface.

Full backtrace available in the [Fedora bug report](https://bugzilla.redhat.com/show_bug.cgi?id=2256118).

**Desktop (please complete the following information):**
 - OS: Linux Fedora
 - Frontend: GTK2
 - Version: 1.7.0 (development git commit 7ca8fe3)

**Comment by 375gnu** [comment]
This was fixed in 39ea72ed7542e15d3e870c278b872fa2c51e0a7c, please update.
