### ISSUE TITLE
Incorrect texturing for add-ons

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#2069]
**Describe the bug**
Reported by mobile user, reproducible on desktop. See screenshots

**To Reproduce**
1. Download [Earth's Auroras](https://celestia.mobi/resources/item?item=F8120336-675B-A499-4DE2-84C8529957CC) add-on
2. Go to Earth
3. See error

**Expected behavior**

<img width="1136" alt="Screenshot 2024-01-14 at 23 43 50" src="https://github.com/CelestiaProject/Celestia/assets/17924287/b3562e91-4c10-4cd7-80c7-ab81f942cbf5">

**Screenshots**

<img width="1136" alt="Screenshot 2024-01-14 at 23 42 33" src="https://github.com/CelestiaProject/Celestia/assets/17924287/a025f123-5b8e-48fb-9917-e04eb5557dbf">

**Additional context**

The bad commit is https://github.com/CelestiaProject/Celestia/commit/3d5ce7b885aa1693727a8d3177ddd6825ff4aa5e#diff-7139070d8ab8a118bba0171ff5da4b90b7fa199c9d6d94e99c72d426ae9848a1

@ajtribick

**Comment by ajtribick** [comment]
This comes down to the use of `Mesh ""` in the Auroral Oval - this is now detected as an invalid filename and thus the Mesh declaration gets ignored, leading to the object being created as a sphere that intersects the actual Earth leading to the patterns.
