### ISSUE TITLE
Many question marks in Chinese enviroment

### ISSUE THREAD

**Issue by qux-bbb** [CelestiaProject/Celestia#2079]
**Describe the bug**
Many question marks in Chinese enviroment.  

**To Reproduce**
Just Open the software.  

**Expected behavior**
Right menu display.  

**Screenshots**
![question_marks](https://github.com/CelestiaProject/Celestia/assets/18598419/7d6c8bc2-5f49-4bba-b541-f9e4ae8aba69)  

**Desktop:**
 - OS: Windows
 - Frontend: maybe native Win
 - Version: 1.6.4

**Comment by ajtribick** [comment]
Probably the default code page is set to something that doesn't support these characters. This should be fixed in 1.7.0 where we now use the wide character APIs in the Windows frontend.

**Comment by ajtribick** [comment]
Closing as fixed in 1.7.0
