### ISSUE TITLE
Pre-Windows 10 1903 versions of ICU

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#2089]
Do we need to support pre-Windows 10 1903 ICU with the `USE_WIN_ICU` feature?

I'm not sure the complexity is worth it to support outdated Windows 10 versions. The only pre-1903 version of Windows 10 ICU that is still in support is Enterprise support for 1809 - and we're not an enterprise application. In particular, our ICU code assumes `UChar` = `char16_t`, which does not appear to have been the case in the initial version released in Windows 10 1703 (split headers/split libraries).

I therefore propose that we drop support for Windows ICU apart from the combined header/combined library version. (Earlier versions of Windows can use the ICU library from vcpkg - which is what the current build process is doing)

**Comment by 375gnu** [comment]
I wouldn't waste time. If 1809 users want WinICU support, they can implement it.

**Comment by levinli303** [comment]
the UWP version only targets 1903+ so i'm fine with the change too.
