### ISSUE TITLE
CI: MacOS front-ends

### ISSUE THREAD

**Issue by ajtribick** [CelestiaProject/Celestia#2093]
Currently we are building SDL, GTK2, Qt5 and Qt6 front-ends for MacOS in the CI. Do we need all of these - in particular, can we remove GTK2 and Qt5?

**Comment by levinli303** [comment]
i'm ok with dropping GTK2 and QT5. i don't think anyone would be using GTK2 on Mac building Celestia, and QT6 is homebrew's default for installing qt now.

**Comment by 375gnu** [comment]
Let's go.
