### ISSUE TITLE
Could not read star database

### ISSUE THREAD

**Issue by Z3R0C** [CelestiaProject/Celestia#2141]
I compiled Celestia without errors and get a star database error message when starting it.

![Bildschirmfoto vom 2024-03-03 00-13-54](https://github.com/CelestiaProject/Celestia/assets/32363130/934c7972-4030-4d3f-9d6f-2464cb8af70d)
![Bildschirmfoto vom 2024-03-03 00-10-30](https://github.com/CelestiaProject/Celestia/assets/32363130/65a54ab2-811d-4c6c-a5ad-14e7b60dd472)

**Comment by ajtribick** [comment]
It looks like you don't have the content files.

Under the support directory there are script files that will download this for you - run updatecontent.sh (for Windows users seeing this issue, run UpdateContent.ps1 instead) - this will create the content directory.

You can then `cd` into the content folder, build and install that.

If you want to run from the build directory without installing, you will need to copy or create symlinks to the fonts, images, scripts and shaders folders inside content, then run, e.g.:

`./build/src/celestia/qt5/celestia-qt5 --dir content --conf celestia.cfg`

**Comment by Z3R0C** [comment]
thx :)
