### ISSUE TITLE
Allow changing colors for comet tails

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#216]
Some comet tails like 46P/Wirtanen are quite green. It might be useful to have a parameter for comets like to specify the color, like this:
`TailColor [ 0.30 1.0 0.65 ]`

**Comment by LukeCEL** [comment]
@375gnu: this is definitely a lower priority request, this doesn't necessarily have to be in 1.7.0.

**Comment by lrm25** [comment]
I'm new to coding on this specific program, and have it compiled from source and running on my machine.  I can take this issue.

**Comment by 375gnu** [comment]
Hi @lrm25 ! It will be great if you can fix this issue. Basically you need to add a new parameter for ssc files (`TailColor`) and use its value when drawing a comet.

**Comment by lrm25** [comment]
Do you want the parameters that are already there in ProcessCometTailVertex in the render.cpp code as a default, or do you want this parameter to be mandatory?

**Comment by LukeCEL** [comment]
For backwards compatibility, I’d like this parameter to be optional, and to use the parameters from render.cpp as defaults.

**Comment by lrm25** [comment]
Got it, and I have the enhancement working on my machine (Linux, QT).  Is that good enough to submit the PR, or do I need to test it on the other systems?  I don't have a Windows machine.

**Comment by lrm25** [comment]
Another question:  do you want me to add any tail colors to comets.ssc, or will you take care of that?

**Comment by LukeCEL** [comment]
> Is that good enough to submit the PR, or do I need to test it on the other systems?

Nice! You should ask @375gnu, but I think it's a good idea to submit the PR, so people can look at it.

> Another question: do you want me to add any tail colors to comets.ssc, or will you take care of that?

I don't think any comets in comets.ssc have tail colors that are too different from the default. I was mostly concerned about green comets like 46P/Wirtanen and C/2012 S1 (ISON).

**Comment by Askaniy** [comment]
> Another question: do you want me to add any tail colors to comets.ssc, or will you take care of that?

Hi @lrm25, I think this is a good idea. But I haven’t yet updated the comets.ssc according to Celestia Origin. I'll try to do it soon.
