### ISSUE TITLE
Orbits disappear after 4000 AD

### ISSUE THREAD

**Issue by levinli303** [CelestiaProject/Celestia#2210]
**Describe the bug**
Reported by Celestia for UWP user, When you change time to after 4000 AD. Orbits disappear.

**To Reproduce**
1. Turn on Orbits
2. Change time to after 4000 AD
3. Orbits disappear

**Expected behavior**
Orbits should not disappear

**Desktop**
 - OS: any

**Additional context**
I tested mobile versions, 1.5.28 is good, 1.6.0 is bad, so should be in one of these commits:
https://github.com/celestiamobile/Celestia/compare/1_5_28_rc1...1_6_0_rc1

**Comment by levinli303** [comment]
maybe #1937 @ajtribick ?

**Comment by ajtribick** [comment]
Pure EllipticalOrbits (e.g. exoplanets) seem to work, looks like something in the MixedOrbit
