### ISSUE TITLE
celestiamotherlode.net cert expired

### ISSUE THREAD

**Issue by Technetium1** [CelestiaProject/Celestia#2228]
**Describe the bug**
- SSL certificate has expired
- SSL certificate incorrect: `www.animadance.org`

**To Reproduce**
1. Attempt to download addon
2. Fail

**Expected behavior**
- Should have had a valid certificate

**Screenshots**
![image](https://github.com/user-attachments/assets/147f060b-981b-4045-9157-22b4c4d276b1)

**Desktop (please complete the following information):**
 - OS: Doesn't matter
 - Frontend: Doesn't matter
 - Version: Doesn't matter

**Additional context**
- This has resulted in the following problem for Chaotic-AUR: https://github.com/chaotic-aur/packages/issues/1913

**Comment by SevenSpheres** [comment]
The Motherlode stopped being maintained years ago. No one here has any control over it.
