### ISSUE TITLE
Keyboard Location Entry - Multiple Items

### ISSUE THREAD

**Issue by dave-kaye** [CelestiaProject/Celestia#2231]
This issue appears to be in the common Celestia code, thus affecting Qt, GTK, SDL and Windows interfaces.

When on the main Celestia viewing screen, pressing ENTER opens a line at the bottom of the screen allowing the keyboard entry of a celestial object and displaying a listing of objects matching the partial keyboard entry. The user can scroll through the listing, selecting one and allowing focus of the display to move to that selected object.

If there are two or more objects with the same name, the listing correctly displays the number of like-named objects in the list.  However, the link for all the listings is only to the first object.

This can be demonstrated by Juno - an asteroid in the main databases; and Juno - the spacecraft orbiting Jupiter (available at Celestia.mobi). The keyboard entry listing displays two entries labeled Juno. However, selecting either entry will only go to the asteroid Juno.  It is not possible to get to the spacecraft Juno from this listing.

While this can be overcome by using a different object browsing window (Solar System Browser) on some of the interfaces, no such method exists for the SDL interface.  It can also be overcome by the user editing one of the *.ssc files to change the name of the object.  

With the wide variety of addon authors and download locations, it is not unexpected to find duplication in object names.  Users editing *.ssc files is not a good, long-term solution.

**Comment by 375gnu** [comment]
This is a well known issue, but it has a workaround. So, when you need asteroid Juno, you type Sun/Juno, and when you need the spacecraft, then you type Jupiter/Juno.
