### ISSUE TITLE
add: List of nearest galaxies

### ISSUE THREAD

**Issue by jujubeja** [CelestiaProject/Celestia#2241]
* List of nearest galaxies https://en.wikipedia.org/wiki/List_of_nearest_galaxies

off-topic
https://exoplanetarchive.ipac.caltech.edu/ NASA confirmed planets
https://en.wikipedia.org/wiki/Observable_universe

youtube
[Size Comparison of the Universe](https://www.youtube.com/watch?v=134nAVodmp8)
[ABSOLUTE Size Comparison 2023 (FULL) 4K 60FPS 3D](https://www.youtube.com/watch?v=WocfYpjgb8M&t=5576s)

**Comment by SevenSpheres** [comment]
This is about content, and there's an [issue](https://github.com/CelestiaProject/CelestiaContent/issues/65) in the content repository about updating the galaxy catalog. Closing as redundant to that.
