### ISSUE TITLE
Can't launch from terminal  : "Celestia: command not found " 

### ISSUE THREAD

**Issue by vic131** [CelestiaProject/Celestia#228]
Ubuntu 18.04
Zip File Downloaded ( not cloned) from git source.
i did :
```
mkdir build
cd  build
cmake .. -DGIT_COMMIT=1234567  # instructed froom https://github.com/CelestiaProject/Celestia/issues/219
make
sudo make install
```
installed at : 
```
/usr/local/share/celestia$ ls
celestia.cfg  controls.txt  data  demo.cel  extras  extras-standard  fonts  guide.cel  images  locale  models  scripts  splash  start.cel  textures
```
But the commands "celestia" or "Celestia" or "celestia-gnome" isnt  valid command to launch it from terminal.
Do ./ in the instaled files dont seems to work either.
And ubuntu's search dont find any app to launch.
So i can't launch celestia ... 

What i did wrong ?

**Comment by 375gnu** [comment]
Use celestia-qt instead.

**Comment by vic131** [comment]
Thanks
