### ISSUE TITLE
1.7.0: Backspace doesn't work for search console

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#238]
In version 1.6.1, typing backspace in the search console would delete the last character you typed. However, on my build, it cycles through the potential options (like tab) but backward.

**Comment by 375gnu** [comment]
I'm unable to reproduce this on GNU/Linux. I suppose it's an OSX specific bug.

**Comment by LukeCEL** [comment]
Huh. By the way, I also can't copy-paste text. Is this a Mac-specific thing as well?

**Comment by 375gnu** [comment]
From the console? It never was implemented, as far as I can tell.

**Comment by 375gnu** [comment]
Hi @LukeCEL, does Ctrl-H work for you?

**Comment by LukeCEL** [comment]
> Hi @LukeCEL, does Ctrl-H work for you?

Ctrl-H selects the parent object. For example, if I have "Moon" selected, repeatedly pressing Ctrl-H selects "Earth", "Sol", "Solar System Barycenter", then de-selects it.

> From the console? It never was implemented, as far as I can tell.

Maybe we're talking about different things by "console". I am talking about the purple rectangle at the bottom of the screen when you press "Enter". There, I am able to copy and paste text.

**Comment by 375gnu** [comment]
On 5/15/19, LukeCEL <notifications@github.com> wrote:
>> Hi @LukeCEL, does Ctrl-H work for you?
>
> Ctrl-H selects the parent object. For example, if I have "Moon" selected,
> repeatedly pressing Ctrl-H selects "Earth", "Sol", "Solar System
> Barycenter", then de-selects it.

With console activated?

In GNU/Linux Ctrl-H behaves as backspace.

>> From the console? It never was implemented, as far as I can tell.
>
> Maybe we're talking about different things by "console". I am talking about
> the purple rectangle at the bottom of the screen when you press "Enter".

Me too.

> There, I am able to copy and paste text.

It was implemented by pirogronian recently.

**Comment by 375gnu** [comment]
@eyvallah could you check if this works for you?

**Comment by eyvallah** [comment]
@375gnu It seems when backspace is pressed, qtglwidget.cpp line 433, \x7f is passed in charEntered, which Celestia treats as a backtab

**Comment by eyvallah** [comment]
@375gnu well apparently, on MacBooks, there is technically no backspace button, it's the "delete" button that works as backspace, and delete button has key code \x7f. according to what's written in the original OS X implementation, some keys needs to be handled differently. I'll submit a pull request fixing it later
