### ISSUE TITLE
Duplicated dwarf planets

### ISSUE THREAD

**Issue by vpontin** [CelestiaProject/Celestia#239]
The dwarf planets added by [this commit](https://github.com/CelestiaProject/Celestia/commit/2375e17fff072851e0f363ddafae03f20bfe5a32) are duplicated by the entries on [asteroids.ssc](https://github.com/CelestiaProject/Celestia/blob/master/data/asteroids.ssc) (Ceres) and outersys.ssc (Haumea, Eris and other TNOs).

What is the most accurate and what about merge the changes in the files on `data` directory?

**Comment by Askaniy** [comment]
I'll fix it today. It's most accurate to remove Ceres from the `asteroids.ssc` and dwarf planets from the `outersys.ssc`. The `data` directory does not support trajectories, so everything that requires additional resources is taken out of it.

**Comment by vpontin** [comment]
Thanks a lot! Will close it for now.
