### ISSUE TITLE
Ceres doesnt have a texture in dwarf-planets extras

### ISSUE THREAD

**Issue by vico93** [CelestiaProject/Celestia#242]
The Ceres SSC entry on `dwarf-planets` in `extras-standard` points to ceres.* as texture, but this file doesnt exist on Celestia nor extras's textures folders, so Ceres is rendered white.

**Comment by Askaniy** [comment]
Ok, thanks, I'll fix it.

**Comment by 375gnu** [comment]
fixed by #389
