### ISSUE TITLE
HD 186302 have a wrong spectral type

### ISSUE THREAD

**Issue by vpontin** [CelestiaProject/Celestia#244]
[This is a solar sibling](https://en.wikipedia.org/wiki/HD_186302) and [should have a spectral type of G2V](https://celestia.space/forum/viewtopic.php?p=142609#p142609), but its listed as a G3.

**Comment by 375gnu** [comment]
@vpontin could you provide any reliable source that it's really G2V not G3?

**Comment by vpontin** [comment]
Yeah, i mistook Joey P's comment from that thread and thought that star had wrong spectral type.
