### ISSUE TITLE
Alpha Centauri Bb

### ISSUE THREAD

**Issue by vpontin** [CelestiaProject/Celestia#251]
This exoplanet still is shipped with Celestia, even though cientists have ruled out the initial studies as data noise.

https://en.wikipedia.org/wiki/Alpha_Centauri_Bb
https://news.nationalgeographic.com/2015/10/151028-planet-disappears-alpha-centauri-astronomy-science/
https://www.popularmechanics.com/space/a18003/no-alpha-centauri-b-planet/

**Comment by lrm25** [comment]
I can take it out.
