### ISSUE TITLE
Handling "relative names"

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#253]
Some names are "generated" by adding suffix to parent body name, for example `ALF Cen` is a parent for `ALF Cen A`. And here is my question: does it make valid such a names like `Toliman A`, `Gliese 559 A` etc automatically, without explicit naming in catalog?

**Comment by LukeCEL** [comment]
I think that's best done manually. There are too many exceptions when naming binary stars. For example, the two components of Gliese 195 are also called Capella H and Capella L, and the system as a whole is called Capella HL.
