### ISSUE TITLE
Appveyor build fails

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#256]
Appveyour fails to build my branch #247 . I tried to fix it, but it only generated next errors. I'm requesting help from someone more skilled with portable C++ code.

Currently errors regards defining static and constant in-class literals, like this:
`src/celengine/xindexdataloader.h`: 
`static constexpr const char CROSSINDEX_FILE_HEADER[] = "CELINDEX";`
`src/celengine/xindexdataloader.cpp`: 
`constexpr const char CrossIndexDataLoader::CROSSINDEX_FILE_HEADER[];`

For more examples please see AppVeyor logsfor my commits at #247 .

**Comment by 375gnu** [comment]
in src/celengine/xindexdataloader.h remove constexpr
in src/celengine/xindexdataloader.cpp remove that line completelly.
