### ISSUE TITLE
compile error char_traits ambiguous

### ISSUE THREAD

**Issue by krisztianpinter** [CelestiaProject/Celestia#269]
trying to compile newest celestia with newest libfmt from github, getting "reference to ‘char_traits’ is ambiguous" in modelfile.cpp:371:75. complete error message attached.

this is a linux mint,
gcc -v says 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 

[error.txt](https://github.com/CelestiaProject/Celestia/files/3081916/error.txt)

**Comment by pirogronian** [comment]
@krisztianpinter
If you have any programming skills, try add `std::` prefox to `char_traits` or other ambigous tokens. Meanwhile I'm, preparing fix.

**Comment by pirogronian** [comment]
@krisztianpinter
Please check out my PR #270 .

**Comment by 375gnu** [comment]
I'd say that's an fmt issue not our. @krisztianpinter why do you need the latest fmt?

**Comment by krisztianpinter** [comment]
@375gnu i don't. i just didn't bother to pick a version. my plan is to put celestia on amazon linux, and it does not seem to have access to libfmt out of the box. so i just pulled it from github and compiled instead. i can use an older version if i know which older version to use. or maybe instead of compiling, i hunt down a good host for the package and install from there.

and btw yeah, i agree that it sounds fishy that a lib update breaks existing code. but i don't know c++ in depth enough to judge.

**Comment by pirogronian** [comment]
@krisztianpinter 
It seems that `fmt` has its own `char_traits` template class: [https://github.com/fmtlib/fmt/search?q=char_traits&unscoped_q=char_traits](https://github.com/fmtlib/fmt/search?q=char_traits&unscoped_q=char_traits).
However, it's in namespace `internal`. Maybe it is his bug that is shown outside. Could You post an issue to them?

**Comment by 375gnu** [comment]
I have reported https://github.com/fmtlib/fmt/issues/1117

**Comment by 375gnu** [comment]
@krisztianpinter you don't need to compile fmt on your own, we provide git submodules for less common  dependencies, so i suggest doing the following:
* rm /path/to/local/fmt/installation
* git clone https://github.com/CelestiaProject/Celestia && cd Celestia
* git submodule update --init

then follow usual build procedure.

It seems we should update build instructions :)

**Comment by krisztianpinter** [comment]
sigh. so much ado about nothing! :)
i think i can close this issue now?

**Comment by 375gnu** [comment]
Let's wait for fmtlib/fmt#1117 resolution.

**Comment by 375gnu** [comment]
Fixed on fmt side
