### ISSUE TITLE
Duplicated names in database - what should I do?

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#274]
Trying to make my branch #247  work, I discovered that some star names in starnames.dat are differently assigned in *stc files. For example, in starnames.dat index 67275 is a `TAU Boo`, while in extrasolar.stc this name is defied for barycenter, while 67275 is bound to `TAU Boo A`. This cause a crash in my code (because barycenter is the same object as orbiting star), but legacy code somehow overcome it and works well. So, my question is: should it be fixed on data files level, or should I re-create legacy behaviour (although I already have tried without success)?

**Comment by 375gnu** [comment]
I believe that current code ("legacy" as you call it) behaves correctly, because Hipparcos might not have enough resolution to distinuish some double stars so they were fixed in stc files using data from other sources.

**Comment by pirogronian** [comment]
I have to agree.
