### ISSUE TITLE
context menu entry "back to the star"

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#279]
> In 1.6.1, the contextual menu of the stars (right click) makes it possible to see and go towards the planets which revolve around the star; it's the same thing between a planet and its moons. I regret that there is not a reverse command of the same type to the 'parent' object: from a planet to its star, from a moon to its planet, ...
> The planets of the Solar System, we know them, at least I hope so, but the exoplanets are called all b, c, d, or e and after a while we do not know where we are. A simple command back to the star would be really nice.

**Comment by lrm25** [comment]
I can work on this one

**Comment by 375gnu** [comment]
Yes please. I assign this bug to you

**Comment by lrm25** [comment]
Does celestia have any rogue planets which don't have parent stars, so that I don't include the menu option in that case?

**Comment by 375gnu** [comment]
On 7/5/19, Luke <notifications@github.com> wrote:
> Does celestia have any rogue planets which don't have parent stars, so that
> I don't include the menu option in that case?

Currently not, but if you add such possibility in advance that will be great.

**Comment by pirogronian** [comment]
> On 7/5/19, Luke ***@***.***> wrote:
 Does celestia have any rogue planets which don't have parent stars, so that
 I don't include the menu option in that case?
Currently not, but if you add such possibility in advance that will be great.

It should be soonly implemented in my branch astrodb.

**Comment by lrm25** [comment]
Do you want the option added to dwarf planets as well?  Any other bodies orbiting stars?

**Comment by 375gnu** [comment]
Yes. And not only for bodies but also for bodies orbiting other bodies. So if we have a spacecraft on a Moon orbit, the it's "Back" selects the Moon, the Moon's "Back" selects Earth and Earth's one selects the Sun.

**Comment by lrm25** [comment]
OK.  How do you want me to handle Pluto-Charon, which has a "Reference point" at its center, rather than an actual object?

**Comment by 375gnu** [comment]
@LukeCEL, @Askaniy could you elaborate with the question above?

**Comment by 375gnu** [comment]
Personally I'd prefer to ignore ref points and use a planet or dwarf planet of a pair as a main body, so in this case for Charon "back" will select Pluto.

**Comment by 375gnu** [comment]
Implemented in #339
