### ISSUE TITLE
Compilation error with LuaJit support

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#295]
My compilation of master failed with several errors like these:
`src/celestia/celx.cpp:476:13: error: ‘lua_open’ was not declared in this scope`
`src/celestia/celx.cpp:695:13: error: ‘lua_iolibopen’ was not declared in this scope`
`src/celestia/celx.cpp:928:76: error: too few arguments to function ‘int lua_load(lua_State*, lua_Reader, void*, const char*, const char*)`
`src/celestia/celx.cpp:1125:13: error: ‘lua_iolibopen’ was not declared in this scope`
`src/celestia/celx.cpp:1351:5: error: ‘lua_baselibopen’ was not declared in this scope`
`src/celestia/celx.cpp:1352:5: error: ‘lua_mathlibopen’ was not declared in this scope`
`src/celestia/celx.cpp:1353:5: error: ‘lua_tablibopen’ was not declared in this scope`
`src/celestia/celx.cpp:1354:5: error: ‘lua_strlibopen’ was not declared in this scope`
`src/celestia/celx.cpp:1419:25: error: ‘LUA_GLOBALSINDEX’ was not declared in this scope`

In cmake config there is following strange statement:

`Found LuaJIT: /usr/lib/liblua5.3.so;/usr/lib/libm.so;dl`

Of course, `/usr/lib/liblua5.3.so` belongs to `lua 5.3` on my system.

Most obvious related to #292 .

**Comment by 375gnu** [comment]
Have you cleaned up your buildspace? cmake caches a lot and then an old lua used instead of a new one (the same will be if you switch from 5.3 to 5.2 or 5.1 or vise verse).

**Comment by pirogronian** [comment]
Indeed, removing `CMakeCache.txt` helped.
