### ISSUE TITLE
Need to fix obs:gotolonglat error

### ISSUE THREAD

**Issue by CelestiaProject** [CelestiaProject/Celestia#3]
In Celestia 1.7.0 source code (even in the 5229 revision from SF), the error occurred: In CELX scripts where used obs:gotolonglat command, not processed **distance** parameter. The reason for this is unknown to me, but I think that error associated with porting the source code on a new mathematical engine **Eigen**.

**Comment by Alexell** [comment]
**Write in celx:** `obs:gotolonglat(Earth, math.rad(0), math.rad(30), 3.5004702E14, 5)`
Celestia must go to Earth at a distance 3.5004702E14, but Celestia go to Earth center!
**File:** celx_observer.cpp
**String 363:** distance = distance / KM_PER_LY;
If comment this string, the Celestia go to Earth the correct distance.

**Comment by Alexell** [comment]
[c81bd5f](https://github.com/CelestiaProject/Celestia/commit/c81bd5fed991c810a30d35be3fa6adfdf39c0730)
