### ISSUE TITLE
Update pot files

### ISSUE THREAD

**Issue by iglosiggio** [CelestiaProject/Celestia#30]
While making progress on packaging Celestia (QT5) for debian  i've stumbled upon the lack of a full translation for the interface.

I'm will to provide an ~ almost_good ~ translation to spanish after i finish [this](https://github.com/HuayraLinux/pkg-celestia), but in the meantime i think that making this an issue can help a lot in the translation to other languages.

I'm attaching the `.pot` file generated and the script that i use for generating it.

#### update_pot.sh
```bash
#!/bin/bash

extractrc $(find -name \*.ui -o -name \*.rc -o -name \*.kcfg) > testrc.cpp
xgettext -ki18n -k_ -F -j \
         -d celestia --package-name=celestia --package-version=1.7.0 --msgid-bugs-address=chris@teyssier.org --copyright-holder="Chris Laurel" \
         $(find . -name \*.c -o -name \*.cpp -o -name \*.cc -o -name \*.h -o -name \*.hpp -o -name \*.qml) -o po/celestia.pot
rm testrc.cpp
```

#### generated file (gzipped for github)
[celestia.pot.gz](https://github.com/CelestiaProject/Celestia/files/1686087/celestia.pot.gz)

**Comment by iglosiggio** [comment]
I've just realized that this corresponds to #4

**Comment by CelestiaProject** [comment]
@Alexell , you need to check the correctness of the POT file generated by the script.

**Comment by Alexell** [comment]
@iglosiggio Thanks for the script!
