### ISSUE TITLE
Build for 64 bits macOS 10.15 Catalina and Ubuntu

### ISSUE THREAD

**Issue by freebrowser1** [CelestiaProject/Celestia#309]
Where can I find an install kit or a build kit to build a 64 bits Celestia for macOS ?
The version 1.6.1 is from 2011 and does not run on macOS 10.15 as it is 64 bits only.
The same applies to Ubuntu, as 19.10 does not support 32 bits anymore.

**Comment by 375gnu** [comment]
Hi @freebrowser1 , we don't have 1.7 release yet so we don't provide any installers of packages for it.

You can always compile Celestia, just follow instructions from INSTALL files.

**Comment by 375gnu** [comment]
@freebrowser1 see #388 for instructions how to use our OBS builds
