### ISSUE TITLE
OSX maintainer required

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#323]
We don't have any OSX maintainer

**Comment by eyvallah** [comment]
would love to help, what is needed?

**Comment by 375gnu** [comment]
Hi @eyvallah !

We need somebody able to test Celestia regularly on OSX platform, report and potentially fix found bugs (We were reported that stars are rendered incorrectly on OSX). Provide builds as homebrew and dmg packages. Replace deprecated OSX functions used in the Qt5 interface with modern equivalents. Make native interface buildable (src/celestia/macosx dir) and update it to be in sync with Qt5 interface.

**Comment by eyvallah** [comment]
I think I can help. I have experience working in both Qt and OSX. will try to set up a starting environment locally if I have time this weekend

**Comment by 375gnu** [comment]
Great!

**Comment by eyvallah** [comment]
How do we fix the CI, seems to be missing the glew dependency but the config should have it installed. Is it because the system/Xcode is outdated?

**Comment by 375gnu** [comment]
It looks like the homebrew cache is outdated in OSX images used by Travis

**Comment by 375gnu** [comment]
According to https://docs.travis-ci.com/user/reference/osx/#compilers-and-build-toolchain

> By default, the Homebrew addon will not run brew update before installing packages. brew update can take a long time and slow down your builds. If you need more up-to-date versions of packages than the snapshot on the build VM has, you can add `update: true` to the addon configuration
```
addons:
  homebrew:
    packages:
    - foo
    - bar
    update: true
```

Or we can switch to another version:
https://docs.travis-ci.com/user/reference/osx/#macos-version

**Comment by eyvallah** [comment]
Yeah it's the homebrew's issue, I didn't read the detail of homebrew package installation since it's folded on CI output. I think we should switch to a newer version first. While I have some linking issue on macOS 10.15 + Xcode 11, osx_image: xcode10.2 sounds like a good choice.
