### ISSUE TITLE
macOS version should be distributed in App Bundle

### ISSUE THREAD

**Issue by eyvallah** [CelestiaProject/Celestia#334]
Currently the CMake script builds and installs Celestia executable to prefix/bin directory and resources to prefix/share directory, whereas macOS Applications are usually distributed in App Bundles with a fixed location of resources. And it's also the way it can be distributed on Mac App Store/brew cask.

The CMakeLists.txt in celestia/qt needs to have MACOSX_BUNDLE variables set on macOS platform, and resource data directory needs also to be set to a given path relative to the App Bundle in runtime in order to make it happen.

**Comment by eyvallah** [comment]
With #336 , Celestia is running in application bundle

![screenshot](https://user-images.githubusercontent.com/17924287/62408127-280c7c80-b5f6-11e9-90c0-17613165fc0f.png)

**Comment by 375gnu** [comment]
Looks great!

But does homebrew package should use Resource folder? I'm not an OSX user, so i'm jugging just by some paths seen in brew packages. So I thought that are just installed to /usr/local like on unix-like systems.

**Comment by eyvallah** [comment]
/usr/local are usually for command line executables, GUI applications on macOS usually are distributed via a DMG containing an App Bundle.

celestia.app
-Contents
--MacOS
---celestia-qt and other tools
--Resources
---data files

While it's possible to distribute GUI application in /usr/local fashion just like it does on linux and etc, it's more viable to distribute in App Bundles since most macOS users just launch app from /Application folder.

You can checkout brew cask, basically installed the app  bundle to /Application and link to /usr/local/bin to make it work both via cli and macOS launchpad
https://github.com/Homebrew/homebrew-cask

**Comment by 375gnu** [comment]
Okay, I suppose you know your system better than me. I just want to have possibility to build like on GNU/Linux because some community members know how to use `cmake && make && make install` and I don't want accidentally break anything for them.

**Comment by eyvallah** [comment]
I’ll separate the two by native_osx_app, will look into it later.

**Comment by eyvallah** [comment]
closing this now, since it can already be configured to build celestia-qt in bundle.
