### ISSUE TITLE
panning is broken

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#34]
When one starts panning (horizontal or vertical movement of a camera) the camera "jumps" (usually up and right) and then continues to move properly.

This issue exist only with a Qt version, not with a glut one.

**Comment by CelestiaProject** [comment]
Do you have any ideas how to solve the problem?

**Comment by gstark31897** [comment]
Hey, do you guys mind if I work on this? I made a pull request that should address this.

**Comment by CelestiaProject** [comment]
@gstark31897 Of course, do not mind. The main thing that everything worked!
