### ISSUE TITLE
QT_SCALE_FACTOR mouse selection bug

### ISSUE THREAD

**Issue by Adriankhl** [CelestiaProject/Celestia#348]
It is pretty common to use QT_SCALE_FACTOR to magnify the UI. In celestia, setting QT_SCALE_FACTOR != 1 would introduce a bug - you can't select the star your mouse pointing at. Instead, it selects something located somewhere upper-left to where you point at.

**Comment by 375gnu** [comment]
Currently our Qt frontend doesn't support HiDPI properly (easy to fix, just 2 lines). Then we can check if QT_SCALE_FACTOR is set and scale coordinates sent to celestiacore.

**Comment by 375gnu** [comment]
Might be useful: https://vicrucann.github.io/tutorials/osg-qt-high-dpi/. I don't have a hidpi screen to verify.

**Comment by levinli303** [comment]
This is done already.
