### ISSUE TITLE
Missing arrow in qt-5.13

### ISSUE THREAD

**Issue by dlshcbmuipmam** [CelestiaProject/Celestia#349]
To the left of "Solar system barycenter", there should be a small arrow where it shows the list of the objects in the solar system. That arrow is missing in the MSVC build with the latest qt 5.13

**Comment by dlshcbmuipmam** [comment]
It can also be related to latest qt 5.13

**Comment by 375gnu** [comment]
I think so too

**Comment by dlshcbmuipmam** [comment]
> 
> I think so too
> […](#)
> On 8/8/19, khlai ***@***.***> wrote: It can also be related to latest qt 5.13 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#349 (comment)](https://github.com/CelestiaProject/Celestia/issues/349#issuecomment-519385837)

I delete my comment because I thought I was using qt 5.12 in vcpkg. Instead I realize that I am using the direct download of qt 5.12, my fault

**Comment by dlshcbmuipmam** [comment]
> 
> I think so too
> […](#)
> On 8/8/19, khlai ***@***.***> wrote: It can also be related to latest qt 5.13 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#349 (comment)](https://github.com/CelestiaProject/Celestia/issues/349#issuecomment-519385837)

Confirmed, it is a problem with qt 5.13
