### ISSUE TITLE
MinGW debug build fail

### ISSUE THREAD

**Issue by dlshcbmuipmam** [CelestiaProject/Celestia#350]
The debug build in MSYS2 + MinGW by 
`cmake .. -G "MSYS Makefiles" -DENABLE_WIN=OFF -DCMAKE_BUILD_TYPE=Debug`
takes forever to link the celestia-qt.exe. This can be related directly to MinGW, or gcc9.1 (the compiler in my MinGW). 

This should not be a high priority issue, but it is better to keep an eye on what cause this problem.

**Comment by dlshcbmuipmam** [comment]
I accidentally found a solution, use the lld linker instead of the default linker
cmake .. -G "MSYS Makefiles" -DENABLE_WIN=OFF -DCMAKE_CXX_FLAGS='-fuse-ld=lld'

**Comment by 375gnu** [comment]
@dlshcbmuipmam could you document the workaround in INSTALL.txt?

**Comment by dlshcbmuipmam** [comment]
> @dlshcbmuipmam could you document the workaround in INSTALL.txt?

@375gnu Sure.
