### ISSUE TITLE
Xcode's clang seems to dislike passing object in varargs

### ISSUE THREAD

**Issue by eyvallah** [CelestiaProject/Celestia#367]
the cmake generated Makefile and Xcode project works, however the native project I'm maintaining is still throwing error (in addition to the class name clash) in compiling with the fmt commit.

for passing string/fs in DebugPrint:
Can not pass object of non-trivial type /xxx/ through variadic function; call will abort at runtime

for the vprintf in debug.cpp:
No matching function for call to 'vfprintf'
note: candidate function [with S = const char *, Char = char] not viable: no known conversion from 'va_list' (aka '__builtin_va_list') to 'basic_format_args<typename basic_printf_context_t<internal::basic_buffer<char> >::type>' (aka 'basic_format_args<basic_printf_context<back_insert_iterator<fmt::v5::internal::basic_buffer<char> >, char> >') for 3rd argument

**Comment by 375gnu** [comment]
my fault, fmt doesn't have vfprintf. strange, i was checking debug builds.

**Comment by 375gnu** [comment]
it seams that we should reimplement this using variadic templates:
