### ISSUE TITLE
solar system objects not appearing in browser

### ISSUE THREAD

**Issue by joequant** [CelestiaProject/Celestia#374]
This is happening with a compile of commit bcce846 on 20190822.

Not seeing any objects in solar system browser.

![2019-08-25 16-11-55 的螢幕擷圖](https://user-images.githubusercontent.com/2908185/63647393-29434c00-c753-11e9-8f6b-95f888f7e147.png)

**Comment by 375gnu** [comment]
Actually the 1st problem commit is b6b54343, but I don't have Earth texture

**Comment by 375gnu** [comment]
Currently it looks like #349

**Comment by dlshcbmuipmam** [comment]
@375gnu Yes it is exactly what I saw in my qt-5.13 build

**Comment by dlshcbmuipmam** [comment]
@joequant Could you check your qt version?

**Comment by munix9** [comment]
This is similar to openSUSE Tumbleweed since it was switched to Qt 5.13 there.

Build log:
https://build.opensuse.org/build/home:munix9:unstable/openSUSE_Tumbleweed/x86_64/celestia/_log

https://software.opensuse.org//download.html?project=home:munix9:unstable&package=celestia

**Comment by eyvallah** [comment]
it seemed to me  it's qt's createIndex in qtsolarsystembrowser.cpp, at line 503 isn't working well.

**Comment by eyvallah** [comment]
make SolarSystemTreeModel inherit directly from QAbstractItemModel seemed to solve the issue? @375gnu 

![ss](https://user-images.githubusercontent.com/17924287/63738088-38dda480-c8bb-11e9-863e-83bb915a7a9a.png)
