### ISSUE TITLE
SourceForge vs. Github

### ISSUE THREAD

**Issue by mmontag** [CelestiaProject/Celestia#39]
Which repository is the canonical source location, Github or SourceForge (https://sourceforge.net/projects/celestia/?source=directory)? Should we add a message at the SourceForge repository if this is now the place for active development?

**Comment by CelestiaProject** [comment]
@mmontag , Celestia repository on SourceForge has not been updated for a long time and will no longer be updated.
Chris Laurel in 2016 instructed us to move the repository to GitHub.

**Comment by vlad1777d** [comment]
GitLab =)
