### ISSUE TITLE
Remove logoTexture from celestiacore

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#417]
For quite a while Celestia 1.7 supports overlay images set by cel/celx scripts. On the other hand it has hardcoded logotexture shown on startup. It seems natural to remove that C++ code and replace it with one line in start.cel.

It will require some additions to overlay image to support colors but for me it's OK to have more usable generic overlay image rather then the current approach.

Any objections?

**Comment by pirogronian** [comment]
You have my blessing.
