### ISSUE TITLE
Bugs detected in Celestia code with the help of PVS-Studio

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [CelestiaProject/Celestia#425]
Hello. I've found some bugs using PVS-Studio tool. [PVS-Studio](https://www.viva64.com/en/pvs-studio/) is a static code analyzer for C, C++, C#, and Java.

Code review: [Celestia: Bugs' Adventures in Space](https://www.viva64.com/en/b/0673/).

**Comment by 375gnu** [comment]
Thank you for checking. Actually I run PVS-Studio from time to time, so you can even find some commits closing its reports, but I've never checked windows frontend and tools.

**Comment by SvyatoslavRazmyslov** [comment]
@375gnu, the PVS-Studio is cross-platform tool. I used the `.appveyor.yml` to configure build environment.

**Comment by 375gnu** [comment]
I know, I'm just too lazy to enable it for all PRs. BTW, on Debian Sid it segfaults, I'll check the latest version on up-to-date installation and report through a feedback form.
