### ISSUE TITLE
Double names

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#441]
In Celestia 1.7 the name of every object is shown twice, like "Earth / Earth".

**Comment by SevenSpheres** [comment]
Question: Does the same thing happen in languages other than English? Is there a way I can change Celestia's language so I can check for myself?

**Comment by 375gnu** [comment]
On 10/12/19, SevenSpheres <notifications@github.com> wrote:

> Question: Does the same thing happen in languages other than English? Is

No. And that's why we have missed this bug.

> there a way I can change Celestia's language so I can check for myself?

LC_MESSAGES=<lang code> celestia-qt

**Comment by SevenSpheres** [comment]
Okay, issue is solved, but I'm still curious...

> LC_MESSAGES=&lt;lang code&gt; celestia-qt

Where do I put this? I use Windows.

**Comment by 375gnu** [comment]
so, open command terminal window (or just run `cmd.exe`) and type `set LC_MESSAGES=be` and press `Enter` (use your language instead of `be`) and then type `celestia-qt` and press `Enter`. `celestia-qt` must be in your `%PATH%` or before running Celestia type `cd <directory with celestia-qt.exe>`

**Comment by SevenSpheres** [comment]
That doesn't work; when I do that Celestia starts but still in English. It doesn't matter since the issue is solved and "my language" is English, but maybe this is another thing to add to celestia.cfg?

**Comment by 375gnu** [comment]
Alternatively you can set another language using windows' control panel (language and region, afair), but will change it globally.
