### ISSUE TITLE
Star orbits don't show in 1.7

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#448]
See title

**Comment by 375gnu** [comment]
They are not shown in earlier versions as well.

**Comment by SevenSpheres** [comment]
They are for binary star systems.

**Comment by SevenSpheres** [comment]
**375gnu**, please remove the "enhancement" label and add the "bug" label.

**Comment by 375gnu** [comment]
@SevenSpheres look like data files are incorrect for ALF Cen in 1.7

**Comment by SevenSpheres** [comment]
ALF Cen in 1.6.1 with orbits turned on:
![alfcen-orbit-161](https://user-images.githubusercontent.com/56284207/67052210-b58e4180-f0fa-11e9-8839-e938c1e19380.png)
ALF Cen in 1.7.0 with orbits turned on:
![alfcen-orbit-170](https://user-images.githubusercontent.com/56284207/67052211-b58e4180-f0fa-11e9-8a4b-27390dbfe3fe.png)
Same for any other binary/multiple system.

**Comment by SevenSpheres** [comment]
I just noticed that if a star has planets its orbit is shown. For example, in the 16 Cygni system, 16 Cyg B's orbit is visible but 16 Cyg A's is not.

**Comment by 375gnu** [comment]
That's funny but 1.6 doesn't have a code for star's orbits :) I dunno why this happens :)

**Comment by 375gnu** [comment]
My fault, really it should be supported.
