### ISSUE TITLE
Coverity issues

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#45]
Hi!

I've scanned the latest Celestia code using [Coverity](https://scan.coverity.com/) tool and it has found 182 issues.

Scan results can be found [here](https://scan4.coverity.com/reports.htm#v37293/p14711)

I'll try to fix them.

**Comment by Alexell** [comment]
@375gnu Coverity does not allow viewing on your link (at least without authorization). But I'm aware of the presence of unfinished places in the code. I would be grateful if you could help me finish them.

**Comment by Alexell** [comment]
On our forum there are a lot of **messages about Celestia QT bugs**, but I do not have enough time to go to the forum yet.

**Comment by 375gnu** [comment]
Indeed, it requires authentication. I've sent you an invitation. https://scan.coverity.com/projects/celestia.

I'm not familiar with QT, 3D and astronomic programming, but I like Celestia so I just do what I can.
