### ISSUE TITLE
gtk build broken (1.7.0~)

### ISSUE THREAD

**Issue by munix9** [CelestiaProject/Celestia#456]
gtk build is currently broken (1.7.0~), probably caused by https://github.com/CelestiaProject/Celestia/commit/9401a4389efb05199c24449f112bd5626225e61a https://github.com/CelestiaProject/Celestia/commit/3cb4d3154d1fd1ac48cfd212c7b1c7a39b3e184b

all repositories are affected (except appimage, which only builds qt), eg.
https://build.opensuse.org/public/build/home:munix9:unstable/Debian_10/x86_64/celestia/_log
https://build.opensuse.org/public/build/home:munix9:unstable/openSUSE_Leap_15.1/x86_64/celestia/_log

**Comment by 375gnu** [comment]
I'll check, I haven't checked gtk for a while
