### ISSUE TITLE
Show dwarf planets and minor moons in right-click menu

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#459]
The right-click menu for the Sun lists planets, asteroids, comets, spacecraft, but not dwarf planets. Similarly, the right-click menus for planets list major moons but not minor moons.

**Comment by lrm25** [comment]
I can take this issue for qt and gtk.

**Comment by 375gnu** [comment]
@lrm25 it would be great

**Comment by 375gnu** [comment]
@lrm25 please add them to their own submenus, it wont be comfortable to anybody to look for any Saturn's moon among 82 entries.

**Comment by lrm25** [comment]
Pluto is contained inside a reference point, and with the way the code is written right now, it would require a code restructuring to include it in the sun's menu.  Should I ignore Pluto for now, or try restructuring?

**Comment by 375gnu** [comment]
@lrm25 As you wish, I'm okay with the both options.

**Comment by lrm25** [comment]
I'll put in an initial PR without Pluto, and then I'll see if I can restructure the code and include it later.
