### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#467]
The 1.7 preferences dialog says "Spacecrafts". It should be "Spacecraft".

**Comment by SevenSpheres** [comment]
**375gnu**, this is not a bug, it is a simple typo.

**Comment by 375gnu** [comment]
@SevenSpheres why do you think it should be in singular here? All other objects are in plural as well.

**Comment by SevenSpheres** [comment]
The plural of spacecraft is the same, like with aircraft. Spacecrafts is not a word.

**Comment by SevenSpheres** [comment]
Some related things that don't need their own issues:
- "Sync Orbit" was changed to "Synch Orbit". This is fine, but why the change?
- The console warning about deprecated parameters is missing a line break after "Use GeomAlbedo instead."

**Comment by hv-work** [comment]
>     * "Sync Orbit" was changed to "Synch Orbit". This is fine, but why the change?

@SevenSpheres where did you find this?

**Comment by SevenSpheres** [comment]
> where did you find this?

It's in the right-click menu for any SSC object.

**Comment by 375gnu** [comment]
Okay, found it. I wouldn't say "it was changed". Qt interface is based on neglected KDE interface which had "Synch" from the very beginning. Windows is not the Center of the World :)

**Comment by SevenSpheres** [comment]
> Qt interface is based on neglected KDE interface which had "Synch" from the very beginning.

Okay, I wasn't aware of this. Also, is @hv-work an alternate account of @375gnu?

**Comment by 375gnu** [comment]
yes, that's me

**Comment by 375gnu** [comment]
Yes, we have fixed it. Thanks for pointing out.

**Comment by RacerBG** [comment]
My God, I'm an astronomy lover since 20 years and only now I learned that the plural of spacecraft is "spacecraft"... :smile:
