### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#472]
There are some pretty big changes in the upcoming version, including AstroDB and the switch to the QT interface. Given this and the hiatus since the last version (1.6.1), should it be called Celestia 2.0? See also [Selden's comment on same](https://celestia.space/forum/viewtopic.php?p=146377#p146377).

**Comment by 375gnu** [comment]
Qt was added in 1.6 actually. Regarding AstroDB we doubt that it will be merged before the 1.7 release.

Bumping version to 2.0 means that Celestia is not backward compatible with 1.x series.

From my side I'd suggest adopt other versioning policy adopted by large number of FLOSS projects: in stable releases use even second number, while odd number is for unstable releases. That way we can always distinguish stable and unstable releases and make proper unstable releases more often. This also means that the next release will be 1.8 not 1.7.

@pirogronian @eyvallah your thoughts?

**Comment by eyvallah** [comment]
I don't have strong opinions on versioning, there are apps with very slowly evolving number, and apps with progressive version numbers where a bump in major version doesn't mean a major change. personally I'd prefer 1.7.0

**Comment by SevenSpheres** [comment]
> Regarding AstroDB we doubt that it will be merged before the 1.7 release.

Oh okay. I thought it would be in 1.7 and make #460 unnecessary.

> Bumping version to 2.0 means that Celestia is not backward compatible with 1.x series.

Does this mean the next version number will definitely not be 2.0? In this case the issue can be closed.

> This also means that the next release will be 1.8 not 1.7.

I don't think skipping numbers is a good idea.

**Comment by eyvallah** [comment]
@SevenSpheres i think he means the next release after 1.7 will be 1.8.

**Comment by 375gnu** [comment]
@pirogronian

**Comment by pirogronian** [comment]
I'm unsure about all that. Technically I'd choose single number version, with alpha, beta and release candidate status. But it would quickly lead to big numbers which looks ugly... On the other hand, any more complex versioning system needs assumptions about developement proces. Despite being developer (not much active recently, however), I cant imagine how development will proceed even in nearest future.

**Comment by SevenSpheres** [comment]
Should I close this issue?
