### ISSUE TITLE
Search function and possible incomplete SAO index problem

### ISSUE THREAD

**Issue by LafuenteAstronomy** [CelestiaProject/Celestia#480]
Hello! This is my first time stating an issue, so I may not know exactly how Celestia works. 

I do have a certain problem with the search function in Celestia. When searching for stars in Celestia, theoretically, you can type "HIP", and then type any number up until 118,218. For example, I type HIP 12345:
![test image 1](https://user-images.githubusercontent.com/56778509/67658622-150b0d80-f995-11e9-90e0-ce2331d4bb98.jpg)
And then I get the result here:
![test image 2](https://user-images.githubusercontent.com/56778509/67658652-25bb8380-f995-11e9-8c9a-ee0b324e88c1.jpg)
Same thing goes when typing TYC objects:
![test image 3](https://user-images.githubusercontent.com/56778509/67658671-37049000-f995-11e9-80e6-654bc1dad881.jpg)
![test image 4](https://user-images.githubusercontent.com/56778509/67658680-3bc94400-f995-11e9-8d39-c5431e5a3834.jpg)
But when it comes to SAO objects, I typed a random SAO identifier here:
![test image 5](https://user-images.githubusercontent.com/56778509/67658706-53083180-f995-11e9-8448-45b3ff69de3a.jpg)
And nothing cam up as a result:
![test image 6](https://user-images.githubusercontent.com/56778509/67658716-5b606c80-f995-11e9-8b50-0c8432323ade.jpg)
I also noticed that when typing the numbers following the "HIP", "TYC" and "SAO" identifiers, there are no matches that were shown in the search results bar, unlike if I type either star names, Bayer Designations, Flamsteed Designations or objects with written identifiers in the starnames.dat file, like when I'm searching for an HR object, since I added HR designations to my starnames.dat file. In the latter case, matches are shown in the search results bar:
![test image 7](https://user-images.githubusercontent.com/56778509/67658813-ab3f3380-f995-11e9-80f3-9728317948c2.jpg)
So, maybe there are around 2 issues:
1: Perhaps the SAO index isn't actually complete, and though the objects associated with it could possibly exist in stars.dat, they may not be given the same identifiers, therefore, some stars with SAO identifiers could possibly not have SAO identifiers in Celestia's saoindex file.
2: I think matches should be shown when typing any HIP, TYC or any other identifier search, so that it'll be easier to find the one you're looking for. 
Well, those are my problems so far. Do what you think is best but if you can, please see what you can do with the issues I brought up. Thanks in advance

**Comment by SevenSpheres** [comment]
> so I may not know exactly how Celestia works.

I think you mean GitHub ;-)

> But when it comes to SAO objects, I typed a random SAO identifier here:
> And nothing cam up as a result:

Not all SAO stars are in the HIP and TYC catalogs. I did find SAO 54322 though - try using Luke's cross-index files which I have in my repository [here](https://github.com/SevenSpheres/Celestia-stars).

> I also noticed that when typing the numbers following the "HIP", "TYC" and "SAO" identifiers, there are no matches that were shown in the search results bar, unlike if I type either star names, Bayer Designations, Flamsteed Designations or objects with written identifiers in the starnames.dat file

I already have an issue open about this [here](https://github.com/CelestiaProject/Celestia/issues/470).

**Comment by SevenSpheres** [comment]
@375gnu, this issue can probably be closed, since one thing is a non-issue and the other is a duplicate.

**Comment by SevenSpheres** [comment]
Looks like I can close this myself now. The only thing that needs to be done here is updating the star database, which will be done in the [CelestiaContent](https://github.com/CelestiaProject/CelestiaContent) repository (just waiting for it to be finalized).

**Comment by SevenSpheres** [comment]
Looks like I can close this myself now. The only thing that needs to be done here is updating the star database, which will be done in the [CelestiaContent](https://github.com/CelestiaProject/CelestiaContent) repository (just waiting for it to be finalized).
