### ISSUE TITLE
AstroDB memory (and CPU) usage 

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#482]
AstroDB is aimed at unifying database structure and enabling dynamic data loading/unloading. However, there are several disadvantages of my implementation, which I cannot overcome so far. This is, mainly, high memory usage. That's why I call for help, in any form - a suggestion or a code.

Possible memory load origins:

1. Common objects data, like name handling and position vector. However, their overall size, calculated by me, seems negligible.
2. Dynamic, general purpose indexes, based on stl containers. I cant imagine, however, their proper replacement.
3. New octree architecture. Octree memory consumption can be reduced by increasing objects per node number, but it increases CPU load.

Recently I added some debug code for memory stats.

CPU load:
Is much less problem, but noticable. According to profiler, tied mostly to `processVisibleStars` function.

AstroDB is currently under #454 pull request.

**Comment by 375gnu** [comment]
1) What benefit gives us object unloading?
2) list is slow, why not vector?
3) have you read the paper about openspace octree i pointed you?

**Comment by pirogronian** [comment]
1. Paradoxically, to handle larger data.
2. Because for this purpose vector would be tremendously slow. These lists are primarily due to handle Lua `celestia:getstars` and `celestia:getdsos` (which needs serious optimisation anyway). I needed container that could easly add, remove and iterate over items, but without need to arbitrary lookup.
3. I remember something of it, so probably yes. But apparently I was hoping for more general and flexible mechanism that desnt need special preparation of data prior to its loading. Maybe I was wrong.

**Comment by pirogronian** [comment]
From Celestia/src/celengine/octree.h:

// There are two classes implemented in this module: StaticOctree and
// DynamicOctree.  The DynamicOctree is built first by inserting
// objects from a database or catalog and is then 'compiled' into a StaticOctree.
// In the process of building the StaticOctree, the original object database is
// reorganized, with objects in the same octree node all placed adjacent to each
// other.  This spatial sorting of the objects dramatically improves the
// performance of octree operations through much more coherent memory access.

This is probably main cause of both issues. To overcome it, without resigning from dynamic database, I'd add separate "static" octree as defaulr and dynamuc one for objects declared as "dynamic". Looka a bit like reinventing wheel, but it's a prise of sketchy reading someone's code...
