### ISSUE TITLE
Reference points aren't labeled

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#489]
Mentioned [here](https://github.com/CelestiaProject/Celestia/issues/463) and [here](https://github.com/CelestiaProject/Celestia/pull/478); not fixed in the November 1 build.

Note that orbits and labels of reference points should only be shown if they have:
`    Visible true`
`    Clickable true`
(or at least this is how it works in 1.6.x)

**Comment by 375gnu** [comment]
could you provide refpoints with labels shown in 1.6.1?

**Comment by SevenSpheres** [comment]
![pluto-label-161](https://user-images.githubusercontent.com/56284207/68077734-86303380-fd8e-11e9-9bd7-729d0354bab4.png)

**Comment by 375gnu** [comment]
Are you using standard data files? In default 1.6.1 it's not shown.

**Comment by SevenSpheres** [comment]
The screenshot is basic unmodified 1.6.1

**Comment by 375gnu** [comment]
Quite interesting, that only windows native version shows them.
