### ISSUE TITLE
Fade constellation boundaries and constellations figures

### ISSUE THREAD

**Issue by CelestiaProject** [CelestiaProject/Celestia#5]
The boundaries of the constellations fade at a distance of **1.6 AU** from the sun.
The figures of the constellations fade at a distance of **20 kpc** from the sun.

In fact, it turns out that the Earth's border is almost invisible. It needs to be fixed.

**Comment by Alexell** [comment]
**File:** render.cpp
Maybe **Render asterisms** section.
Instead string `float dist = observerPosLY.norm() * 1e6f;`
write `float dist = observerPosLY.distanceFromOrigin() * 1e6f;` ???

**Comment by Alexell** [comment]
Or just increase **1e6f** value...

**Comment by CelestiaProject** [comment]
Now the constellation boundaries slowly fade in the distance of 70 AU from the Sun, and the constellations figures fade at a distance of 4 light-years from the Sun.
`float dist = observerPosLY.norm() * 1.6e4f;`
