### ISSUE TITLE
Celestia logo not showing in README.md

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#500]
Recently the Celestia logo has disappeared from README.md, showing only a "broken image" icon. This doesn't seem to be because of any changes to README.md. When I click on "Open Image" I get [this](https://camo.githubusercontent.com/8d4065470e30d95d57f6412aa51cef83200745e5/68747470733a2f2f63656c657374696170726f6a6563742e6e65742f696d672f616c62756d732f323031372f30342f32302f39613537643866323161313239303439613662306531646133613563383532642e706e67), which says `Error Fetching Resource`; but the image URL referenced in the code for README.md is [this](https://celestiaproject.net/img/albums/2017/04/20/9a57d8f21a129049a6b0e1da3a5c852d.png), which works. I have no idea what's going on here.

Edit: ...and this is issue/PR number 500. Wow.

**Comment by Anthony-B-Russo10** [comment]
It disappeared sometime after my edit to it.

**Comment by SevenSpheres** [comment]
But it had nothing to do with your edit; if you look at a version of README.md before your edit to it the image is still missing.

**Comment by Anthony-B-Russo10** [comment]
Then I don't know what happened.

**Comment by eyvallah** [comment]
hmm. it's showing for me. probably the url should be changed, i think celestiaproject.net is the old domain

**Comment by 375gnu** [comment]
first, it's better to update url to point to celestia.space. second, the actual problem is caused by ddos protection enabled.

**Comment by SevenSpheres** [comment]
> first, it's better to update url to point to celestia.space.

I did this [here](https://github.com/SevenSpheres/Celestia/tree/fix-readme).

> second, the actual problem is caused by ddos protection enabled.

So how can we work around this?

**Comment by 375gnu** [comment]
> I did this [here](https://github.com/SevenSpheres/Celestia/tree/fix-readme).

I'm waiting for PR :)

> So how can we work around this?

Move the image to Github

**Comment by SevenSpheres** [comment]
> Move the image to Github

How do I do that?
