### ISSUE TITLE
Appveyor artifacts don't work

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#523]
When trying to run any of the Celestia binaries from the "artifacts" section of [Appveyor](https://ci.appveyor.com/project/375gnu/celestia/history) (both QT and Windows versions), I get this error message:

![celestia-error-crop](https://user-images.githubusercontent.com/56284207/69291380-54a5cd80-0bc0-11ea-99e1-85f3a8af81d0.png)

The earlier builds from [Bintray](https://bintray.com/celestia/celestia-builds/snapshots) work fine for me. This was previously mentioned [here](https://github.com/CelestiaProject/Celestia/pull/495), where is was suggested I install the Visual Studio 2015 runtime libraries, but it turns out I already had that installed.

**Comment by eyvallah** [comment]
I guess it’s due to the change in font rendering? You might need freetype.dll and a ttf font configured to run the artifact. @375gnu

**Comment by 375gnu** [comment]
Yes, freetype is required. Please wait until I create a new full build.

**Comment by 375gnu** [comment]
Actually freetype is not used yet, cause appveyor.yml has an error :) but i still think that the problem is with vc runtime. @SevenSpheres do you really have it for 32bit (x86) system?

**Comment by SevenSpheres** [comment]
> do you really have it for 32bit (x86) system?

Both x64 and x86.

**Comment by SevenSpheres** [comment]
@Anthony-B-Russo10 @LafuenteAstronomy @Panterstruck, anyone else who uses Windows - do these binaries work for you?

**Comment by Anthony-B-Russo10** [comment]
![2019-11-21 (3)](https://user-images.githubusercontent.com/57239744/69389404-e8979800-0c99-11ea-8c36-c99885109bd3.png)
![2019-11-21 (2)](https://user-images.githubusercontent.com/57239744/69389406-e8979800-0c99-11ea-8660-c693d3d52fff.png)
I get these errors, the builds of 1.7.0 I have work, but on my main computer crash on my main laptop and don't work on the others due to software incompatibility.
I also run Linux and MacOS X Snow Leopard 10.6.8.

**Comment by SevenSpheres** [comment]
It's a _different_ error message. Odd.

**Comment by Anthony-B-Russo10** [comment]
Yeah.

**Comment by SevenSpheres** [comment]
Hmm...it's having problems with "fmt.dll". Make sure you have the latest version of that file (from the September 3 build on Bintray).

**Comment by Anthony-B-Russo10** [comment]
I'think so.

**Comment by SevenSpheres** [comment]
When I use the .exe and DLLs from [this post](https://celestia.space/forum/viewtopic.php?p=147706#p147706), I get the same error (in the OP) when trying to run the old executable. When I put back the old DLLs, the new executable gives me the error. So I think the problem can be solved by always including DLLs with new builds.

**Comment by SevenSpheres** [comment]
With the latest build:
- QT version returns the same error
- Win version starts up, but info text is missing and stars viewed close up are too dark, as if the star style was set to "scaled disks"

**Comment by SevenSpheres** [comment]
Using the latest build with ttf fonts, both the QT and Win versions start up, and they both look like this:

![redtext](https://user-images.githubusercontent.com/56284207/72668099-664cfb00-39e0-11ea-9e1d-f884480f9fb5.png)

Same problem with star rendering as before.

**Comment by SevenSpheres** [comment]
Just realized that this should be closed, since the problem is fixed.
