### ISSUE TITLE
Can't type some characters in search

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#526]
In Celestia 1.6.1, when the search box is open (by pressing Enter), pressing any key will type into the search box. In Celestia 1.7, it's impossible to type brackets in the search box; regardless of whether the search box is open, typing brackets will always adjust the limiting magnitude. This may also be the case for other characters; I haven't tried pressing every key.

This actually is a problem - in some catalogs of objects, particularly those derived from SIMBAD, there are object names with brackets.

**Comment by 375gnu** [comment]
@SevenSpheres i suppose the problem is with Qt interface only, isn't it?

**Comment by SevenSpheres** [comment]
> i suppose the problem is with Qt interface only, isn't it?

Yes it is, I never noticed that (since I'm not checking everything with both frontends).
