### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by shujaatak** [CelestiaProject/Celestia#534]
Where can I find build instructions for Windows?
Is there any step by step guide/tutorial?
In most Github repositories I find the build instructions/links in the Readme file or in Wiki but I couldn't find them in Celestia repository.

**Comment by shujaatak** [comment]
Clear and easy build instructions/method would attract more developers to contribute to Celestia.

**Comment by eyvallah** [comment]
yes I agree. Currently you can resort to the INSTALLATION file in the root directory for building.

We will need to rewrite that file in markdown to make it more friendly

**Comment by 375gnu** [comment]
Please refer to https://github.com/CelestiaProject/Celestia/blob/master/INSTALL, both MSVC and GCC (Mingw) are supported.

**Comment by shujaatak** [comment]
IMHO build method described here  https://github.com/CelestiaProject/Celestia/blob/master/INSTALL is so complex and time consuming that some developers wouldn't even think to try to build the Celestia by themselves leave aside contributing. This method is so discouraging.
IMHO all ThirdParty libs should be integrated in Celestia repository which could be downloaded using  `git clone --recursive https://github.com/CelestiaProject/Celestia.git` or directly using `git clone https://github.com/CelestiaProject/Celestia.git`. This way the developer would only need to build and run the project that's it. At least core project should be easy to build and run. The optional packages can be allowed to be configured through vcpkg.

**Comment by 375gnu** [comment]
I would like to see how you integrate GNU gettext, without official support for MSVC and CMake, GLEW (autogenerated, so it requires 2 stage build), lua and libpng. I also would like to see how you recompile Qt every time you change the main CMakeList.txt or pass another option to CMake.

![popcorn](https://user-images.githubusercontent.com/1612688/69655602-f8432200-1087-11ea-89fd-0c6ead9b5030.jpg)

**Comment by larsnaesbye** [comment]
Let's gradually make the build instructions better so we can get even more contributors!
I've started softly with #573 ...

**Comment by larsnaesbye** [comment]
@eyvallah : Would you like me to rewrite it in Markdown?

**Comment by eyvallah** [comment]
> @eyvallah : Would you like me to rewrite it in Markdown?

That would be great, go ahead

**Comment by larsnaesbye** [comment]
@eyvallah : Here you go -> #579 

Could probably use some linting and extra line breaks, but it's a start :-)
