### ISSUE TITLE
Sun halo in different starfield rendering modes

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#541]
Both in 1.6 and 1.7 versions. Depending on starfield's style a sun halo either present or not:
No halo with scaled disks:
![disks](https://user-images.githubusercontent.com/1612688/69856079-da4f0a80-129d-11ea-8fc5-e8ac7784ca24.png)
Halo present with points and fuzzy points:
![fuzzy](https://user-images.githubusercontent.com/1612688/69856265-4cbfea80-129e-11ea-9b07-dd609a4804b1.png)
![points](https://user-images.githubusercontent.com/1612688/69856268-4e89ae00-129e-11ea-9a91-68765aa76431.png)

1.7 had the same behaviour before #533. Now it has less bright halo in «points» and «fuzzy points» modes.

Quite interesting is that Alexell's version didn't have this bug. UPD: when vp&fp programs doesn't present, so older strarfied with quads is in use.

**Comment by SevenSpheres** [comment]
solution: implement #2

**Comment by SevenSpheres** [comment]
> 1.7 had the same behaviour before #533. Now it has less bright halo in «points» and «fuzzy points» modes.

I can confirm this; in fact I've mentioned it in #523 and #589, and made a duplicate issue for it at #596 (sorry!) Still agreed with my comment above. I'll post my screenshots again here.

Sun in older 1.7 build, with star style set to fuzzy points:
![nonbuggysun](https://user-images.githubusercontent.com/56284207/74072534-58c5d800-49c4-11ea-872c-7f2f8b49d17a.png)

Sun in newer 1.7 build, with star style set to fuzzy points:
![darksunbug2](https://user-images.githubusercontent.com/56284207/74072530-582d4180-49c4-11ea-8474-71011a930507.png)

**Comment by SevenSpheres** [comment]
This apparently affects Celestia Origin's rogue planet addon as well (`BlendTexture` seems to be broken):

![rogueplanetbug](https://user-images.githubusercontent.com/56284207/74109301-5471fa00-4b3f-11ea-9315-ef1d714dbecc.png)

@375gnu I think this should be labeled "high priority".

**Comment by 375gnu** [comment]
These visual glitches are related, but are not the same.
