### ISSUE TITLE
1.7 build: Planet rings don't show

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#545]
Planetary rings don't seem to ever show, even when I have "planet's rings" turned on. 

In fact, the "planet's rings" button seems to just toggle the ring shadows. The rings shadows only appear when both the "ring shadows" and "planet's rings" are turned on.

Here's a screenshot:
![saturnringless](https://user-images.githubusercontent.com/45546434/69890326-0f218880-12c3-11ea-901f-3409370dc711.png)

**Comment by SevenSpheres** [comment]
Rings show for me, so I guess this is a Mac-specific bug.

**Comment by LukeCEL** [comment]
Okay. I recompiled the entire thing, and now the rings show. This time I didn't run `git submodule update --init` but other than that, I have no idea what could have possibly made the rings disappear.
