### ISSUE TITLE
Stars becoming yellow

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#549]
@375gnu: remember the time I referenced this problem on the Celestia forums [here](https://celestia.space/forum/viewtopic.php?p=142395#p142395)? Well, I think I found the problem. The stars turn yellow as soon as a model with point sprites is loaded.

Here's a screenshot before the model is loaded:
![beforesprites](https://user-images.githubusercontent.com/45546434/69904829-b2cd7000-1379-11ea-8cf9-b8f23bd44786.png)

Here's a screenshot after the model is loaded:
![aftersprites](https://user-images.githubusercontent.com/45546434/69904839-d55f8900-1379-11ea-8663-e8a431f6f3d4.png)

I have confirmed that the stars turn yellow right when the console displays:
> Loading model: "extras-standard/Nebula - Sprites/models/hltau.cmod"

**Comment by SevenSpheres** [comment]
@LukeCEL how many of these models do you have? Can you share them in the "Add-on releases" section of the forum?

**Comment by 375gnu** [comment]
Once again unbound textures. There are so many places in code which introduce implicit dependencies between different parts of rendering code.

**Comment by LukeCEL** [comment]
@SevenSpheres @375gnu It will take some time to finalize and publish all the models, but for now I've made a new repository: [spritestest](https://github.com/LukeCEL/spritestest). Note that this effect occurs with both SSC and DSC files.

**Comment by 375gnu** [comment]
@LukeCEL could you test the current `master`? I'm unable to reproduce the issue.

**Comment by LukeCEL** [comment]
Hmm... unfortunately the issue still seems to persist.

![bugstillhere](https://user-images.githubusercontent.com/45546434/70083626-c4fa1900-15da-11ea-8daf-2c08c47c55fe.png)

**Comment by eyvallah** [comment]
i can reproduce it with @LukeCEL 's repo, it went yellow in the middle of the trip going to HL TAU

**Comment by SevenSpheres** [comment]
You know, I had never actually tested this addon in 1.7.0. I just did and I'm unable to duplicate this bug, so it's probably Mac only.
