### ISSUE TITLE
Undefined Q_NAMESPACE

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#55]
Hi @pirogronian,

I'm compiling on Debian 9 based system, Qt version is 5.7.1.

```
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DGLEW_STATIC -DEIGEN_NO_DEBUG -DEIGEN_NO_DEBUG -DNDEBUG -DNO_DEBUG -DTHEORA -DLUA_VER=0x050300 -DCELX -DCONFIG_DATA_DIR=\"/opt/celestia/share/Celestia_QT\" -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../Celestia -I. -I../../Celestia -I../src -I../thirdparty/glew/include -I../thirdparty/Eigen -I../thirdparty/curveplot/include -I/usr/local/cspice/include -isystem /usr/include/libdrm -isystem /usr/include/lua5.3 -isystem /usr/include/libpng16 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Imoc -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o obj/qtglwidget.o ../src/celestia/qt/qtglwidget.cpp
In file included from ../src/celestia/qt/qtappwin.h:16:0,
                 from ../src/celestia/qt/qtmain.cpp:29:
../src/celestia/qt/QtCelestiaCoreApplication.h:8:5: error: ‘Q_NAMESPACE’ does not name a type
     Q_NAMESPACE
     ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:83:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdatetime.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QTime:1,
                 from ../src/celestia/qt/qtmain.cpp:19:
../src/celestia/qt/QtCelestiaCoreApplication.h:11:9: error: expected ‘}’ before end of line
         Q_OBJECT
         ^
../src/celestia/qt/QtCelestiaCoreApplication.h:11:9: error: expected declaration before end of line
Makefile:24631: recipe for target 'obj/qtmain.o' failed
make: *** [obj/qtmain.o] Error 1
```

Q_NAMESPACE was introduced in Qt 5.8, we should support older versions used by current OSes.

**Comment by pirogronian** [comment]
I added Q_NAMSPACE when I though it is needed, however later I realized it isn,t but forgot to remove it. Sorry for that.

**Comment by Alexell** [comment]
In any case, we use QT 5.9 to compile Celestia, so it's not important.

**Comment by 375gnu** [comment]
You use 5.9 but there are still a lot of systems which use older versions. Debian 9 is a current stable and will be supported for the next ~4 years, Ubuntu 16.04 (EOS in 2021) uses 5.5, Ubuntu 14.04 uses 5.2 (EOS in next year). I don't know about other OSes.

So if your target is only you and some of your friends then you may not care about older OSes but if you target it for wider audience then you should care about other systems.

**Comment by Alexell** [comment]
@375gnu If all this is so, then you are right.
I work only on Windows and for me there is no problem installing any version of QT.
I hope that @pirogronian will fix the problem.

**Comment by Alexell** [comment]
@375gnu @pirogronian I will soon have a new computer and I think I will not install QT 5.9.2 (Windows), if this is not really necessary.
Can I compile Celestia on previous versions? Which version do you recommend to me?
So I can also notice if there are compatibility problems in the future.

**Comment by 375gnu** [comment]
I'd like to say that support for Ubuntu 14.04 & Debian 8 shipping 5.2.x and 5.3.x Qt version, but their compilers don't support C++ 11 fully, and we have 2 stable releases for Ubuntu and 1 for Debian, so 5.5 or 5.7 as lowest supported version is a good start. RedHat 7 and Suse 12 have 5.6.2.

I don't know exactly but suspect that OSX users can install any version like Windows users.

So to be sure that Celestia works on Ubuntu 16 (I suppose it's the most popular version) you should have 5.5.x.

**Comment by Alexell** [comment]
@375gnu Goog. Then on the new computer I install QT 5.5 and will report if there are problems with the compilation. Thanks!
