### ISSUE TITLE
Localization problems on Ubuntu

### ISSUE THREAD

**Issue by cjvth** [CelestiaProject/Celestia#561]
I have Ubuntu 19.10 (Celestia bionic release) with Russian language. Your program translates not all the text.
![](https://user-images.githubusercontent.com/40120650/70371328-2df7ce80-1904-11ea-89fa-d951660a9ac1.png)
Menubar and its items and window names aren't translated. Furthermore, there are problems with digit group separators.

**Comment by cjvth** [comment]
P.S. Also, some planet textures are missing (this is Jupiter)
![White Jupiter](https://user-images.githubusercontent.com/40120650/70371581-72d13480-1907-11ea-998c-83f397bd10d4.png)

**Comment by 375gnu** [comment]
The problem with translation of GTK+ interface is known for 1.6.1. It's fixed in upcoming 1.6.2 and 1.7.0.

To have all textures you should install celestia-common-nonfree package.

**Comment by 375gnu** [comment]
You can join https://www.transifex.com/celestia/celestia/dashboard/ to translate Celestia for 1.7 version.
