### ISSUE TITLE
Celestia's fonts need more special characters

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#570]
In Celestia's data files, non-ASCII characters can be escaped like "\u00ec" (ì), but some characters aren't supported. For instance, [Gǃkúnǁʼhòmdímà](https://en.wikipedia.org/wiki/229762_G%C7%83k%C3%BAn%C7%81%CA%BCh%C3%B2md%C3%ADm%C3%A0) can be escaped as "G\u01c3k\u00fan\u01c1\u02bch\u00f2md\u00edm\u00e0", but the name appears in Celestia as "G?kún??hòmdímà".

[Relevant thread](https://celestia.space/forum/viewtopic.php?f=3&t=20094)

**Comment by eyvallah** [comment]
with ttf support in 1.7.0, this should no longer be a problem

**Comment by SevenSpheres** [comment]
> with ttf support in 1.7.0, this should no longer be a problem

Yeah I realize that now, probably shouldn't have made an issue.

**Comment by SevenSpheres** [comment]
I've been using the Arial font with the latest 1.7 builds, and Gǃkúnǁʼhòmdímà's name can now be rendered correctly:

![gkunhomdimafix](https://user-images.githubusercontent.com/56284207/74071291-c96af580-49c0-11ea-8f82-9f07045d47a2.png)

**Comment by SevenSpheres** [comment]
Fixed by #669
