### ISSUE TITLE
ScriptedOrbit doesn't work

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#576]
Both in 1.6.2 and 1.7. With lua 5.1, 5.3 and luajit. More info and test data: https://celestia.space/forum/viewtopic.php?p=147641#p147641

**Comment by 375gnu** [comment]
supposedly 3fedf866ffd6d7ce6373db60b2541124057b307f is to blame

**Comment by SevenSpheres** [comment]
Why is this labeled as "release blocker"?

**Comment by 375gnu** [comment]
Because no next release can be made without this bug fixed.

**Comment by SevenSpheres** [comment]
> Because no next release can be made without this bug fixed.

Oh of course. Guess I didn't get what "release blocker" means.
