### ISSUE TITLE
Clicking certain stars or deep space objects causes 1.7.0 to crash

### ISSUE THREAD

**Issue by LafuenteAstronomy** [CelestiaProject/Celestia#592]
This issue has been reported by PlutonianEmpire in the Forum. More details here:
https://celestia.space/forum/viewtopic.php?f=3&t=20156&sid=c2b1339238ab07b8b23d6c34db547fe7

**Comment by SevenSpheres** [comment]
I'm unable to reproduce this bug.

**Comment by SevenSpheres** [comment]
[Another thread describing a same/similar issue.](https://celestia.space/forum/viewtopic.php?f=3&t=20712) I assumed it was caused by an addon, but maybe not.

**Comment by SevenSpheres** [comment]
Update: [this issue seems to be caused by missing or incorrect custom templates.](https://celestia.space/forum/viewtopic.php?p=153637#p153637) I'm not sure whether it's actually a bug.
