### ISSUE TITLE
Stars too dark in latest 1.7 builds

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#596]
I've previously mentioned this in #523 and #589.

In the latest 1.7 builds (since January 12 at the latest), stars viewed close up appear too dark, as if "scaled disks" mode was on. Here is the screenshot I posted previously:

![darksunbug](https://user-images.githubusercontent.com/56284207/73597492-c61bc980-44e9-11ea-9928-9ae1d77897df.png)

Here it is with the default gstar texture:

![darksunbug2](https://user-images.githubusercontent.com/56284207/73597533-26ab0680-44ea-11ea-82c3-1de6c715392d.png)

Here's what it looks like in older 1.7 builds, so you can see the difference:

![nonbuggysun](https://user-images.githubusercontent.com/56284207/73597585-aa64f300-44ea-11ea-8868-3f8ec0483c08.png)

**Comment by LukeCEL** [comment]
Confirmed on my build

**Comment by 375gnu** [comment]
Actually this problem exists in 1.6 version too. In OpenGL 2 and Vertex Programs modes.

**Comment by SevenSpheres** [comment]
> Actually this problem exists in 1.6 version too. In OpenGL 2 and Vertex Programs modes.

It does not? Please show screenshots.

**Comment by LukeCEL** [comment]
> Actually this problem exists in 1.6 version too. In OpenGL 2 and Vertex Programs modes.

For me the problem exists in 1.6 only when "Scaled Discs" is on and when the rendering path is "DOT3+ARB VP" or "OpenGL 2.0".

**Comment by SevenSpheres** [comment]
Found the cause of this mentioned in #541:

> 1.7 had the same behaviour before #533. Now it has less bright halo in «points» and «fuzzy points» modes.

**Comment by SevenSpheres** [comment]
Actually this is a duplicate issue, closing
