### ISSUE TITLE
GLEW initialize error

### ISSUE THREAD

**Issue by Alexell** [CelestiaProject/Celestia#60]
Hi all.
Celestia run perfectly and work on my computer **with QT installed**.
But when running on a computer where there is no installed QT, Celestia produces an error:
**Celestia was unable to initialize OpenGL extensions (error 1). Graphics quality will be reduced.**

An error occurs when glew initializing (src/celestia/qt/qtappwin.cpp line 260).

How can I fix it?

**Comment by 375gnu** [comment]
Do you link Qt libs statically so it starts without Qt installed?
I'd check whether that system has proper OpenGL subsystem, afaik default video drivers installed by Windows might lack OpenGL support.

**Comment by Alexell** [comment]
@375gnu I'm not doing anything, just doing the compilation of celestia.pro in QT Creator. Then I place the executable file in the Celestia 1.6.1 folder and add the necessary dll files: libintl_x86.dll, Qt5Core.dll, Qt5Gui.dll, Qt5Multimedia.dll, Qt5Network.dll, Qt5OpenGL.dll, Qt5Widgets.dll, platforms/qminimal.dll, platforms/qoffscreen.dll, platforms/qwindows.dll

On two computers where I tried to start Celestia 1.7.0 there are no problems with OpenGL, because Celestia 1.6.1 works great.

**Comment by Alexell** [comment]
Now found out that Celestia 1.7.0 works on NVIDIA and other GPU, but does not work on integrated Intel GPUs.
**Checked on the following:**
`Vendor: Intel
Renderer: Intel(R) HD Graphics
Version: 3.1.0 - Build 9.17.10.4459
GLSL version: 1.40 - Intel Build 9.17.10.4459
Max simultaneous textures: 8
Max texture size: 8192
Point size range: 1.000000 - 20.000000`

**and**
```
Vendor: Intel
Renderer: Intel(R) HD Graphics 3000
Version: 3.1.0 - Build 9.17.10.4459
GLSL version: 1.40 - Intel Build 9.17.10.4459
Max simultaneous textures: 8
Max texture size: 8192
Point size range: 1.000000 - 20.000000
```

It is important that on both these computers Celestia 1.6.1 works perfectly.

**Comment by 375gnu** [comment]
You might be missing some dynamically loadable opengl modules for qt5. https://doc.qt.io/qt-5/windows-requirements.html is a good start to get info about how to run opengl with qt5 and windows.

**Comment by Alexell** [comment]
Any dlls specified in this document, I already tried to add in Celestia folder (with compiled execulable), but nothing helped.
It will be hard for me to understand the entire document, to translate it into my native language for a long time.

**Comment by 375gnu** [comment]
you should use tools provided by qt to copy required dll instead of doing this manually.
