### ISSUE TITLE
Scripts don't work in QT version

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#601]
When I have the QT version of Celestia 1.7.0 open and run a script (CEL or CELX) it doesn't work; Celestia 1.6.2 opens instead. When I have the Win version of 1.7.0 open scripts work fine. I'm using the Appveyor builds, if it matters. I see that #64 exists, but it doesn't seem to be the same thing.

**Comment by 375gnu** [comment]
I've just tested the latest build (created for #607) under wine and everything was just fine.

**Comment by SevenSpheres** [comment]
I'm seeing the same behavior with this build. Nothing in the console, because the script is being sent to the default Win version (1.6.2 for me) instead of the Qt version that is actually running.

**Comment by 375gnu** [comment]
One question: what do you mean by "run a script" and "the script is being sent"? Do you use "File" -> "Open Script" or something else?

**Comment by SevenSpheres** [comment]
I was double-clicking on the actual .cel script file. I tried File -> Open Script and that does work; for some reason I hadn't thought of using that. Still a bug though.

**Comment by 375gnu** [comment]
That's an OS integration, windoze won't magically associate *.cel files with Celestia.
