### ISSUE TITLE
`BlendTexture` property is ignored

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#602]
This apparently affects Celestia Origin's rogue planet addon as well (`BlendTexture` seems to be broken):

![rogueplanetbug](https://user-images.githubusercontent.com/56284207/74109301-5471fa00-4b3f-11ea-9315-ef1d714dbecc.png)

@375gnu I think this should be labeled "high priority".

_Originally posted by @SevenSpheres in https://github.com/CelestiaProject/Celestia/issues/541#issuecomment-583889172_

**Comment by SevenSpheres** [comment]
> @375gnu I think this should be labeled "high priority".

To be clear this was referring to the star rendering issue (#541), not the `BlendTexture` issue.

Also, `BlendTexture` still works correctly for objects in the Solar System (e.g. Sedna). That's why I assumed this was the same as the star rendering issue.

**Comment by 375gnu** [comment]
@SevenSpheres could you test https://ci.appveyor.com/project/375gnu/celestia/builds/30729994/artifacts?

**Comment by SevenSpheres** [comment]
That fixes it!
