### ISSUE TITLE
Update installation instructions (CelestiaContent)

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#606]
Now that there's the CelestiaContent repository holding all the data files, there should be some note of that in the installation instructions.

**Comment by SevenSpheres** [comment]
See also [CelestiaContent#4](https://github.com/CelestiaProject/CelestiaContent/issues/4)

**Comment by eyvallah** [comment]
maybe we can make CelestiaContent repo a submodule of Celestia repo, and change the CMakeLists accordingly @375gnu

**Comment by 375gnu** [comment]
We need to clean-up CelestiaContent and provide proper debian/* files before this.

**Comment by eyvallah** [comment]
this is done in INSTALL.md
