### ISSUE TITLE
startextdump.cpp doesn't output spherical coordinates

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#623]
The tool startextdump.cpp, in src/tools/stardb, has a command-line argument `--spherical` (or `-s`), which makes it output a stars.txt with X, Y, and Z instead of the desired RA, Dec, and Distance.
 
Andrew Tribick explained it better in [this reply](https://celestia.space/forum/viewtopic.php?p=148169#p148169). Basically the `DumpStarDatabase` function doesn't know about the `useSphericalCoords` variable.

**Comment by 375gnu** [comment]
Technically that's not a bug. Only old DB was using spherical coordinates, so it's obvious to use them in a dumped text file.

**Comment by LukeCEL** [comment]
That's fair, I do see now that it says on the readme:
> The spherical option is ignored unless the input is an old format star database.

Strangely though, makestardb *does* come with its own spherical option, that a user would get from the nonexistent startextdump.

I'll make a PR soon.
