### ISSUE TITLE
Albedo question

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#624]
In Celestia 1.7.0, the parameter `Albedo` has been deprecated and replaced by `BondAlbedo` and `GeomAlbedo`. I assumed that for backwards compatibility `Albedo` would still work. I tested this by defining two planets with the same orbital distance but different albedos. Celestia displays the same temperature for both planets. So if `Albedo` does still work, it's being interpreted as the geometric albedo, not the bond albedo.

Here's the .ssc I used, if needed:
```
"A" "HIP 102152" {
	Class "planet"
	Radius 6000
	EllipticalOrbit {
		Period 1
		SemiMajorAxis 1
		ArgOfPericenter 90
	}
	Albedo 0.1
}

"B" "HIP 102152" {
	Class "planet"
	Radius 6000
	EllipticalOrbit {
		Period 1
		SemiMajorAxis 1
		ArgOfPericenter 270
	}
	Albedo 0.7
}
```

**Comment by LukeCEL** [comment]
Note: As I've said before, `Albedo` in 1.6.1 represents the Bond albedo, according to the [Wikibook](https://en.wikibooks.org/wiki/Celestia/SSC_File#Albedo_f). It makes sense because the `Albedo` parameter has to be between 0 and 1.

**Comment by 375gnu** [comment]
It was added after discussion with Celestia Origin team. Old implementation was geometric one actually that's why `Albedo` is an alias for `GeomAlbedo`. `BondAlbedo` was added to properly calculate body temperature.
