### ISSUE TITLE
Error reading PNG textures with indexed color palette ("Puckman" bug)

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#635]
Screenshot from 2018 that explains the bug name. This is Puck, a moon of Uranus:
![puckman_for_github](https://user-images.githubusercontent.com/44873271/75676219-e03bf980-5c99-11ea-88ef-e8b30df370ef.png)
Today I tested this old texture again because a few more people found this bug, and not only on models.

The texture was tested on 1.6.1 and 1.7.0 (from September 2019), the result is identical. A quarter of the object becomes invisible, everything else becomes translucent. At the places of overlapping the visible part and their eclipsed brightness add up (which is expected from translucency). Also near the observed stratification of the texture by colors, stripes perpendicular to the equator. I suppose that the problem may be with the additional data in PNG that Celestia cannot read correctly. 

Almost the same texture with and without a bug:
[puck_textures.zip](https://github.com/CelestiaProject/Celestia/files/4275326/puck_textures.zip)

Screenshots:
1.6.1 (+CO)
![image](https://user-images.githubusercontent.com/44873271/75675794-eaa9c380-5c98-11ea-974b-e17aab98d050.png)
1.7.0
![image](https://user-images.githubusercontent.com/44873271/75675815-f7c6b280-5c98-11ea-86ae-5b4ba83732d8.png)
![image](https://user-images.githubusercontent.com/44873271/75675839-0d3bdc80-5c99-11ea-9181-111df3b55d37.png)

**Comment by SevenSpheres** [comment]
I confirm this bug.

**Comment by hv-work** [comment]
In provided example:
- good image is true RGB
- bad image has indexed palette

**Comment by Askaniy** [comment]
Thanks, you're right. But I just indexed palette of texture and tested it, and it worked fine. So the problem is something else.

**Comment by Askaniy** [comment]
Sudden sequel. It seems that there is also a bug in the specular maps of a certain type, I will study it.
![image](https://user-images.githubusercontent.com/44873271/83688019-5fbcca00-a5f5-11ea-8a74-4dfebf224dcf.png)
![image](https://user-images.githubusercontent.com/44873271/83688189-ab6f7380-a5f5-11ea-8c1e-798355fa7419.png)

**Comment by Askaniy** [comment]
I checked Puck's textures and these specular maps for the mode in Pillow (Python library). 
Сlear result: **Celestia doesn't read correctly PNG textures with the indexed color palette**, it's the  [mode `P`](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes) in Pillow.
