### ISSUE TITLE
missing most famous polar star Alpha Ursae Minoris

### ISSUE THREAD

**Issue by MagicPoulp** [CelestiaProject/Celestia#636]
**Describe the bug**

The most famous double star called polar star is not in the list.
Alpha Ursae Minoris, alpha Umi

Also the start has different names so one should be able to search both full name and small name ideally.

**To Reproduce**

just search in start, including multiple stars.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. GNU/Linux, Windows, macOS]
 - Frontend: [e.g. Qt, native Win, native Mac]
 - Version: [e.g. 1.7.0]

Debian 10, Qt5, latest celestia of today.

**Additional context**

**Comment by LukeCEL** [comment]
Hi @MagicPoulp, what search term did you use? Using “Polaris” should work, as well as “ALF UMi”. Celestia uses abbreviated constellation names and Greek letters.

**Comment by SevenSpheres** [comment]
Polaris can be selected by typing:
- `polaris`
- `alrukaba`
- `alf umi`
- `alpha umi`
- `alpha ursae minoris`
- `1 umi`
- `1 ursae minoris`
- `hip 11767`
- `hd 8890`
- `sao 308`

I suggest closing as "invalid".

**Comment by GurrenLagannTSS** [comment]
I agree with SevenSpheres. This feels like a mistake a 5-year-old could had done.

**Comment by SevenSpheres** [comment]
Thinking about this more, if I assume good faith as much as possible, this:
> The most famous **double star** called polar star is not in the list.

could *just possibly* be interpreted as meaning that Polaris isn't rendered as a double star. This can be fixed by downloading the [Binary Star Catalog](http://celestiamotherlode.net/catalog/show_addon_details.php?addon_id=1676) addon.

**Comment by LukeCEL** [comment]
> This feels like a mistake a 5-year-old could had done.

Don’t say that, that’s rude.

**Comment by GurrenLagannTSS** [comment]
> Don’t say that, that’s rude.
What do you expect, its my typical behavior for stupid bug reports!

**Comment by MagicPoulp** [comment]
OK thanks.

I just found in the doc how to search a star by name (using ENTER).
I only had the tabs to the left with a limited amount of stars.

**Comment by 375gnu** [comment]
@GurrenLagannTSS does your behaviour attract new users? If you continue this way I'll block your access to the issue board.

**Comment by SevenSpheres** [comment]
> OK thanks.
>
> I just found in the doc how to search a star by name (using ENTER).
> I only had the tabs to the left with a limited amount of stars.

Ah, I should have realized you were looking in the Celestial Browser. If you select "Brightest Stars" (instead of "Closest Stars"), you can find Polaris there too.

**Comment by MagicPoulp** [comment]
There many things I want to do but I lack the energy to search in the doc.

In any case, I say it here:
I have put split sky into constellations. But I cannot see the names of the constellations.

I just learnt that the polar star is in the ursa minor and that it looks like a bear with ears. Quite cool to see shapes in the sky.

**Comment by 375gnu** [comment]
File->Preferences, or quick access buttons on the panel.

**Comment by MagicPoulp** [comment]
The B in the quick menu shows constellation boundaries. But I cannot see the name of the constellations anywhere. The boundaries are not clickable.

And how do I find Ursa Major?

**Comment by 375gnu** [comment]
that's becomes ridiculous. is it so hard to press all buttons and check preferences box?

**Comment by MagicPoulp** [comment]
Ah thanks I found it.

Well im not good finding stuff. Sorry.
