### ISSUE TITLE
celx file-io does not work with qt version

### ISSUE THREAD

**Issue by GottfriedSp** [CelestiaProject/Celestia#64]
the file-io does not work with qt, but it works with native windows (1.7.0)
This example script demonstrate it.
[scripts.zip](https://github.com/CelestiaProject/Celestia/files/2163702/scripts.zip)

First command is for allowing io access: (this ask the first time for permission to file access: y = yes, ESC = cancel, any other key = no)
`celestia:requestsystemaccess()`
I have tried y, Y, and z (german keyboard changed the key 'y' and 'z' from english layout)
The next statement causes a "Fatal Error" [string "scripts/Test.celx"]:11: attempt to index global 'io' (a nil value)
`f = assert(io.open(pathname .. "/data.txt", "r"))`
See link to lua manual 1.5.0 and later [https://en.wikibooks.org/wiki/Celestia/Celx_Scripting/CELX_Lua_Methods](url)

The celestia:getobserver():goto does not go to destination with newer lua interpreter (goto has no label)

**Comment by 375gnu** [comment]
What Lua version do you use?

`goto` is a keyword in Lua 5.2 so the method was renamed to `gotoobject`, but it's still available as `goto` on Lua 5.1 and earlier.

So that I assume that you use Lua 5.2 or 5.3 that might dropped automatic loading of `io` library as it did for `coroutines`.

**Comment by 375gnu** [comment]
@GottfriedSp please test #65

**Comment by GottfriedSp** [comment]
Ok, I try the gotoobject.

The other thing I found in celx.cpp line 744, this i changed to:
`        if(strcmp(c_p, "y") == 0 || strcmp(c_p, "Y") == 0)`
The qt sends from CelestiaGlWidget::keyPressEvent line 535 the key 'Y':
`            appCore->charEntered('Y');`
Now it works perfectly.
From Windows native the key 'y' comes from MainWindowProc() line 4291:
`            appCore->charEntered(utf8CharCode, modifiers);`

I added the commit into my Pull request. (Each new Push from my local repository added to the Pull request to the open Pull request here, and I don't know why)

Current Lua: 5.1.5
I try to update to Lua 5.3.4 but I think this works also.

**Comment by 375gnu** [comment]
If you use windows, then the only supported Lua so far is 5.1. Only Unix builds support Lua 5.2 & 5.3.

That's quite strange that you have io==nil with 5.1, my Celestia 1.6.2 linked against Lua 5.1 works with your script.

**Comment by GottfriedSp** [comment]
Ok, maybe the Qt 5.6.3 for windows.
When I click into screen and press ENTER and then press the keys "p r o x i m a" I see in the screen the word "prOXIma" - see screenshot below.
![proxima](https://user-images.githubusercontent.com/7338172/42291884-e1c04bd4-7fce-11e8-94e7-8c9917f4e4f9.png)
It works with both, my changes and the changes #65 
The system cyllene looks like this picture:
![cyllene](https://user-images.githubusercontent.com/7338172/42292069-24fd45cc-7fd0-11e8-8f23-b4d06e87abc1.png)

I have Qt5.6.3 windows 64-bit with platformtoolset v140 and 32-bit with platformtoolset v140_xp
Qt with msvc2015 compiler (visual studio and qt-creator)
I build the lua 5.1 and 5.3 with visual studio 2015 as static lib and the 5.3 also works with the current celestia 1.7.0

**Comment by GottfriedSp** [comment]
The io==nil comes from the upper case 'Y' even if i press 'y'

**Comment by GottfriedSp** [comment]
You're right, I tested Lua 5.3 with windows and celestia crashes -> switch back to 5.1 for windows.

**Comment by 375gnu** [comment]
So, let's summarize:

1. Qt related code sends incorrect characters (uppercased), so your dcaa0a725 just workarounds the problem in one particular case. We need a better fix.
2. celestia:requestsystemaccess() should either abort script if 'y' wasn't pressed or return false so script author can process it.

**Comment by 375gnu** [comment]
1b1781d (partially) and 0c6786b should be reverted as they are ugly hack and cause this issue.

**Comment by GottfriedSp** [comment]
But the check for 'y' or 'Y' should be ok if the caps lock is pressed or the user click the key 'Y'.
The other code also should be changed, I see for VK_C:
`        else if (e->modifiers().testFlag(Qt::ShiftModifier))
            appCore->charEntered('C');
        else
            appCore->charEntered('c');
        break;
`
But this is not clean code to add this for each keystroke, I look for a better solution for that.

**Comment by GottfriedSp** [comment]
Ah, ok i see, the defines with hexadecimal values.
I think the cases with the same functionality can be blocked together

**Comment by Alexell** [comment]
Partially fixed?

**Comment by 375gnu** [comment]
Yes, only partially. Now if you press 'y' then celx code receives 'y' not 'Y', but we still need to properly fix case when 'Y' is pressed (trivially) and make celestia:requestsystemaccess() return result (not so easy because of asynchronous nature of how interaction with user is implemented).
