### ISSUE TITLE
[Question] Best way to implement common database?

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#647]
As I decided to implement unified database by small steps, I have to choose most  painless way. Here are possible ways to gather common routines:
1. As a static members of AstroObject (my favourite)
2. As a static members of stardb and  #dsodb parent class
3. As a normall class which stardb and dsodb would access via pointer/reference (imho worst case)
If no response, I will start with 1st option once #641 will be accepted.

**Comment by hv-work** [comment]
without experiments i can't suggest anything. but i would again suggest taking a look on openspace and gayasky as they are able to handle much large star sets.

**Comment by pirogronian** [comment]
Ah, I meant rather organisation of code itself, not particular alghoritms or data structures. So, I will do it with the easiest way and later it can be always changed.

**Comment by hv-work** [comment]
code organization depends on algorithms and other decisions, it's not 1st class citizen

**Comment by 375gnu** [comment]
Just one question, if you have common database, how will you extract DSO only and stars only from it in efficient way?

**Comment by pirogronian** [comment]
I dont know yet and in fact now I'm unsure if I will able to implement fully common database. In astrodb I had separate stl sets, which takes some memory, but not as much. Anyway, I finally replaced it by filters on main index container to save some memory. Now I'm unsure, how far unification will proceed. Astrodb had some performance issues, as you know.
