### ISSUE TITLE
[Git related] some commits have wrong date.

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#648]
At first I was surprised, when wached in github summary, that repo has "Last commit by 375gnu about 3 months ago", because I know new commits arrives every few days. Now noticed that today commit of @375gnu is dated at november 2019. Apparently it's not critical issue, but a bit misleading at first for someone from outside.

**Comment by hv-work** [comment]
that's okay. i have some branches started long-long time ago, when i cleanup them merging commits, commits keep their creation date. that's okay.
