### ISSUE TITLE
[LuaJIT] Celestia crashes at closing lua error dialog.

### ISSUE THREAD

**Issue by pirogronian** [CelestiaProject/Celestia#656]
**Describe the bug**
When there is a syntax error in Lua script and Celestia is showeing an erro dialog, clicking "ok" cause a crash.

**Expected behavior**
Yy, not crashing?

**Backtrace**

> #_0  0x00007ffff756e9a0 in  () at /usr/lib/libluajit-5.1.so.2
> #_1  0x00007ffff75aafb3 in lua_getfield () at /usr/lib/libluajit-5.1.so.2
> #_2  0x0000555555813479 in LuaState::cleanup() ()
> #_3  0x00005555557ffd60 in celestia::scripts::LuaScript::~LuaScript() ()
> #_4  0x00005555558028d2 in celestia::scripts::LuaScriptPlugin::loadScript(std::experimental::filesystem::v1::__cxx11::path const&) ()
> #_5  0x00005555557c6de9 in CelestiaCore::runScript(std::experimental::filesystem::v1::__cxx11::path const&) ()
> #_6  0x0000555555637511 in CelestiaAppWindow::slotOpenScriptDialog() ()
> #_7  0x00007ffff6559540 in  () at /usr/lib/libQt5Core.so.5
> #_8  0x00007ffff6fb6f33 in QAction::triggered(bool) () at /usr/lib/libQt5Widgets.so.5
> #_9  0x00007ffff6fb961c in QAction::activate(QAction::ActionEvent) () at /usr/lib/libQt5Widgets.so.5
> #_10 0x00007ffff7146773 in  () at /usr/lib/libQt5Widgets.so.5
> #_11 0x00007ffff714e01c in  () at /usr/lib/libQt5Widgets.so.5
> #_12 0x00007ffff714f063 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
> #_13 0x00007ffff700148e in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
> #_14 0x00007ffff71516cc in QMenu::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
> #_15 0x00007ffff6fbd362 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
> #_16 0x00007ffff6fc6a68 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
> #_17 0x00007ffff6523a12 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
> #_18 0x00007ffff6fc5afb in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
>     at /usr/lib/libQt5Widgets.so.5
> #_19 0x00007ffff701d5d8 in  () at /usr/lib/libQt5Widgets.so.5
> #_20 0x00007ffff701fbc4 in  () at /usr/lib/libQt5Widgets.so.5
> #_21 0x00007ffff6fbd362 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
> #_22 0x00007ffff6fc6819 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
> #_23 0x00007ffff6523a12 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
> #_24 0x00007ffff68ec574 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
> #_25 0x00007ffff68edcb6 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
> #_26 0x00007ffff68c6bcc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
> #_27 0x00007fffeffeebcc in  () at /usr/lib/libQt5XcbQpa.so.5
> #_28 0x00007ffff25229be in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
> #_29 0x00007ffff2524831 in  () at /usr/lib/libglib-2.0.so.0
> #_30 0x00007ffff2524871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
> #_31 0x00007ffff657c0d0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #_32 0x00007ffff652257c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
> #_33 0x00007ffff652a586 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
> #_34 0x000055555562c30c in main ()

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Frontend: Qt
 - LuaJIT
 - Version: master + lua-get-star-dso (but I believe it's not related)

**Comment by 375gnu** [comment]
Hi @pirogronian , I don't see any  `lua_getfield()` calls inside `LuaState::cleanup()`. Please ensure that you can reproduce the bug with `master`.

**Comment by 375gnu** [comment]
@pirogronian is it still reproducible?
