### ISSUE TITLE
Black holes should be texture-less

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#662]
**Is your feature request related to a problem? Please describe.**
Currently Celestia uses the neutron star texture for black holes, which makes black holes look...wrong. This can be fixed by setting a nonexistent texture for neutron stars. I did this in my pull request #660, but @375gnu said I should open an issue instead.

**Describe the solution you'd like**
The texture for black holes should be independent from that for neutron stars (specifically, black holes shouldn't have a texture).

**Describe alternatives you've considered**
The workaround described above, which @375gnu doesn't like.

**Comment by 375gnu** [comment]
And they are: https://github.com/CelestiaProject/Celestia/blob/master/src/celengine/star.cpp#L743
![blackhole](https://user-images.githubusercontent.com/1612688/78502102-fd1b8f00-7767-11ea-8e1a-15d2682dd0ae.png)

How did you manage to assign texture to it? In 1.6.x this code is the same as well.

**Comment by 375gnu** [comment]
ha, it seems that #607 fixes this :)

**Comment by SevenSpheres** [comment]
> ha, it seems that #607 fixes this :)

> @SevenSpheres could you confirm?

Yes, it does fix it!
