### ISSUE TITLE
Earth texture bug

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [CelestiaProject/Celestia#675]
**Earth texture bug**
This bug occurs what I open the 1.6.2 beat 2 under my late 2006 MacBook Pro with an ATY,RadeonX1600 GPU while under Mac OS X 10.7.5 (via firewire target disk mode since it normal runs 10.6.8).

**Screenshots**
![celestia_1 7 0_error](https://user-images.githubusercontent.com/57239744/77414950-2287c080-6d98-11ea-9726-f365a3b52104.jpg)

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.7.5 Lion (booted via firewire of an iMac)
 - Frontend: Mac
 - Version: 1.6.2 beta 2

**Comment by 375gnu** [comment]
could you provide console output (press ~)?

**Comment by Anthony-B-Russo10** [comment]
![1 6 2_error_1](https://user-images.githubusercontent.com/57239744/77599692-ea899600-6edb-11ea-83e1-e78c68554d17.jpg)
![1 6 2_error_2](https://user-images.githubusercontent.com/57239744/77599694-eb222c80-6edb-11ea-83ba-896c372a276e.jpg)
Here are the console outputs.

**Comment by 375gnu** [comment]
What about 1.6.1 on the same system?

**Comment by Anthony-B-Russo10** [comment]
1.6.1 under the same system doesn't suffer from this problem, it displays correctly under the same computer while running either Snow Leopard or Lion.
Snow Leopard:
![image](https://user-images.githubusercontent.com/57239744/78511106-1ae8f400-7768-11ea-8d12-7a7dc2e05a83.png)
And Lion:
![image](https://user-images.githubusercontent.com/57239744/78511653-70bf9b00-776c-11ea-9d4e-f6a05748bc8b.png)

**Comment by eyvallah** [comment]
there should not be a major change in render, except that I removed the workaround for very old graphics card, ATI 9200. can you maybe launch from Terminal (or show package contents - Contents - macOS - Double click on Celestia) and see if there is any log output?

**Comment by 375gnu** [comment]
And if something is different when you change rendering mode (Basic, Multitexture, etc)?

**Comment by SevenSpheres** [comment]
Since there is now a [Mac build of 1.7.0](https://celestia.space/forum/viewtopic.php?p=148771#p148771), could you see if it has the same bug?

**Comment by eyvallah** [comment]
> Since there is now a [Mac build of 1.7.0](https://celestia.space/forum/viewtopic.php?p=148771#p148771), could you see if it has the same bug?

This build doesn’t support his system (10.7) it runs only on 10.10+

**Comment by Anthony-B-Russo10** [comment]
The two graphics modes between GL 2.0 and DOT 3 aren't supported on my MBP, my 17" iMac and maybe my 20" iMac since I decided to test the 17" and it has the same problem.
But here are the other Graphics modes:
DOT3+ARB VP
![image](https://user-images.githubusercontent.com/57239744/79037817-5dfcfa00-7ba2-11ea-8da5-1745b9675963.png)
Multitexture- the only one that works
![image](https://user-images.githubusercontent.com/57239744/79037835-808f1300-7ba2-11ea-8204-03970cecc61b.png)
Basic
![image](https://user-images.githubusercontent.com/57239744/79037857-ab796700-7ba2-11ea-80aa-cdc20fa8559c.png)

Though in order to test 1.7.0, all I have to do is patch the iMac that the OS is stored on up to 10.10.

**Comment by levinli303** [comment]
let's close this, supporting old Mac is too much work and not realistic as it gets.
