### ISSUE TITLE
[1.7.0] Attempting to lock orbit frame can crash Celestia

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#677]
**Describe the bug**
Typing `Shift+;` to lock orbit frame sometimes causes Celestia to crash, but only sometimes. This occurs only in 1.7.0, not in 1.6.x.

**To Reproduce**
1. Type `Shift+;`
2. Celestia crashes, if not try again until it does

**Expected behavior**
Celestia does not crash.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Frontend: both Qt and native Win
 - Version: 1.7.0, latest build as of today

**Additional context**
Reported by **Nrco0e**/**N3cronium** on Discord and confirmed by me. Not reproducible by @LukeCEL on Mac.

**Comment by 375gnu** [comment]
I'm unable to reproduce. Any chance you run this under debugger?

**Comment by SevenSpheres** [comment]
> Any chance you run this under debugger?

I have to assume you mean Visual Studio's debugger. In that case, no, since [when I try to compile Celestia VS gives me errors](https://celestia.space/forum/viewtopic.php?f=4&t=20269).

**Comment by SevenSpheres** [comment]
seems to be fixed by #793
