### ISSUE TITLE
[1.7.0] Ring texture render bug

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#678]
**Describe the bug**
When viewing Celestia Origin's J1407 b in Celestia 1.7.0, its rings appear odd and grainy, and flicker. Additionally, in the Windows native version (but not the Qt version), the planet's texture doesn't display.

**To Reproduce**
1. Set up Celestia 1.7.0 with Celestia Origin (or just that one planet and its textures)
2. Go to the planet (`1SWASP J140747.93-394542.6/b`)
3. See bug

**Expected behavior**
The rings (and planet) render normally.

**Screenshots**
Qt:
![ringbugqt](https://user-images.githubusercontent.com/56284207/77600074-60860100-6ecc-11ea-95e2-387704810d3d.png)
Native Windows:
![ringbugwin](https://user-images.githubusercontent.com/56284207/77600079-61b72e00-6ecc-11ea-9cad-a2527d961501.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Frontend: Qt and native Win, but *different* behavior in each
 - Version: 1.7.0, latest build as of today

**Additional context**
Reported by **Nrco0e**/**N3cronium** on Discord and confirmed by me. There seems to be no connection to either #574 or #635.

**Comment by 375gnu** [comment]
This is actually #574

**Comment by 375gnu** [comment]
for missing planet texture please provide console output and please don't create 1 bug reports for 2 or more issues.

**Comment by 375gnu** [comment]
And texture is too large for rings.

**Comment by SevenSpheres** [comment]
> This is actually #574

No it isn't, I changed the planet's obliquity and the bug didn't go away.

> for missing planet texture please provide console output and please don't create 1 bug reports for 2 or more issues.

Actually I'm no longer seeing the missing texture bug, so I don't know what happened there. I guess the two commits between then and now fixed it.

> And texture is too large for rings.

It works in 1.6.x though.

**Comment by 375gnu** [comment]
They use a fake "diffuse" object with rings to draw large rings, so this is #574 actually.

Big texture works, but there is no guaranty that it will work properly on all hardware and software, etc. It should be resized to 1024x1.

**Comment by SevenSpheres** [comment]
> They use a fake "diffuse" object with rings to draw large rings, so this is #574 actually.

I'm aware of that, and I changed the obliquity of that object as well. This isn't #574.

**Comment by 375gnu** [comment]
@SevenSpheres please stop changing labels

**Comment by SevenSpheres** [comment]
This is **not** a duplicate.

**Comment by SevenSpheres** [comment]
Still reproducible with [J1407b-test.zip](https://drive.google.com/file/d/1PgA7d3FLV8cgFT6or0mFo0RPmpVAgrSt/view?usp=sharing)

**Comment by SevenSpheres** [comment]
Resizing J1407b's ring texture to 1 pixel height reduces rendering artifacts but does not completely remove them. The remaining artifacts are more noticeable on the native Windows frontend.

![j1407bug](https://user-images.githubusercontent.com/56284207/148596670-ec04e9ea-5c55-41bf-b82d-dea214b474f5.png)

**Comment by 375gnu** [comment]
That's because there are 2 objects occupy the same place: rings themselves and diffuse objects. This artifact is called Z-fighting. There is no fix exists for it, only workarounds.
