### ISSUE TITLE
how to detect surface maps in sub-folders of extras

### ISSUE THREAD

**Issue by MagicPoulp** [CelestiaProject/Celestia#680]
Help would be appreciated thanks. I just built celestia 1.7 on linux, no errors.

I tried to load mars surface maps
http://celestiamotherlode.net/catalog/mars.php

for the jester 16K maps, I could map it work
extra/mars_m46_dds_vt/
and everyhing else is in the subfolder

-- I tried with the 32K maps.
but if things are in a sub folder it is not detected. I had the same problem before.

There are several zip files
What does it mean level 0-3, 4, 5?
Do I need all of them and where should I put the Mars.ctx separate file? Not documentted
since I want to have many surface maps, I dont think it is good to have everything at the root of extras.

**Comment by MagicPoulp** [comment]
I found this but it did not help
https://www.classe.cornell.edu/~seb/celestia/addon-intro.html

**Comment by MagicPoulp** [comment]
Now I have new problems:

now I see it. I just copied all files.
The Mars.ctx seems to have no effect. Maybe it must be somewhere special.

the alternate map has become the default, it is not selectable it took over  the normal one.
I dont want this I want it to be selectable in the right click.

it seems that the maps for long range are of bad quality and bad resolution
but when I zoom, it seems to have higher resolution than the 16K map.

**Comment by MagicPoulp** [comment]
So the main problem I have is to make the 32K selectable instead of taking over the default.

if I copy only the lvl 5 textures, it seems to look better. THe 16K from another addon seems to have a certain sharp contrast format. So maybe it is normal the 32K does not look so good in comparison.

**Comment by 375gnu** [comment]
@MagicPoulp this bugzilla is for issues related to data shipped with Celestia. To discuss 3rd-party addons, ask questions and other unrelated topics please use our forum  https://celestia.space/forum/ or discord  https://discordapp.com/invite/WEWDcJh. To educate about VT levels you can start with https://en.wikibooks.org/wiki/Celestia/Textures#Virtual_Textures . And don't forget that some addons were created on windows which filesystem is case-insensitive.

**Comment by MagicPoulp** [comment]
ok sorry
