### ISSUE TITLE
Error in CMakeLists.txt

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#685]
Yes, I'm trying to compile Celestia now!

**Describe the bug**
See [this thread](https://celestia.space/forum/viewtopic.php?f=4&t=20269). Compiling Celestia, even 32-bit Celestia, requires 64-bit packages. I'm not entirely sure that this is a bug, but this means that it's impossible for people on 32-bit systems (e.g. @GurrenLagannTSS) to compile Celestia.

**To Reproduce**
Um...try to compile 32-bit Celestia without 64-bit packages?

**Expected behavior**
32-bit Celestia compiles with no errors when 64-bit packages aren't installed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.7.0, latest commit as of today

For @GurrenLagannTSS:
 - OS: Windows 7
 - Version: https://github.com/GurrenLagannTSS/EnhancedCelestia

**Comment by 375gnu** [comment]
VS provides several *.bat files and entries in start menu to invoke "native x86", "native x64", "cross-compiling x86 on x64", etc environments. For 32 bit run "native x86" and perform all next actions in this console window. For 64 bit use "native x64".

**Comment by SevenSpheres** [comment]
> VS provides several *.bat files and entries in start menu to invoke "native x86", "native x64", "cross-compiling x86 on x64", etc environments. For 32 bit run "native x86" and perform all next actions in this console window. For 64 bit use "native x64".

1. That's not what INSTALL.md says to do
2. I can't find these batch files in the start menu, at least not by searching "Visual Studio" (yes, I do have VS2019 installed)

**Comment by 375gnu** [comment]
i don't know what vs2019 provides. 2015 & 2017 do this.

**Comment by SevenSpheres** [comment]
> i don't know what vs2019 provides. 2015 & 2017 do this.

I've already uninstalled and reinstalled VS twice (2019 -> 2017, then 2017 -> 2019). I don't want to do it again.

**Comment by SevenSpheres** [comment]
I tried starting from scratch - ignoring INSTALL.md and just using Visual Studio. I immediately get a warning:
![warning](https://user-images.githubusercontent.com/56284207/78830111-ab137d00-79a4-11ea-95cf-7bbe06d923d4.png)
which is the exact same warning cmake gave me, that I thought I had fixed by installing 64-bit packages. So really this seems to be an issue with CMakeLists.txt.

**Comment by 375gnu** [comment]
CMakeLists.txt doesn't have any issue. Please stop reopening incorrect issues and start reading documentation for tools you want to use. This warning about optional dependency - gettext binaries. It's not required to compile.

**Comment by SevenSpheres** [comment]
And yet I did install gettext binaries through vcpkg...

**Comment by 375gnu** [comment]
Use this one https://mlocati.github.io/articles/gettext-iconv-windows.html and update PATH
