### ISSUE TITLE
INSTALL.md has incomplete instructions for Windows

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#687]
I tried to compile Celestia by following the instructions in INSTALL.md.

On the first try I got cmake errors which were fixed by installing 64-bit versions of all vcpkg packages. According to @375gnu in #685, I should have done something with some unspecified batch files instead of doing what INSTALL.md says to do; in that case INSTALL.md should be updated with clear instructions on what to do with these batch files.

After installing the necessary packages and following the instructions again, everything worked, and I thought I would have an executable. Instead all I had were Visual Studio project files. Again, INSTALL.md needs to make this clear.

I'm also unable to get Visual Studio to compile Celestia from the project files, but that's for another issue.

Relevant thread [here](https://celestia.space/forum/viewtopic.php?f=4&t=20269).

**Comment by SevenSpheres** [comment]
> On the first try I got cmake errors which were fixed by installing 64-bit versions of all vcpkg packages.

This seems to actually be an issue with CMakeLists.txt; see #685.

**Comment by 375gnu** [comment]
Where is you PR to fix docs?

**Comment by SevenSpheres** [comment]
> Where is you PR to fix docs?

When I get compiling to work, I might make one.
