### ISSUE TITLE
Build for macOS 10.15 Catalina (64-bit)

### ISSUE THREAD

**Issue by brettalton** [CelestiaProject/Celestia#689]
Hi there!

**Is your feature request related to a problem? Please describe.**
I've followed a few of the bug/feature threads and saw a macOS/64-bit build is in the works for the 1.6.2 branch (and possibly 1.7.0). However, in the INSTALL file, it just says "clone the source" (https://github.com/CelestiaProject/Celestia/blob/master/INSTALL.md#celestia-install-instructions-for-macos-qt-only). Is there a specific branch I'm supposed to be using or is this in the master branch that 64-bit compiling will run on 10.15? I'm not sure what version master is at as the branches are unclear of this. Sorry, I just don't see clear instruction and am relatively weak at building from source--I'm sure you're busy fixing and compiling and not updating the docs so that's why I thought I'd ask here!

**Describe the solution you'd like**
Beta builds of the branches and future releases (currently 1.6.2beta and 1.7.0beta) if possible!

**Describe alternatives you've considered**
Automated building of releases perhaps? Not sure how that's done...

**Additional context**
Thank you!

**Comment by eyvallah** [comment]
You can build 1.7.0 (qt version) from the master branch for now. 1.6.x branch lack some dependency libs in the repo, so I wouldn’t recommend.

The instruction should have detailed the way how you build it. Follow it and you should be able to get it working.

**Comment by SevenSpheres** [comment]
You can also download 1.6.2 already built for macOS from [here](https://github.com/CelestiaProject/Celestia/releases/tag/1.6.2-beta2).

**Comment by eyvallah** [comment]
> You can also download 1.6.2 already built for macOS from [here](https://github.com/CelestiaProject/Celestia/releases/tag/1.6.2-beta2).

Thanks for mentioning it. Also there is a experimental 1.7.0 build available here https://celestia.space/forum/viewtopic.php?p=148771#p148771

**Comment by brettalton** [comment]
I just tried compiling from 'master' myself and this is the issue I had. Is this what you're referring to @eyvallah?

![Screen-Shot-2020-04-10-at-6 57 38-PM](https://user-images.githubusercontent.com/108411/79032732-aba34380-7b5d-11ea-8f31-bd341f3c9178.jpg)

I will try those builds @SevenSpheres & @eyvallah, thank you so much!

**Comment by brettalton** [comment]
@SevenSpheres your link to the 1.6.2beta2 released worked! Thank you so much!

@eyvallah your link to the 1.7 build also worked, thank you so much!

<img width="870" alt="Screen Shot 2020-04-10 at 7 09 15 PM" src="https://user-images.githubusercontent.com/108411/79032897-cb873700-7b5e-11ea-9ecd-eae9538cccc0.png">

**Comment by eyvallah** [comment]
> I just tried compiling from 'master' myself and this is the issue I had. Is this what you're referring to @eyvallah?
> 
> 
> 
> ![Screen-Shot-2020-04-10-at-6 57 38-PM](https://user-images.githubusercontent.com/108411/79032732-aba34380-7b5d-11ea-8f31-bd341f3c9178.jpg)
> 
> 
> 
> I will try those builds @SevenSpheres & @eyvallah, thank you so much!

Ok it seems to be the CelestiaContent change

To compile it, you need to run 
git submodule update --init
After you clone this repo


Also you need to add ‘-DENABLE_DATA=ON’ to your cmake command

**Comment by eyvallah** [comment]
closing for #690
