### ISSUE TITLE
celestia fails to compile with libfmt 6.2

### ISSUE THREAD

**Issue by joequant** [CelestiaProject/Celestia#695]
**Describe the bug**

Celestia fails to compile with libfmt 6.2 because many of the string sprintf's appear to require
string casts that do not exist

**To Reproduce**

Attempt to compile celestia with libfmt 6.2

**Expected behavior**
Should compile

**Desktop (please complete the following information):**
 - OS: Linux with gcc 9.3

**Additional context**
working on a patch right now.

**Comment by 375gnu** [comment]
Hi @joequant
Thanks for reporting, but please don't waste your time to create a patch: the bug is in `fmt` code and it's been fixed in `HEAD`. So for now either go back to 6.1.2 or use `fmt` built from `HEAD`.

**Comment by joequant** [comment]
Thanks!!!  Saved me some time

**Comment by joequant** [comment]
Also can you point me to the commit what has the libfmt bug?

**Comment by 375gnu** [comment]
Bad commit - https://github.com/fmtlib/fmt/commit/f72a905eb3f003ccc13596daff223a3f2b494164
Fixed in https://github.com/fmtlib/fmt/commit/e99809f29da1002e8b9246e9278084ad231174e5
