### ISSUE TITLE
What does CustomTemplate do for globulars?

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#697]
This is a question. The Wikibook lists `CustomTemplate` as a parameter for globular clusters, but @SevenSpheres tried experimenting with it and it didn't seem to affect globular rendering in any way. I also tried, and again, it didn't seem to change anything.

I tried looking at src/celengine/globular.cpp to see what the parameter does, but I am not sure what it does, or even if it does _anything_.

**Comment by 375gnu** [comment]
It presented even in the initial globular.cpp and even then it was doing nothing. I suppose t00fri used galaxy.cpp as a template, so some unneeded lines of code were left. I will remove them.
