### ISSUE TITLE
Will 1.6.2 have updated data?

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#699]
This question came up in the Discord. Since we have the CelestiaContent repo, which is somewhat independent from the Celestia core, does that mean that Celestia 1.6.2 will have data updates as well? Or is the data update only for 1.7.0?

**Comment by SevenSpheres** [comment]
I'm 99% sure that 1.6.2 won't have data updates, which kind of defeats the point of CelestiaContent, but there's not much I can do about it...

**Comment by Anthony-B-Russo10** [comment]
But still, 1.6.2 needs a data update period.

**Comment by 375gnu** [comment]
I definitely would like to have updated data for 1.6.x.

**Comment by LukeCEL** [comment]
Oh, thank you for the response.
