### ISSUE TITLE
QT Celestial Browser sorting

### ISSUE THREAD

**Issue by CelestiaProject** [CelestiaProject/Celestia#7]
**_Need to fix a few defects in Celestial Browser (QT):_**
1. **Solar system**. Sort by name and type is not yet implemented.
2. **Stars**. Pressing the "name" button to sort by distance, not by name.
3. **Deep Sky Objects**. Pressing the "name" button to sort by distance, not by name.

**Comment by Alexell** [comment]
qtcelestialbrowser.cpp

**Comment by Alexell** [comment]
Function `bool StarPredicate`
`    case Alphabetical:
        return false;  // TODO`

**Comment by CelestiaProject** [comment]
@ajtribick, Maybe you can help us?

**Comment by CelestiaProject** [comment]
We think:
1. Add the fourth column "Asteroids and comets", and in the column "Solar System" show only the Planets, Dwarf Planets, Moons and Small Moons.
2. Perhaps for spacecraft need a fifth tab, because with a large number of additions, it would be convenient to see all the spacecraft separately.
3. We think that you can make the browser more informative and useful. The browser should contain more columns with parameters (Kepler parameters + the rest). The sorting should work for each column.

It is very important to create a quality catalog.

**Comment by CelestiaProject** [comment]
**In order not to increase the size of the Celestial Browser:**
There is a vertical scroll in the catalog table. Just add a horizontal scroll bar in table bottom. Then you can not change the size of the browser, and the columns that do not fit the width can be seen by sliding the horizontal scoll.

**Comment by gstark31897** [comment]
I made a pull request addressing name sorting on some of the tabs: https://github.com/CelestiaProject/Celestia/pull/43
The TreeView is a little more complicated to get sorting, so I might try working on the "Asteroids and comets" and spacecrafts tabs next.

**Comment by CelestiaProject** [comment]
@gstark31897 Thank you. Later we will check the work of your changes. We will be grateful if you completely solve the sorting problem described in the first message.

**Comment by gstark31897** [comment]
Alright, I'll focus on finishing up the solar system sorting then. Thanks.

**Comment by Alexell** [comment]
#43

**Comment by Alexell** [comment]
#43 already done.

**Comment by amirabbaska** [comment]
okkkkk

**Comment by 375gnu** [comment]
Hi @pirogronian , i suppose we can close this issue. The more I think the close I am to the conclusion that we don't need name/type sorting for the Solar System Browser.
1. It's initial sorting order is by distance from a parent (star, planet, etc). So we need an additional control to restore original sort order.
1. Sorting by type is useless as we have grouping. I also have some WIP filtering code.
1. Sorting by name should help to look up for required object. But for me it's better to add a search box instead.
