### ISSUE TITLE
Full screen does not work

### ISSUE THREAD

**Issue by GottfriedSp** [CelestiaProject/Celestia#70]
Full screen does not work with qt.
It resizes the window to max size but does not change to full screen.

**Comment by 375gnu** [comment]
Works for me. What OS & Qt version do you use?

**Comment by GottfriedSp** [comment]
The menuBar, the toolBars and the solarSystemBrowser is visible in full screen.
With the native windows interface all of this is hidden.
This should be hidden like in other programs (vlc media player, stellarium, media player, presentation programms, ...)

Windows 7 64bit
Qt 5.6.3

**Comment by 375gnu** [comment]
So, I suppose it's just not implemented. Do you wish to?

**Comment by GottfriedSp** [comment]
I can try this, but my vacation is over and could be taken some time.

**Comment by GottfriedSp** [comment]
Pull request is done with #81

**Comment by 375gnu** [comment]
this was fixed some time ago
