### ISSUE TITLE
Binary CMODs sometimes don't work if converted with comments

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#706]
**Describe the bug**
When converting a .cmod file from ASCII to binary, some binary .cmod files end up not working, because the original ASCII .cmod had comments on them.

**To Reproduce**
1. Go to https://celestia.space/forum/viewtopic.php?p=149095#p149095 and download the ASCII .cmod file (ic3568.cmod.zip). This .cmod file has comments on lines 2 and 8.
2. Use cmodfix to convert the file from ASCII to binary.
3. Test the new .cmod file. On some computers it works, but on other computers it doesn't.
4. Now, go to the original ASCII .cmod and delete the comments.
5. Use cmodfix to convert the file from ASCII to binary.
6. Test the new .cmod file. This time, it should render.

**Expected behavior**
I think what is happening (but I'm not sure) is that when converting from ASCII to binary, cmodfix (incorrectly) does not ignore the comments.

For now, a good workaround is to simply delete the comments from the ASCII .cmod before converting them to binary.

**Comment by 375gnu** [comment]
@LukeCEL what `cmodfix` do you use: 1.6 or 1.7?

**Comment by LukeCEL** [comment]
1.7 - I used the one that I got when compiling Celestia

**Comment by 375gnu** [comment]
with your test data everything is fine on my installation

**Comment by LukeCEL** [comment]
You mean Abell 39? Ah yes, I uploaded that model before I really knew what was going on.

Anyway, here is an add-on containing the model that was problematic for everyone.

[IC3568.zip](https://github.com/CelestiaProject/Celestia/files/4561970/IC3568.zip)

**Comment by 375gnu** [comment]
I was talking about ascii model for IC 3568 from the forum. I was able to convert it to binary representation without any issues. And resulting file is identical to your ic3568bin-functional.cmod.

Very strange. The only problem with ascii model that I see is that it messes up line endings, some lines use `0x0d`, some other use `0x0a`.

**Comment by LukeCEL** [comment]
Indeed, the binary cmod still works for me in 1.6.1, but not in 1.7. It's very strange.

**Comment by 375gnu** [comment]
@LukeCEL could you confirm this issue with up-to-date code?

**Comment by LukeCEL** [comment]
I think this issue has been fixed - I used the newest cmodfix on an ASCII ic3568.cmod, and they both seemed to work:
[ic3568b_c.cmod.zip](https://github.com/CelestiaProject/Celestia/files/7615559/ic3568b_c.cmod.zip) - original ASCII file has comments
[ic3568b_nc.cmod.zip](https://github.com/CelestiaProject/Celestia/files/7615560/ic3568b_nc.cmod.zip) - original ASCII file does not have comments

> Anyway, here is an add-on containing the model that was problematic for everyone.
> 
> [IC3568.zip](https://github.com/CelestiaProject/Celestia/files/4561970/IC3568.zip)

I downloaded this model and it did not work, as expected, but it is also different in size - the others are 43 KB, but this is 60 KB. I am not sure why, but definitely using the new cmodfix I don't get any broken CMOD files.

**Comment by SevenSpheres** [comment]
Should this be closed?

**Comment by 375gnu** [comment]
seems yes
