### ISSUE TITLE
startextdump doesn't output the entire file

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#722]
When you output startextdump to a file, the file is cut off near the very end. For example with the default stars.dat, even though the last line should be HIP 120404, the last line looks like this:

```
118249 554.5157 -769.9752 336.2617 0.0
```
**To Reproduce**
Use startextdump to output a file, using this syntax:

```
startextdump stars.dat output.txt
```

From @ajtribick ([source](https://celestia.space/forum/viewtopic.php?p=149203#p149203)), the cause of the issue:

> Interesting... looking at the code I see what's going on: the ofstream is created on the heap via operator new and it is not deleted at the end of the program. So the ofstream destructor doesn't get called and the stream doesn't get flushed. (There are no explicit calls to flush the stream either)
> 
> The export of the HD cross-index from old-format database files (which contained the HD identifier in stars.dat) would exhibit the same problem, but unless you're doing archaeology on really old Celestia versions that shouldn't be too much of an issue.

**Additional notes**
A suitable workaround is to simply update the documentation, because this syntax works:
```
startextdump stars.dat > output.txt
```

**Comment by SevenSpheres** [comment]
I tested this earlier and it works correctly for me; it seems to be a Mac-specific problem.

**Comment by LukeCEL** [comment]
@375gnu: apparently makexindex has the same issue: https://celestia.space/forum/viewtopic.php?f=15&t=20195&p=149208#p149208
