### ISSUE TITLE
Cant run Celestia 

### ISSUE THREAD

**Issue by JustBruh** [CelestiaProject/Celestia#728]
Hi, when I tried to enter the command on the command line this error appears

CMake Error at CMakeLists.txt: 64 (include):
   include could not find load file: FastMath
CMake Error at CMakeLists.txt: 91 (EnableFastMath):
   Unknown CMake command "EnableFastMath"

Then similar error messages appear, but in which other files appear. I would like to ask for help.

![image](https://user-images.githubusercontent.com/60921666/81216939-76ff9c00-8fe4-11ea-821b-e0a9a1e144c9.png)

 - OS: [Windows10 x64]
 - Version: [e.g. 1.7.0]

**Comment by 375gnu** [comment]
you run cmake with `..` as source directory. do the following:
```
mkdir build
cd build
```
and then run cmake as you did
