### ISSUE TITLE
Can't install the Celestia

### ISSUE THREAD

**Issue by JustBruh** [CelestiaProject/Celestia#730]
**Describe the bug**
This is the same error, but only the Gettext file was not found in it.#728. It is  on a different machine, with Windows 10 x86, what should I do? I'm stumped with this problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/60921666/81268862-2d996600-9051-11ea-85e1-a14ddcf777da.png)

**Desktop:**
 - OS: [Windows10 x86]
 - Version: [e.g. 1.7.0]

**Comment by 375gnu** [comment]
You should install libraries for x64-windows triplet as the 1st cmake warning says.
```
vcpkg install --triplet=x64-windows libpng libjpeg-turbo gettext fmt libepoxy eigen3 qt5 luajit

```

or
```
vcpkg install libpng:x64-windows  libjpeg-turbo:x64-windows ...
```

**Comment by JustBruh** [comment]
Thank you

**Comment by JustBruh** [comment]
I did everything that you advised, but nothing has changed

**Comment by 375gnu** [comment]
show your vcpkg output and what do you have in vcpkg/packages/

**Comment by JustBruh** [comment]
vcpkg/packages/
![image](https://user-images.githubusercontent.com/60921666/81673225-f7465700-9453-11ea-911e-4890980d9d21.png)
But i haven't vcpkg output. I have only CMakeOutput.txt

**Comment by 375gnu** [comment]
> I have only CMakeOutput.txt

plz attach it

**Comment by JustBruh** [comment]
[CMakeOutput.log](https://github.com/CelestiaProject/Celestia/files/4615199/CMakeOutput.log)

**Comment by 375gnu** [comment]
it seems that you are missing `-DCMAKE_GENERATOR_PLATFORM=x64` parameter. add it before `-DCMAKE_TOOLCHAIN_FILE=`

**Comment by 375gnu** [comment]
btw, if you are using windows, you can simply copy files from https://ci.appveyor.com/project/375gnu/celestia/history. take the latest green build with id `1.7.0-dev-xyz` where `xyz` is a number.
