### ISSUE TITLE
Missing build for Ubuntu 20 LTS (focal)

### ISSUE THREAD

**Issue by ckuethe** [CelestiaProject/Celestia#752]
**Describe the bug**
There is no binary for Ubuntu 20 LTS (focal)

**To Reproduce**
Observ that there is no build for Ubuntu 20 on  https://bintray.com/celestia/releases-deb/celestia/view/readmore#read

**Expected behavior**
There should be a build for Ubuntu 20

**Screenshots**

**Desktop (please complete the following information):**
Ubuntu 20

**Additional context**

**Comment by 375gnu** [comment]
Built & uploaded.
