### ISSUE TITLE
ttf font rendering not working

### ISSUE THREAD

**Issue by wm-0007** [CelestiaProject/Celestia#755]
**Describe the bug**
Font rendering is not working correctly.

With the true type font listed in the default celestia.cfg enabled, a console message is displayed: 
Error loading font; text will not be visible.

With the default font "sans12.txf" enabled, no console message is displayed, but the text does not display completely at all sizes.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster) 
 - Frontend: Gnome
 - Version: 1.7.0 commit 7a062af

**Comment by 375gnu** [comment]
Please use our forum or discord for support requests (see README.md for URLs).

But as we here - how did you build Celestia?

**Comment by wm-0007** [comment]
Attached is my compile log from today, commit 2ce8147, with the same error message.

[compile-log.txt](https://github.com/CelestiaProject/Celestia/files/4775715/compile-log.txt)

**Comment by 375gnu** [comment]
you have compiled celestia without ttf support. you should pass `-DENABLE_TTF=ON` to `cmake`

**Comment by wm-0007** [comment]
Issue solved.
used cmake command: cmake .. -DENABLE_GTK=ON -DENABLE_TTF=ON -DCMAKE_INSTALL_PREFIX=/home/william/Celestia-Test/
