### ISSUE TITLE
1.6.2: incorrect spectral type parsing

### ISSUE THREAD

**Issue by LukeCEL** [CelestiaProject/Celestia#802]
**Describe the bug**
Stars that were encoded as spectral class "C" in 1.6.1 and 1.7.0 are being read as spectral class "Y" in 1.6.2.

**To Reproduce**
1. Make sure the star database being used is the default star database (from Celestia 1.6.1, not ajtribick's version).
2. Select HIP 26032 (which has a spectral type of C6II, in 1.6.1 and 1.7.0).
3. In 1.6.2, it has a spectral type of Y6II.

**Expected behavior**
Stars that were encoded as spectral class "C" in 1.6.1 and 1.7.0, should also be "C" in 1.6.2.

**Desktop (please complete the following information):**
 - OS: macOS (@SevenSpheres confirmed this for Windows)
 - Frontend: native Mac
 - Version: 1.6.2

**Additional context**
This seems to only affect stars in stars.dat. Spectral types defined using STC files seem to work properly. For example this code:

```
"CW Leo"
{
	RA 146.98919300 
	Dec +13.27876800
	Distance 310
	AppMag 10.96
	SpectralType "C9"
}
```

**Comment by 375gnu** [comment]
I forgot to backport an additional patch from `master` branch.
