### ISSUE TITLE
Speed of travel does not work linux

### ISSUE THREAD

**Issue by ferroao** [CelestiaProject/Celestia#811]
**Describe the bug**
At beginning speed text changes (bottom left text), when using speed keys, but in reality the speed has not changed.
When using speed keys A, Z, Fs, after some time of using Celestia, they don't change bottom left text. (speed never changes)

**To Reproduce**
1. Click on any key of speed

**Expected behavior**
Speed changing and also its text, always

**Desktop (please complete the following information):**
 - OS: GNU/Linux ubuntu 19.10
 - Version: 1.7.0~git20200723+68a741d6, 1.6 also tested

**Comment by 375gnu** [comment]
I'm unable to reproduce the issue. Are you using Qt or Gtk interface?

**Comment by ferroao** [comment]
qt, you can see details in:
https://askubuntu.com/questions/1081299/how-can-i-install-celestia-on-ubuntu-18-04-1#answer-1163925

**Comment by ferroao** [comment]
After removing qt (1.7) and installing gtk (1.6) I notice
the travel speed works only when at the end of the travel. For ex. If I go from sun to earth, and I am in a low speed. I arrive very quickly to earth, and only the last moments, or approximation (when destination is visible), are at the desired speed.

**Comment by 375gnu** [comment]
I checked both Qt/1.7 & Gtk/1.6.2 on Ubuntu 18.04. Everything works fine for me.

**Comment by 375gnu** [comment]
Could you write and post video?

**Comment by ferroao** [comment]
mmm, I have ubuntu 19.10. Will video  be useful? or details of my system? let me know.

**Comment by 375gnu** [comment]
video + description what actions you perform on what second

**Comment by ferroao** [comment]
1.6
video  https://www.youtube.com/watch?v=KNrI4UzBAdE
speed works near objects
I notice the travel speed works only when at the end of the travel. For ex. If I go from sun to earth, and I am in a low speed. I arrive very quickly to earth, and only the last moments, or approximation (when destination is visible), are at the desired speed.

for 1.7
no video
speed never works.
At beginning speed text changes (bottom left text), when using speed keys, but in reality the speed has not changed.
When using speed keys A, Z, Fs, after some time of using Celestia, they don't change bottom left text. (speed never changes)

**Comment by 375gnu** [comment]
Hi @ferroao ,

Actually you do journey incorrectly. Movement is performed into screen center. The best way to check is: select any far object (e.g. M 31), press F7 and you'll see changes.

**Comment by ferroao** [comment]
I tried, I centered M 31; a travel with 1 ly/s (F7) or any other speed, are the same.

**Comment by 375gnu** [comment]
please provide video

**Comment by ferroao** [comment]
thx, in this videos, with several speeds tested, you will see always the travalling text, bottom right, counting from 5 to 0, so time of travel does not depend on speed. (1.6.2)

https://youtu.be/ZUBHqD_wIf0
https://youtu.be/fJJneSv0mEI

**Comment by 375gnu** [comment]
@ferroao movement speed doesn't affect speed of "goto to object" function. they are 2 separate independent functions.

**Comment by ferroao** [comment]
thx, in version 1.7, speed keys dont do anything.

**Comment by 375gnu** [comment]
they work fine for me. if they don't work for you, you can try to debug.

**Comment by 375gnu** [comment]
also in our discord channel there is no confirmation for this issue
