### ISSUE TITLE
(One more) way to improve albedo

### ISSUE THREAD

**Issue by Askaniy** [CelestiaProject/Celestia#833]
Albedo-related improvement was first raised by the Celestia Origin team, then on Discord and here (#624).
Last time (on Discord) I wrote that it would be nice to connect `Albedo` to `BondAlbedo` too, but… `BondAlbedo` is limited to 1, while `GeomAlbedo` is unlimited. This can create problems with calculating temperatures for bodies with strongly directional reflectivity. 

So I propose to discuss adding four albedo parameters:

1. `Albedo` (from 0 to ∞)
For backward compatibility only. It isn't possible to cover all use cases with one parameter. 
_If specified, interpreted as `GeomAlbedo` as the most likely option._

2. `GeomAlbedo` (from 0 to ∞)
The geometric albedo is the most common parameter and the most useless for us 😕
If simplified, it is the brightness of the full disk (in zero phase angle). However, just in this case, the reflectivity of many bodies increases significantly (due to the [opposition surge](https://en.wikipedia.org/wiki/Opposition_surge)). For this reason, it will be much more accurate to use `Reflectivity` instead.
_Sets the `BondAlbedo` and `Reflectivity` values if it is <1, otherwise as 1._
Because imprecise values are better than no values.

3. `BondAlbedo` (from 0 to 1)
Nothing changes here. Still used for reliable temperature calculations.

4. `Reflectivity` (from 0 to 1)
This albedo has no generally accepted name (for example, "Normal albedo" is used [here](https://www.researchgate.net/figure/LORRI-albedos-on-Pluto-Panel-A-shows-normal-albedo-across-Pluto-from-LORRI-panchromatic_fig12_298918241)). 
It can probably be called "visual spherical albedo" or "visual Bond albedo". Without going into detail, this is the visible average global reflectivity, just what is needed for points' brightness if phase curves are unknown.

Here is an illustration of the light curves from [this](https://arxiv.org/abs/1511.04415) paper:
![light_curves](https://user-images.githubusercontent.com/44873271/91576226-54591080-e950-11ea-9d8e-85192c7cfbc7.png)
You can see the brightness peak at zero phase angle (corresponding to the geometric albedo). 
Table with parameters from the same paper, except for the Bond albedo:
Celestial body | `GeomAlbedo` |  `BondAlbedo` | `Reflectivity`
-- | -- | -- | --
Enceladus | 1.362 | [0.81](https://www.sciencedirect.com/science/article/abs/pii/S001910350900308X) | 1.0
Callisto | 0.235 | [0.05](https://www.sciencedirect.com/science/article/abs/pii/0019103580902183) | 0.09

What do you think about this? I tried to take into account all previous opinions.
_UPD: new albedo parameter renamed to `Reflectivity`_

**Comment by Panterstruck** [comment]
I have certainly experienced these issues, especially when dealing with Enceladus and other icy objects that have a strong specular reflection. So I'm for defining a proper value.

Problem is, how would we handle it? Sure geometric albedo is the most videly available parameter, but it's very inconsistent, depending on how it's measured. A normalized albedo value would help - but - won't this just be the bond albedo then? How do we define the normalized albedo? The most intuitive way I can think of is the geometric albedo phase function integrated over all phase angels... but that will give bond albedo right? Or a value proportional to it. Before we introduce these parameters, I want this properly defined.
And if that's done, how do we get said parameter? I understand you're proposing some kind of default reflectivity which might work... but im not sure.

**Comment by Askaniy** [comment]
You're right, as I mentioned in passing, this parameter is equivalent to visual Bond albedo. 
Better names can be chosen, for example, `VisualBondAlbedo` for dots' brightness and `BolometricBondAlbedo` for temperatures' calculations, but it may be too complex for common use by most addon builders. Although I may be wrong.

**Comment by Panterstruck** [comment]
How about calling it "Reflectivity"? Since we're talking about a handwaving albedo definition that overlaps with any official definitions, it would be quite confusing to make up a new albedo designation.

**Comment by Askaniy** [comment]
Good option
Another issue to consider: should we rename `BondAlbedo` and `GeomAlbedo` as in SE (`AlbedoBond` and `AlbedoGeom`) before it's too late? Or add both?

**Comment by 375gnu** [comment]
closed by #926
