### ISSUE TITLE
[1.7.0] Disk models rendered with black squares from some distances

### ISSUE THREAD

**Issue by SevenSpheres** [CelestiaProject/Celestia#840]
**Describe the bug**
When viewed from a close distance in Celestia 1.7.0, some (all?) disk models are rendered with a black square around them.

**To Reproduce**
1. Download Vision's Milky Way center addon from [here](https://celestia.space/forum/viewtopic.php?f=23&t=20030)
2. Go to Sgr A*
3. See bug

**Expected behavior**
Disks are rendered without black squares, as in 1.6 (and older 1.7 builds)

**Screenshots**
The bug at Sagittarius A*
![sgrablacksquare](https://user-images.githubusercontent.com/56284207/93686772-d206cc80-fa75-11ea-84ae-c6fa97f70dae.png)
Another example from Trolligi
![image](https://cdn.discordapp.com/attachments/721466900114178109/756886282948575262/wot.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Frontend: Qt/native Win
 - Version: 1.7.0

**Comment by levinli303** [comment]
I will probably investigate into It when I have time. if you got time, can you maybe try with older versions from appveyor so we can see which commit might be the faulty commit?

**Comment by SevenSpheres** [comment]
Seems to have been caused by #823

**Comment by levinli303** [comment]
More specifically, in this commit: https://github.com/CelestiaProject/Celestia/pull/823/commits/8983df3d576bd6e42ee56261102d050ea70f1367

as I add back line 2986/2987 in render.cpp, the issue is gone.

Since I'm no expert in GL, @375gnu how should we fix it

**Comment by 375gnu** [comment]
@levinli303 looks like you have found the root cause.

**Comment by levinli303** [comment]
should we add back the two lines or should we revert the commit?

**Comment by 375gnu** [comment]
Just get back those two lines.
