### ISSUE TITLE
Wrong name of constellations in Chinese version

### ISSUE THREAD

**Issue by QuantumJack1** [CelestiaProject/Celestia#856]
**Describe the bug**
The name of constellations Vela and Virgo are swapped in Chinese version of Celestia. 
**To Reproduce**
1. Run Celestia in Chinese language
2. Scroll to constellations Vela or Virgo
3. See error
**Screenshots**
![微信图片_20201018171617](https://user-images.githubusercontent.com/73057159/96363271-c6d2b980-1165-11eb-9810-2bd8c97468d8.jpg)
**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 1.6.1

**Comment by levinli303** [comment]
Thanks for reporting. indeed, it's in po2/zh_CN.po
