### ISSUE TITLE
Warped fisheye

### ISSUE THREAD

**Issue by pdbourke** [CelestiaProject/Celestia#869]
I just had a look at the warped fisheye support for spherical mirror projection systems ... great work.
How does one change the warp mesh though?
I installed this literally yesterday
    http://paulbourke.net/dome/directidome/
and it would be great to test Celestia on this true 4K Digital Projection projector.
Note, this warping is not only required for spherical mirror projection, this is a fisheye but because it's off center it needs warping also.

**Comment by levinli303** [comment]
Yeah that would be great! The mesh file used in the build I provided is Celestia.app/Resources/CelestiaResources/warp/warp.map, you can swap it with your own mesh file and it should work.

**Comment by pdbourke** [comment]
Ahhhh, thanks.
I did go for a browse through the Contents but clearly didn't dig far enough.

**Comment by levinli303** [comment]
good to see it working, it is the first time for me to see it on something other than a flat display. 😆

**Comment by levinli303** [comment]
Closing, we have fisheye support merged in the codebase and thus will be included in the next release.
