### ISSUE TITLE
celestia.desktop references celestia-gtk insted of celestia

### ISSUE THREAD

**Issue by mietinen** [CelestiaProject/Celestia#898]
src/celestia/gtk/data/celestia.desktop has Exec=celestia-gtk, but the binary is compiled as celestia.

**To Reproduce**
Install GTK version as described with:
  ./configure --with-gtk
  make
  make install

Celestia failes to open if launched from the menu, as it tries to run celestia-gtk. Which does not exist. The binary is simply named celestia. If launched from terminal it works just fine.

 - OS: Archlinux
 - Frontend: GTK

**Comment by 375gnu** [comment]
Hi @mietinen are you talking about 1.6.2?

**Comment by antonio-rojas** [comment]
Yes, this happens in 1.6.2
