### ISSUE TITLE
Missing meshes from dwarf-planets

### ISSUE THREAD

**Issue by vpontin** [CelestiaProject/Celestia#90]
Opening `data\solar-system\dwarf-planets\dwarf-planets.ssc` shows me dwarf planets like Pluto and Charon should have proper meshes (`pluto.cmod` and `charon.cmod`) but those arent on `meshes` folder and so when went to one of them nothing shows in-Celestia.

Is this intentional?

**Comment by vpontin** [comment]
The issue is still present: no pluto.cmod or charon.cmod exists on [models](https://github.com/CelestiaProject/Celestia/tree/main/models) folder.

**Comment by 375gnu** [comment]
Duplicates: #78
