### ISSUE TITLE
Debian_10 build failed on OBS: dpkg-source: error: can't build with source format '3.0 (native)'

### ISSUE THREAD

**Issue by munix9** [CelestiaProject/Celestia#911]
**Describe the bug**
Debian_10 x86_64 v1.7 master build on OBS failed:
`dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision`
Ubuntu builds are fine.

**To Reproduce**
See https://build.opensuse.org/package/live_build_log/home:munix9:unstable/celestia/Debian_10/x86_64

**Expected behavior**
Debian_10 build should not fail.
Maybe a problem with latest updates for Debian_10 and the definition in
https://github.com/CelestiaProject/Celestia/blob/master/debian/source/format
(should be 3.0 (quilt) ?!).

**Screenshots**

**Desktop (please complete the following information):**
Debian_10 build on OBS.

**Additional context**

**Comment by 375gnu** [comment]
Hi @munix9 ,

This is a problem on OBS side:
```
[  180s] Compressed celestia-1.7.0~git20210114+5360a165e.tar to celestia-1.7.0~git20210114+5360a165e.tar.xz
[  181s] /usr/lib/obs/service/set_version:33: RuntimeWarning: install 'packaging' to improve python package versions
[  181s]   RuntimeWarning)
[  181s] Found files matching debian.*, running debian transformer...
[  181s] release: (385.1), release (DEB) (385.1)
[  181s] ** Started: debtransform --release 385.1 //usr/src/packages/SOURCES //usr/src/packages/SOURCES/celestia.dsc //usr/src/packages/SOURCES.DEB
[  181s] No DEBTRANSFORM-TAR line in the .dsc file.
[  181s] Attempting automatic discovery of a suitable source archive.
[  181s] Source archive chosen for transformation: celestia-1.7.0~git20210114+5360a165e.tar.xz
[  181s] Transforming into source package 1.0 (non-native) format
[  181s] Added Debian revision to Version field, which is now "1.7.0~git20210114+5360a165e-1".
[  181s] converting //usr/src/packages/SOURCES/celestia-1.7.0~git20210114+5360a165e.tar.xz to celestia-1.7.0~git20210114+5360a165e.tar.gz
[  183s] Modifying dsc Version field to "1.7.0~git20210114+5360a165e-1"
[  183s] Moving //usr/src/packages/SOURCES/celestia-1.7.0~git20210114+5360a165e.tar.gz to //usr/src/packages/SOURCES.DEB/celestia_1.7.0~git20210114+5360a165e.orig.tar.gz
[  183s] files 87cf852d55ea152871681774fd843955 9191430 celestia_1.7.0~git20210114+5360a165e.orig.tar.gz
[  183s] Scanning //usr/src/packages/SOURCES.DEB/celestia_1.7.0~git20210114+5360a165e.orig.tar.gz...
[  183s] Generating //usr/src/packages/SOURCES.DEB/celestia_1.7.0~git20210114+5360a165e-1.diff
[  183s] Scanning //usr/src/packages/SOURCES/debian.tar.xz...
```

What is `debian.tar.xz` purpose? If this is something you created then please update its `debian/source/format` to `3.0 (quilt)`. Or better avoid its usage if it's possible.

**Comment by munix9** [comment]
No, I don't think that's a problem with OBS.
I created the `debian.tar.xz` manually for testing, normally this is created by OBS using the `_service` file.
The manually generated `debian.tar.xz` is identical to the content of the `debian` folder, with the difference that the `debian/source/format` file now contains `3.0 (quilt)` instead of `3.0 (native)`.
Apparently something has changed recently with Debian 10, so that the above error message appears during the build when `3.0 (native)` is used.

> Or better avoid its usage if it's possible.

No, this is required for building on OBS, has nothing to do with it and is normally generated automatically from `_service` file as described above (see also https://build.opensuse.org/package/view_file/home:munix9:unstable/celestia/_service?expand=1 - currently the section is disabled because of testing). After all, it worked before.

I will create a request for it.

**Comment by 375gnu** [comment]
Could you apply patches to generated `debian.tar.xz`?
