### ISSUE TITLE
Zoom-IN to key KP_1, Zoom-OUT to key KP_3

### ISSUE THREAD

**Issue by Bogdan107** [CelestiaProject/Celestia#916]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want this shortcuts to interactively zoom view:
- KP_1 - Zoom-IN
- KP_2 - Zoom-OUT

In my laptop:
- KP_1 - is key "1" on numeric block of keyboard, which has "1" and "INS" labels.
- KP_3 - is key "3" on numeric block of keyboard, which has "3" and "PG DN" labels.

```
# xev | grep keycode
keycode 87 (keysym 0xffb1, KP_1)
keycode 89 (keysym 0xffb3, KP_3)
```

**Additional context**
Celestia not use shortcuts KP_1 and KP_3. So, KP_1 and KP_3 shortcuts are free to take new functions.

**Comment by 375gnu** [comment]
Closed in favor or #917
