### ISSUE TITLE
build system not detecting GLES

### ISSUE THREAD

**Issue by milada-horakova** [CelestiaProject/Celestia#941]
celestia-qt builds, splash screen shows up, then calls wrong drawing function:
```
No provider of glPolygonMode found.  Requires one of:
    Desktop OpenGL 1.0
    GL extension "GL_NV_polygon_mode"
```
there is no glPolygonMode for wireframe drawing on GLES, the build system failed to detected this. 

1. build celestia-qt as instructed for debian 10
2. run celestia-qt

**Expected behavior**
application main window showing up

**Computer**
Memory		: 7882MB
Machine		: Raspberry Pi 4
Operating System		: Twister OS - Debian GNU/Linux 10 (buster)

**Display**
Resolution		: 1920x1080 pixels
Vendor		: The X.Org Foundation
Version		: 1.20.4
Current Display Name		: :0
-Monitors-
Monitor 0		: 1920x1080 pixels
-OpenGL-
Vendor		: Broadcom
Renderer		: V3D 4.2
Version		: 2.1 Mesa 20.3.0
Direct Rendering		: Yes
-Extensions-
Composite
DAMAGE
DOUBLE-BUFFER
DPMS
DRI2
DRI3
GLX
Generic Event Extension
MIT-SCREEN-SAVER
MIT-SHM
Present
RANDR
RECORD
RENDER
SECURITY
SHAPE
SYNC
X-Resource
XC-MISC
XFIXES
XFree86-DGA
XFree86-VidModeExtension
XINERAMA
XInputExtension
XKEYBOARD
XTEST
XVideo
default screen number:    0

**Processors**
ARM Cortex-A72 r0p3 (AArch32)		: 2000.00 MHz
ARM Cortex-A72 r0p3 (AArch32)		: 2000.00 MHz
ARM Cortex-A72 r0p3 (AArch32)		: 2000.00 MHz
ARM Cortex-A72 r0p3 (AArch32)		: 2000.00 MHz

**Comment by 375gnu** [comment]
@milada-horakova did you pass `-DENABLE_GLES=ON` to `cmake`?

**Comment by milada-horakova** [comment]
thank you very much

thought there were only other systems documented below _Celestia Install instructions for Windows (MSVC)_ in https://github.com/CelestiaProject/Celestia/blob/master/INSTALL.md and haven't scrolled below to see the cmake options 😅
