### ISSUE TITLE
Solar system objects drawn as points must have depth writing disabled

### ISSUE THREAD

**Issue by 375gnu** [CelestiaProject/Celestia#947]
**Describe the bug**
Planets drawn as GL points are drawn above labels.

**Comment by levinli303** [comment]
the bug still exists for stars.

<img width="678" alt="Screen Shot 2021-05-13 at 3 53 15 PM" src="https://user-images.githubusercontent.com/17924287/118095951-55a96b00-b403-11eb-82f3-58079155d94b.png">

**Comment by 375gnu** [comment]
Actually this is a different bug, i'll create a new issue for it.
