### ISSUE TITLE
Ubuntu 18.04 build fails on OBS

### ISSUE THREAD

**Issue by munix9** [CelestiaProject/Celestia#985]
Since https://github.com/CelestiaProject/Celestia/commit/bf10d8d6e1abdfc258a813c999333b2ce84ddd17 Ubuntu 18.04 build fails on OBS
https://build.opensuse.org/public/build/home:munix9:unstable/Ubuntu_18.04/x86_64/celestia/_log

**Comment by levinli303** [comment]
https://cmake.org/cmake/help/latest/command/target_link_directories.html target_link_directories is available on CMake 3.13, can we update the CMake version in the build script?

**Comment by munix9** [comment]
Hm, I can try to take this one for OBS for example:
https://build.opensuse.org/package/show/science:dlr/CMake
But what about those who want to build and install this locally on their PC?
There should be a note somewhere in INSTALL that a newer cmake is needed for Ubuntu 18.04

**Comment by levinli303** [comment]
with #986 would produce better error message when building with a lower version of CMake.

**Comment by munix9** [comment]
Would the use of https://cmake.org/cmake/help/v3.0/variable/CMAKE_VERSION.html make more sense?
At least as long as LTS Distries need it...
Something with
```
if(CMAKE_VERSION VERSION_GREATER 3.12)
...
```

**Comment by levinli303** [comment]
I suppose we can, although it will break Mac GTK builds with early version of CMake, anyway, I don't think anyone would be using the GTK frontend on Mac, or use an old version of CMake.

**Comment by munix9** [comment]
Anyway, for OBS I now have a cmake 3.14.1 for Ubuntu 18.04 in use:
https://build.opensuse.org/package/show/home:munix9:unstable/cmake
The build should now be fine again:
https://build.opensuse.org/project/monitor/home:munix9:unstable
